appium/appium-xcuitest-driver

.gitmodules
LICENSE

Resolves #18. Also fix license.
@Jonahss

Use https scheme for submodules

---

lib/commands/execute.js
lib/commands/find.js
lib/commands/gesture.js
lib/commands/index.js
lib/commands/proxy-helper.js
lib/driver.js
lib/simulatorManagement.js
lib/webdriveragent.js

maps locator strategy used in java-client to the locator strategy
Delegate certain commands to specific helper methods
Override locator strategies in specific commands.
Only create simulator if it does not exist in the list of current devices

Helper methods / Simulator Creation

---

lib/commands/find.js
lib/commands/gesture.js
lib/webdriveragent.js

new web driver requires installing dependencies via carthage. Cloning out of the box doesn't have dependencies. createXcodeBuildSubProcess will fail.

Download and install dependencies for WDA

---

.eslintignore
.eslintrc
.travis.yml
LICENSE
lib/commands/execute.js
lib/commands/find.js
lib/commands/index.js
lib/copySymlinks.js
lib/driver.js
lib/logger.js
lib/safari-launcher.js
lib/sample.js
lib/webdriveragent.js
package.json
test/functional/driver-e2e-specs.js
test/functional/safari-e2e-specs.js
test/functional/webdriveragent-e2e-specs.js
test/functional/webview-e2e-specs.js

Build still fails. Looking into it.

Update eslint and fix problems

---

.gitmodules
.travis.yml
README.md
index.js
lib/commands/execute.js
lib/commands/find.js
lib/commands/index.js
lib/driver.js
lib/logger.js
lib/server.js
lib/simulatorManagement.js
lib/webdriveragent.js
package.json
test/functional/driver-e2e-specs.js
test/functional/safari-e2e-specs.js
test/functional/webdriveragent-e2e-specs.js
test/functional/webview-e2e-specs.js
test/unit/webdriveragent-specs.js

Clean up code.
Move from local fork to Facebook version of WebDriverAgent.
Quarantine tests that use SafarDriver (Safari and webview tests) until that driver is fixed.

Update system to get tests running

---

lib/commands/index.js
lib/commands/source.js
lib/driver.js
package.json
test/functional/basic-e2e-specs.js
test/unit/commands/source-specs.js

This will approximate getting the source in current Appium. There are some problems (WDA returns "Other" for the type of table views, for instance) but this is useful for debugging purposes so I wanted to get it in early.

Add source command

---

docs/endpoints-wda.md
docs/endpoints.md

List of endpoints supported by Appium and WDA. To use in determining work to be done.

Add doc on endpoints

---

package.json

Add a pre-commit hook to lint and run unit tests on commit. This should eventually be added to all our working repos.

Add precommit hook so linting and tests run

---

gulpfile.js
lib/commands/general.js
lib/commands/index.js
lib/driver.js
test/functional/basic-e2e-specs.js
test/unit/commands/general-specs.js

Translation of the first part of #25.

Add backgrounding app

---

lib/commands/gesture.js
lib/driver.js
test/functional/gesture-e2e-specs.js
test/unit/commands/gesture-specs.js

Second half of #25. This will probably need to be rebased when #49 gets in.

Add tap command

---

lib/driver.js
lib/server.js

opts pass in address as a capability, not host.

shutdown any hanging simulators before startup.

---

test/functional/find-e2e-specs.js

Skipped tests are where WDA functions wrongly. Or at least differently from how Appium does using Instruments.

Add initial tests for find commands

---

lib/driver.js
package.json

Make sure the timeouts get into Safari.

Add safari as a managed driver

---

lib/commands/execute.js
test/functional/alert-e2e-specs.js
test/functional/basic-e2e-specs.js
test/functional/driver-e2e-specs.js
test/functional/element-e2e-specs.js
test/functional/find-e2e-specs.js
test/functional/gesture-e2e-specs.js
test/functional/helpers/navigation.js
test/functional/helpers/session.js

Tests for element size, name, etc.
Also move some of the repeating code out of the tests.

Add tests for element interaction

---

lib/commands/gesture.js

doubleTap support

---

.travis.yml
README.md
gulpfile.js
lib/commands/log.js
lib/driver.js
lib/realDeviceManagement.js
lib/simulatorManagement.js
lib/utils.js
lib/webdriveragent.js
package.json
test/functional/basic-e2e-specs.js
test/functional/desired.js
test/functional/driver-e2e-specs.js
test/functional/element-e2e-specs.js
test/functional/gesture-e2e-specs.js
test/functional/helpers/session.js
test/functional/webdriveragent-e2e-specs.js
test/unit/webdriveragent-specs.js

Basic support for real devices. NO functionality was added beyond allowing a session to be created.

Add provisional support for real devices

---

.travis.yml
test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js
test/functional/driver/driver-e2e-specs.js
test/functional/driver/webdriveragent-e2e-specs.js
test/functional/web/safari-e2e-specs.js
test/functional/web/webview-e2e-specs.js

Split up tests as they are beginning to take too long on Travis.

Arrange tests for Travis

---

lib/commands/context.js
lib/commands/index.js
lib/commands/timeouts.js
lib/driver.js
package.json
test/functional/web/helpers.js
test/functional/web/safari-e2e-specs.js

Whoa! Actual honest-to-goodness reliable web automation!

Set initial url for safari session

---

lib/webdriveragent.js

fixing bug - url port to proxy should be updated

---

lib/webdriveragent.js

ensure webdriveragent logs come out line-by-line (fix #6749)

---

lib/driver.js

Handle the various cases of app/bundleId, and download the app if need be.

Properly configure application

---

lib/driver.js
package.json
test/unit/driver-specs.js

Note that this will depend on https://github.com/appium/appium-ios-driver/pull/174 being merged and published to work.
cc @imurchie

ensure we send back default server caps (fix appium/appium#6771)

---

lib/commands/alert.js
lib/commands/find.js
lib/commands/proxy-helper.js
lib/commands/source.js
lib/commands/web.js
lib/driver.js
package.json
test/functional/helpers/session.js
test/functional/web/safari-alerts-e2e-specs.js
test/functional/web/safari-basic-e2e-specs.js
test/functional/web/safari-window-e2e-specs.js

Alerts in Safari are native, and need to be handled specially.

Add support for alerts in safari

---

lib/webdriveragent.js

fix LOG_STARTTIME_REGEX for dates with single digit number

---

lib/webdriveragent.js

Following this change. Hope it will help at least simulator runs 
https://github.com/facebook/WebDriverAgent/pull/272

reliable WDA build for simulator

---

test/functional/web/safari-basic-e2e-specs.js

Trying to make it work better in Travis.

Separate one bunch of safari tests

---

lib/commands/element.js
lib/commands/general.js
lib/driver.js
test/functional/basic/element-e2e-specs.js

Handle the basics of special characters.

Allow for special characters

---

test/functional/web/safari-basic-e2e-specs.js

The tests are flakey. It sucks.

Split up more safari tests

---

lib/commands/element.js
test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js
test/functional/web/safari-alerts-e2e-specs.js
test/functional/web/safari-cookie-e2e-specs.js
test/functional/web/safari-execute-e2e-specs.js
test/functional/web/safari-window-e2e-specs.js
test/functional/web/webview-e2e-specs.js

WDA requires an array, we were sending a string.

Make sure setvalue works for regular text

---

lib/driver.js
test/functional/driver/driver-e2e-specs.js

Handle initial orientation in caps

---

lib/commands/general.js
test/functional/basic/basic-e2e-specs.js

Proxy window size to WDA

---

lib/webdriveragent.js

Ignore what the device says, even on a sim (we already do for real devices).

Use localhost as WDA host

---

lib/commands/gesture.js

[fixing issue](https://github.com/appium/appium/issues/6836)

adding tap support for tap 

---

lib/commands/source.js
test/functional/basic/basic-e2e-specs.js

Fix source retrieval

---

lib/driver.js

If SafariLuancher is built and install on ios10 real device. This should work. I didnt get time to test though

real device safari support beta

---

README.md
lib/webdriveragent.js

Just a little change so the value of the constant is not encoded within the name.

Make generic name for real device system logger

---

test/functional/basic/element-e2e-specs.js

WDA was updated to allow for this test to run. (The diff is messed up because of some changes that were needed to support this, in terms of starting and stopping sessions. The actual test that was added is at the very bottom.)

Add test for picker wheel interaction

---

lib/desired-caps.js

These are used but not yet validated or handled correctly.

Add realDeviceLogger and wdaLocalPort to cap validation

---

README.md
lib/desired-caps.js
lib/driver.js

Allow a pause after installation to be configured via capabilities. Addresses https://github.com/appium/appium/issues/6889

Add iosInstallPause cap

---

lib/commands/element.js
test/functional/basic/element-e2e-specs.js

Fix text handling

---

lib/webdriveragent.js

Give more visibility into potential errors in wda launch/log creation.
In regard to #191

Make sure to handle rejection during wda startup

---

lib/commands/find.js
lib/commands/general.js

Rather than naively checking for 'Done', find the last button on the keyboard and press that.
What should we do if there is no keyboard?

Better handling of hide keyboard

---

lib/webdriveragent.js
test/functional/basic/element-e2e-specs.js

`iproxy` doesn't do much in the way of logging, but log it anyway.

Add iproxy logging

---

lib/commands/proxy-helper.js
lib/driver.js
package.json

fixing package file to add glob which is needed for /test/functional/desired.js

kill app at end of test

---

lib/driver.js
lib/real-device-management.js
lib/simulator-management.js
lib/webdriveragent.js
test/functional/driver/driver-e2e-specs.js

Pull reset logic from ios driver and refactor so the functionality is the same.

Add reset logic

---

lib/commands/find.js
test/unit/commands/find-specs.js
test/unit/driver-specs.js

add xpath UIA->XCUI rewriting

---

lib/webdriveragent.js

Otherwise we get a lot of errant logging.

Add check for real device around real device log log

---

README.md
bin/run-xcodebuild.sh
lib/webdriveragent.js

We use it for real device builds now, and need to document it.

Add xcpretty to docs

---

lib/webdriveragent.js

There are cases where the message continues to be displayed.

Make sure we don't show waiting message too much

---

lib/commands/context.js

Both functions seem to be called.

Make sure webview check is right

---

lib/driver.js

We try to install bundles, but we shouldn't. Fixes #237

Make sure we don't try to install app that is bundle

---

lib/driver.js

Fixes https://github.com/appium/appium/issues/7053
Also clarifies some logging.

Allow non-safari browserName through

---

lib/driver.js
test/functional/desired.js

Our message was saying they needed the wrong properties.

Fix error message for process args

---

test/functional/basic/find-e2e-specs.js

Actually run the test during ios 10 tests.

Fix find image test

---

test/functional/basic/basic-e2e-specs.js

Add one that fails on iOS 10.x now.

Fix orientation tests

---

lib/webdriveragent.js

Clean a little bit the webdriveragent handling code.

Clean up webdriveragent handling

---

lib/driver.js

which no longer ships by default with xcode
addresses appium/appium#7122
cc @imurchie

use ipad retina as default ipad instead of ipad 2

---

lib/commands/element.js
lib/driver.js
test/functional/basic/element-e2e-specs.js

Deal with delete/backspace and newline/return for `keys` as it is for `setValue`.

Handle special keys in keys method

---

lib/commands/gesture.js
lib/desired-caps.js
test/functional/basic/gesture-e2e-specs.js
test/unit/commands/gesture-specs.js

Better handling of `longPress`, including shifting press-wait-release from `tap` to `longPress`. 
Also add `tapWithShortPressDuration` capability to handle the case where `tap` (and `click`) are too long. This can configure the time for a tap, in the case that it doesn't work. See https://github.com/appium/appium/issues/7051

Fix gesture support a bit

---

lib/commands/element.js
test/functional/basic/element-e2e-specs.js

We have a very quick-and-dirty solution in now. This extends it and makes it a little more robust.

Clean up handling of keyboard on sending input to text field

---

lib/commands/navigation.js
lib/driver.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js

Try to find the navigation bar's back button, and click it.
Fixes https://github.com/appium/appium/issues/7118

Add native back method

---

README.md
lib/commands/find.js
test/functional/basic/find-e2e-specs.js

-Added tests that demonstrate predicate string strategy
-Fixed a small typo in README.md
NOTE: Once the pull request is approved I'll squash these commits into one

Dan predicate string

---

README.md
lib/desired-caps.js
lib/driver.js

This PR is based on https://github.com/appium/appium-ios-simulator/pull/74

Add possibility to set custom scale factor for iOS Simulator in xcuitest driver

---

lib/commands/gesture.js
lib/commands/proxy-helper.js
test/unit/commands/proxy-helper-specs.js

This is not how `BadParameterError` works, and we end up with weird logs.

Do not use BadParameterError when we should not be

---

package.json
test/functional/desired.js
test/functional/web/webview-e2e-specs.js

There is no reason to have the extra app, since UICatalog has an embedded web view.

Remove ios-webviewapp dep and use uicatalog

---

lib/commands/gesture.js
test/functional/basic/gesture-e2e-specs.js
test/unit/commands/gesture-specs.js

Long press and tap with coordinates instead of element.

Allow gestures on coordinates

---

README.md
lib/driver.js
test/functional/basic/basic-e2e-specs.js

Document that we do not support lock (fixes https://github.com/appium/appium/issues/6813), shake (fixes https://github.com/appium/appium/issues/6814), and location (fixes https://github.com/appium/appium/issues/6856).

Document location, lock, shake

---

lib/commands/index.js
lib/commands/session.js
lib/driver.js
test/functional/basic/basic-e2e-specs.js
test/unit/commands/session-specs.js

merge appium caps with WDA caps and repackage for appium clients

---

lib/commands/log.js
lib/driver.js
package.json

This is the next step in https://github.com/appium/appium/issues/7467 and https://github.com/appium/appium/issues/7495

Remove ios-app-util and appium-ios-log dependencies

---

lib/commands/source.js
package.json
test/functional/basic/basic-e2e-specs.js
test/unit/commands/source-specs.js

XML output is the same as it was.
Addresses https://github.com/appium/appium/issues/7382

Move to using WDA xml source method

---

lib/commands/element.js

This fix addresses https://github.com/appium/appium/issues/7585 and also speeds up typing in general, since Appium does not execute unnecessary requests to WDA anymore

Optimize setValue algorithm

---

.travis.yml
lib/commands/element.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js

Some tests are skipped on Travis because they failed at one time. Reduce the number of these.

Update setValue to correctly handle special characters, and unquarantine tests

---

.travis.yml
lib/commands/gesture.js
lib/real-device-management.js
package.json
test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/file-movement-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js
test/functional/driver/driver-e2e-specs.js
test/functional/driver/webdriveragent-e2e-specs.js
test/functional/helpers/session.js
test/functional/web/safari-alerts-e2e-specs.js
test/functional/web/safari-basic-e2e-specs.js
test/functional/web/safari-cookie-e2e-specs.js
test/functional/web/safari-execute-e2e-specs.js
test/functional/web/safari-ssl-e2e-specs.js
test/functional/web/safari-window-e2e-specs.js

REsolves https://github.com/appium/appium/issues/7627

Map /touch/click to click

---

README.md
lib/commands/gesture.js
lib/desired-caps.js
lib/webdriveragent.js
package.json

Add a capability `wdaConnectionTimeout` to modify the amount of time to wait for a WDA-proxied command to return.
And a few miscellaneous things.

Add wdaConnectionTimeout cap

---

lib/webdriveragent.js

Wrong port was being used because of the way we were changing the url object.

Make sure we handle local port on real device tests

---

lib/driver.js
lib/utils.js

Undo `chmod` of derived data, after the session.

Clean up handling of derived data folder

---

lib/commands/gesture.js
test/functional/web/safari-execute-e2e-specs.js

Otherwise the element is not found and we cannot scroll.
Fixes https://github.com/appium/appium/issues/7760

Make sure scroll/swipe works in web context

---

lib/driver.js
lib/real-device-management.js
lib/simulator-management.js
package.json

Addresses https://github.com/appium/appium/issues/7754

Add reset to startup flow

---

lib/driver.js

Fix minor typo

---

README.md
lib/desired-caps.js
lib/driver.js

As per https://github.com/appium/appium/issues/7918
This PR depends on https://github.com/appium/appium-ios-simulator/pull/100

Make Connect Hardware Keyboard option configurable for Simulator in capabilities

---

lib/driver.js
lib/simulator-management.js
lib/utils.js
lib/webdriveragent.js
package.json
test/functional/basic/gesture-e2e-specs.js

Make tools version visible. Also restrict some functionality that doesn't work in xcode 7.3

Log xcode tools version

---

lib/commands/general.js

It takes a long time to report back.

If we know we are on an iPhone, don't try broken WDA hide keyboard

---

test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js

Try to mitigate some of the flakiness in the build recently.

Firm up some of the tests

---

lib/commands/element.js
lib/desired-caps.js
test/functional/basic/element-e2e-specs.js

Allow users to try out using XCUIElement typeText method if they want to.

Put typing change behind cap

---

README.md
lib/commands/element.js
lib/desired-caps.js
lib/driver.js
test/functional/basic/element-e2e-specs.js
test/functional/desired.js

On some systems the typing happens to fast and the gestures get muddled.

Add capability to set frequency of keystrokes while typing

---

README.md
lib/desired-caps.js
lib/driver.js
lib/webdriveragent-utils.js
lib/webdriveragent.js
test/unit/webdriveragent-utils-specs.js

Some systems need to use SSL. Allow that. Also add some unit tests because testing!

Add ability to use ssl for Carthage

---

lib/commands/gesture.js
test/unit/commands/gesture-specs.js

See https://github.com/appium/appium/issues/7055#issuecomment-290662166 for more details.

Fix for getting action coordinates in case they are presented as string values

---

lib/commands/screenshots.js
lib/driver.js

Fixes https://github.com/appium/appium/issues/4956
Also use the correct method for checking whether the device is real or not

Make sure reset happens even if noReset is set to true

---

.travis.yml
test/functional/long/typing-stress-e2e-specs.js

Make sure the system can handle repeated typing in Travis.

Add test to check on long typing

---

lib/driver.js
lib/utils.js
lib/webdriveragent.js
test/functional/desired.js
test/unit/utils-specs.js

Oops! We've been directing people to use the `clearSystemFiles` cap but never actually implemented it!

Actually add clearSystemFiles capability

---

README.md

Add documentation for startIWDP capability

---

lib/commands/execute.js
lib/commands/gesture.js
test/unit/commands/gesture-specs.js

See https://github.com/facebook/WebDriverAgent/pull/523 for more details.
Please merge this PR only after the most recent WDA from master containing the PR above is available in xcuitest driver.

Implement dynamic selection of picker wheel value

---

README.md

Added ```allowTouchIdEnroll``` caps into docs. @imurchie @mykola-mokhnach FYI

Doc Updates - Capabilities

---

lib/commands/gesture.js
test/unit/commands/gesture-specs.js

Please merge this commit after WDA master with https://github.com/facebook/WebDriverAgent/pull/549 is available

Add the optional ‘offset’ parameter to selectPickerWheelValue call

---

.travis.yml
test/unit/driver-specs.js

Stop IWDP unit test from starting IWDP

---

lib/commands/alert.js
lib/commands/execute.js
test/unit/commands/alert-specs.js

Addresses https://github.com/appium/appium/issues/8361

Add support for tap alert button by name

---

lib/commands/gesture.js

Addresses https://github.com/appium/appium/issues/8405

Add one more matching actions chain for long press for better compatibility with Python client

---

lib/commands/gesture.js

Addresses https://github.com/appium/appium/issues/7559

Add support of drag chain starting with longpress action

---

lib/commands/execute.js
test/unit/commands/alert-specs.js

Addresses https://github.com/appium/ruby_lib/issues/578
Special thanks to @KazuCocoa for careful testing

Fix value return from ‘mobile:’ command

---

lib/driver.js

Fix floating point comparison

---

lib/commands/element.js

Addresses https://github.com/appium/appium/issues/8695

Force attribute value conversion to string, which is required by the W3C spec

---

lib/simulator-management.js
test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js
test/functional/basic/touch-id-e2e-specs.js
test/functional/desired.js
test/functional/driver/driver-e2e-specs.js

Still the same bugs as before, just a little more coverage from Appium's side. 
See https://github.com/appium/appium/issues/8675

Second pass at getting iOS 11 going

---

test/functional/web/safari-window-e2e-specs.js

The window and frame test is particularly flakey on Travis.

Fix the build

---

lib/simulator-management.js

It's a part of the preparation for parallel simulator sessions support with Xcode9. Also, the PR depends on https://github.com/appium/appium-ios-simulator/pull/110

Avoid explicit interaction with processes, since it may create issues for parallel sessions

---

lib/driver.js
test/functional/basic/gesture-e2e-specs.js

One last place where the url needs to be adjusted.

Make sure we save the href of WDA when we find it

---

README.md
lib/desired-caps.js
lib/driver.js
lib/simulator-management.js
package.json
test/functional/driver/driver-e2e-specs.js
test/unit/driver-specs.js

This PR depends on https://github.com/appium/appium-ios-simulator/pull/113 and should be merged after it

Add isHeadless capability and refactor the driver to support the most recent refactoring changes in appium-ios-simulator package

---

lib/driver.js
lib/simulator-management.js

Did some refactoring optimizations for Simulator-related stuff in xcuitest driver

Clean up full reset method for Simulator

---

lib/commands/element.js

Addresses https://github.com/appium/appium/issues/8899

Make sure a value is of type string before typing it

---

lib/driver.js
lib/wda/webdriveragent.js
lib/wda/xcodebuild.js
test/functional/basic/basic-e2e-specs.js

It's a bit tricky, since most of these conditions are based on static code analysis. If you see more places where this verification should be added then please let me know about it.

Avoid simultaneous access to shared resources by setting isFirstSession property

---

test/functional/basic/touch-id-e2e-specs.js

Work on tests

---

lib/ios-deploy.js

The install command is sometimes flakey. In the best case, this is no different than it was. If the command fails, we get some retries.

Retry real device install

---

lib/driver.js
lib/simulator-management.js
lib/utils.js
lib/wda/webdriveragent.js
lib/wda/xcodebuild.js

Now the code is starting to please my eyes 😻

Refactor XCTest processes cleanup

---

.travis.yml
lib/commands/element.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/touch-id-e2e-specs.js
test/unit/commands/element-specs.js

Demonstrates resolution of https://github.com/appium/appium/issues/9036

Add unit tests for setValue/setValueImmediate

---

test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js
test/functional/desired.js

Other than logging, Xcode 9b5 resolved all of the remaining issues that are identified in our test code.

Update tests for Xcode 9b5

---

lib/commands/general.js

Addresses https://github.com/appium/appium/issues/9066

Fix url opening on real devices

---

lib/driver.js

Addresses https://github.com/appium/appium/issues/4000

Allow to detect simulators if udid value is set to 'auto'

---

lib/commands/actions.js
lib/commands/index.js
package.json

Addresses https://github.com/appium/appium/issues/8355
This PR depends on https://github.com/appium/node-simctl/pull/45

Add a possibility to push media files to Simulator

---

lib/commands/general.js

Addresses https://github.com/appium/appium/issues/9188

Fix setting url inside web context on real devices

---

README.md

Update the list of known/missing things in README.

Update known issues

---

lib/driver.js

Addresses https://github.com/appium/python-client/issues/182

Add /attribute/ endpoint to NO_PROXY list

---

README.md
lib/commands/element.js
lib/desired-caps.js
package-lock.json
test/unit/commands/element-specs.js

before we were returning location in view, because that was what the atom did. but we should be returning location relative to 0, 0 of the document. note that this is a breaking change so we might want to think about when and how to land it. this change would also need to be done in ios-driver if we want them to stay in sync, since the code is duplicated from there.

change web element location finding semantics

---

lib/wda/xcodebuild.js

See https://github.com/appium/appium/issues/9256 for more details

Do not try to read xcodebuild log file if it is too big

---

lib/driver.js
package.json

Please merge it after https://github.com/appium/appium-ios-simulator/pull/130 is published

Apply a workaround for setting the default device orientation

---

.travis.yml
lib/commands/web.js
test/functional/web/helpers.js
test/functional/web/safari-basic-e2e-specs.js
test/functional/web/safari-nativewebtap-e2e-specs.js

Handle tabs and the Smart App Banner. Works for iPhone and iPad.

Update offset determination for ipad

---

lib/utils.js
test/unit/utils-specs.js

Addresses https://github.com/appium/appium/issues/9410

Reset temporary big log files created by XCTest

---

lib/wda/webdriveragent.js

This should improve the situation described in https://github.com/appium/appium/issues/9461

Do not throw an exception if WDA uninstall fails

---

lib/commands/source.js
test/functional/web/safari-window-e2e-specs.js

Rather than getting the source of the frameset, should get the source of the frame itself when inside a frame.

Fix source retrieval inside frame/iframe

---

lib/driver.js
lib/utils.js
test/unit/utils-specs.js

As per https://github.com/appium/appium/issues/9534

Fix device name translation for Xcode 9.1+

---

README.md
lib/commands/general.js
lib/commands/gesture.js
package.json
test/functional/basic/basic-e2e-specs.js

Based on https://github.com/appium/appium-ios-simulator/pull/136

Add support for shake and setGeolocation on Simulator

---

lib/driver.js
package.json
test/unit/driver-specs.js

Addresses https://github.com/appium/appium/issues/9410

Perform installd caches cleanup before installing the app on Simulator

---

lib/utils.js
test/unit/utils-specs.js

9.0.1 also fixed the device names.

Restrict deviceName map for xcode 9.0

---

lib/commands/log.js
lib/device-log/ios-log.js
test/unit/log-specs.js

Wire up subclass of ios logger

---

lib/commands/alert.js
test/functional/basic/alert-e2e-specs.js

Still no support from WDA. So try to find what should be there, and type into it.
See https://github.com/appium/appium/issues/9590

Fix prompt support in native context

---

lib/driver.js

* Apparently there's a way for wda to become null between lines 556 and 565; this is a fix for that

Check that wda still exists

---

lib/driver.js
test/unit/driver-specs.js

Partially addresses https://github.com/appium/appium/issues/9641 (we anyway cannot do more there)

Avoid forceful setting of display orientation if it is not set explicitly

---

lib/commands/log.js
lib/device-log/ios-crash-log.js
lib/device-log/ios-log.js
package.json
test/unit/log-specs.js

Please merge it after https://github.com/appium/appium-ios-driver/pull/256 is tagged with a new ios-driver version label

Update crash logs gathering algorithm

---

lib/commands/actions.js

Added a possibility to push/pull files to/from real devices via SSHD file system (osxfuse/ifuse combination). Also, it is now possible to access files inside application containers.

Add a possibility to push and pull files from both simulator and real devices

---

lib/commands/actions.js
lib/commands/execute.js

This PR is based on https://github.com/appium/WebDriverAgent/pull/11

Add the corresponding mobile: endpoints to support multiple apps

---

lib/commands/screenshots.js

This should start working as soon as new WDA snapshot is merged.

Add element screenshot endpoint handler

---

.circleci/config.yml
lib/device-log/ios-log.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/touch-id-e2e-specs.js
test/functional/desired.js
test/functional/driver/driver-e2e-specs.js
test/functional/helpers/session.js
test/functional/long/typing-stress-e2e-specs.js
test/functional/web/safari-alerts-e2e-specs.js

Run the test suite on Circle CI, which is much faster than Travis.

Add circle ci config and make tests pass

---

lib/commands/actions.js
lib/commands/execute.js
lib/commands/general.js
lib/ios-deploy.js

Now there will be a complete set of methods to test, for example, application upgrade.

Add missing mobile: methods for multiple applications management

---

.npmignore

Ignore docs from npm package

---

lib/commands/actions.js

Based on https://github.com/appium/WebDriverAgent/pull/18

Add env and args to /launchApp endpoint

---

lib/commands/actions.js

We are passing the wrong thing to `isAppInstalled`, and getting https://github.com/appium/appium/issues/9940

Fix isAppInstalled and removeApp functions

---

README.md
lib/desired-caps.js
lib/driver.js
lib/simulator-management.js

Addresses https://github.com/appium/appium/issues/9954

Add a possibility to shutdown other running Simulators on session startup

---

lib/commands/general.js

`await this.getAttribute('visible', keyboard)` returns a string representation, either `'true'` or `'false'`, so it is _always_ truthy.
Also make sure the button we are pressing can be pressed, though this is probably unnecessary if the keyboard visibility check is working correctly.

Properly check for keyboard

---

lib/simulator-management.js

Addresses https://github.com/appium/appium/issues/9954#issuecomment-359832627

Fix value transformation for shutdownOtherSimulators call

---

lib/wda/webdriveragent.js

I see that fkill always fails to terminate the process. Not sure why it happens, so I'd rather use a normal `kill` call.
Addresses https://github.com/appium/appium/issues/10081

Use system call instead of fkill

---

lib/commands/app-management.js

This completes the set of native application management endpoints

Add activate app endpoint handler

---

test/functional/basic/gesture-e2e-specs.js

These tests are not technically broken, but this should fix the errors seen in #622

Fix gesture tests

---

test/functional/basic/file-movement-e2e-specs.js

Addresses https://github.com/appium/appium-xcuitest-driver/pull/620#issuecomment-363913642

Fix file movement integration test

---

lib/commands/gesture.js
test/functional/basic/gesture-e2e-specs.js
test/unit/commands/gesture-specs.js

This is a copy of https://github.com/appium/appium-xcuitest-driver/pull/546

Update touch actions implementation to use native endpoints

---

lib/commands/gesture.js
lib/driver.js
test/functional/basic/gesture-e2e-specs.js

The endpoint is already present in WDA

Add handler for W3C actions

---

test/functional/web/safari-ssl-e2e-specs.js

Travis build has been broken for more than a week.

Fix the build in Travis

---

lib/commands/log.js
lib/device-log/ios-log.js
lib/driver.js
lib/wda/webdriveragent.js
package.json
test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js
test/functional/helpers/session.js

See https://github.com/appium/appium/issues/10188 for details.

Remove check for Xcode when webDriverAgentUrl is used on real device

---

lib/commands/general.js

Depends on https://github.com/appium/WebDriverAgent/pull/52

Handle requests to /element/active API

---

lib/utils.js
test/functional/basic/basic-e2e-specs.js

Addresses https://github.com/appium/appium/issues/10300

Do not throw an exception if xcodeVersion is unset

---

lib/simulator-management.js

See https://github.com/appium/appium-xcuitest-driver/pull/634 for more details
@kool79 FYI

Properly cleanup cached xcodebuild processes before shutting down the device

---

lib/commands/alert.js

Depends on https://github.com/appium/WebDriverAgent/pull/53

Add native handler for `alert/text` endpoint

---

lib/commands/clipboard.js
lib/commands/index.js

Bases on https://github.com/appium/WebDriverAgent/pull/64 and https://github.com/appium/appium-base-driver/pull/199

Add clipboard handlers

---

lib/driver.js

exposes https://github.com/appium/WebDriverAgent/pull/69 to appium-land

support getting element attributes during find element call

---

lib/commands/execute.js
lib/commands/log.js
lib/driver.js
lib/utils.js
package.json

Depends on https://github.com/appium/appium-ios-driver/pull/272

Add system logs broadcast feature

---

lib/driver.js

Just an additional protection from stupidity

Add webDriverAgentUrl capability verification

---

lib/commands/certificate.js
lib/commands/execute.js
lib/commands/index.js
package.json

This still has to be tested properly, but I just wanted to demonstrate the idea first.

Add mobile: endpoint for installing custom certificate

---

lib/commands/context.js
lib/commands/log.js
lib/desired-caps.js
lib/device-log/safari-console-log.js
package.json
test/functional/basic/basic-e2e-specs.js
test/functional/desired.js
test/functional/helpers/session.js
test/functional/web/safari-basic-e2e-specs.js

Add capability `showSafariConsoleLog`.

Add safari console logging

---

lib/commands/log.js

currently it fails because of undefined listener error

Fix listener variable name

---

lib/commands/battery.js
lib/commands/execute.js
lib/commands/index.js

Based on https://github.com/appium/WebDriverAgent/pull/83

Add an extension to retrieve battery info from a real device

---

lib/device-log/safari-console-log.js

I merged the other PR before addressing a couple of comments.

Fix Safari console log retrieval

---

lib/commands/certificate.js
package.json

This is needed to fix electron building

Replace the native x509 node module with openssl call

---

lib/commands/app-management.js

Addresses https://github.com/appium/java-client/issues/892

Return proper result on application removal

---

lib/commands/location.js
test/unit/commands/location-specs.js

Addresses https://github.com/appium/appium/issues/10699

Fix formatting of negative coordinate values for location setting

---

lib/commands/location.js
test/unit/commands/location-specs.js

It turns out that isEmpty check returns `false` for raw numbers. I've changed it to `hasValue` and updated the unit tests.
Addresses https://github.com/appium/appium/issues/10706

Fix verification for numeric location values

---

lib/commands/file-movement.js

Now it should be also possible to pull folders along with files

Add a possibility to pull folders from real devices

---

lib/commands/gesture.js
test/functional/basic/gesture-e2e-specs.js

The old test was passing but not doing what it said it was testing.

Fix swipe test

---

lib/commands/performance.js
lib/server.js
test/functional/basic/performance-e2e-specs.js
test/functional/basic/touch-id-e2e-specs.js
test/functional/helpers/session.js

The performance recording tests do not work as is. So expose the actual driver to set up correctly.

Fix performance tests

---

lib/commands/context.js
lib/commands/execute.js
test/functional/web/safari-basic-e2e-specs.js

Addresses https://github.com/appium/appium/issues/10757

Add mobile:getContexts command to get full context list

---

lib/commands/proxy-helper.js
package.json

See https://github.com/appium/appium-base-driver/pull/218 and https://github.com/appium/appium-base-driver/pull/220 for more details

Remove the obsolete verification from proxyCommand helper

---

lib/driver.js
test/unit/commands/session-specs.js

Resolves performance issue described in https://github.com/appium/appium/issues/10790#issuecomment-398792966

Cache WDA and device caps per driver instance

---

lib/wda/xcodebuild.js

The previous retrieval method is not very reliable and also slow.

Improve derived data retrieval

---

lib/commands/certificate.js
test/unit/commands/pasteboard-specs.js

Addresses https://github.com/appium/appium/issues/10940

Fix certificate name retrieval

---

lib/commands/certificate.js

I've tested it with the recent iOS beta and managed to fix some problems.

Tune certificate installation flow

---

.travis.yml
lib/commands/general.js
lib/commands/web.js
lib/driver.js
lib/wda/xcodebuild.js
package.json
test/functional/helpers/ci-metrics.js
test/functional/web/helpers.js
test/functional/web/safari-nativewebtap-e2e-specs.js

Some fixes to how we handle `nativeWebTap`.

Update nativeWebTap and test on iPhone X

---

lib/commands/context.js

All further info regarding this pull request can be found at https://github.com/appium/appium/pull/10960

Add option to use a remote debugger proxy

---

lib/commands/web.js
lib/driver.js

this should partially address https://github.com/appium/appium/issues/8582

Add alerts handling in web context

---

README.md

https://github.com/appium/appium/issues/11132 is a related issue.
A user avoided the issue with `waitForQuiescence` but we have no capability section about it.

add waitForQuiescence in readme

---

lib/commands/recordscreen.js

The classic problem with seconds to milliseconds conversion

Fix time metrics conversion

---

README.md
lib/commands/web.js
lib/driver.js
test/unit/driver-specs.js

The PR is based on https://github.com/appium/WebDriverAgent/pull/108

Add support for auto accepting/dismissing alerts

---

.travis.yml
test/functional/apps.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/performance-e2e-specs.js
test/functional/web/safari-ssl-e2e-specs.js

* Use mocha-parallel-tests for cloud tests so that we can run tests on multiple parallel Simulators
* Fixed some test failures

Fix some broken tests; make tests parallel

---

lib/commands/file-movement.js
package.json

The ugly bug has been luckily caught fast.

Fix container type parsing

---

.travis.yml

This will make the tests run quicker because it allows concurrent sessions on SauceLabs ondemand

Add parallel tests

---

lib/commands/web.js

https://github.com/appium/appium/issues/11367

Tune the timeout message

---

.travis.yml
lib/commands/screenshots.js
lib/desired-caps.js
lib/driver.js
package.json
test/functional/basic/screenshot-e2e-specs.js

the iOS equivalent of https://github.com/appium/appium-uiautomator2-driver/pull/193.
🤞  for travis + mjpeg-consumer

add mjpegScreenshotUrl cap support for ios

---

lib/commands/element.js

Addresses https://github.com/appium/appium/issues/11427

implement /rect for web context

---

.travis.yml
lib/driver.js
lib/simulator-management.js

hopefully addresses https://github.com/appium/appium/issues/11350

Use smarter cache cleanup algorithm

---

lib/driver.js
lib/utils.js
test/unit/utils-specs.js

Addresses https://github.com/appium/appium/issues/11508

Do not try to detect xcode version for real devices

---

lib/commands/gesture.js

I hope someone still reads these messages

Provide better error messages if performTouch fails in web context

---

lib/commands/execute.js
lib/commands/general.js

This might be sometimes useful for automation purposes

Implement pressButton mobile command

---

lib/commands/location.js

Fixes https://github.com/appium/appium-xcuitest-driver/pull/810 originally proposed by @kkaskavelis

Fix idevicelocation arguments formatting when both of them are negative

---

lib/commands/execute.js
lib/commands/index.js
lib/commands/permissions.js

The PR is based on https://github.com/appium/appium-ios-simulator/pull/188

Add mobile commands for permissions setting/getting

---

.gitignore
.travis.yml
gulpfile.js
package.json
test/functional/driver/driver-e2e-specs.js

Move coverage command into _after_success_ block and adjust file locations and verbosity.

Add coverage to Travis build

---

lib/commands/element.js
lib/commands/find.js
lib/commands/general.js
lib/commands/gesture.js
lib/commands/proxy-helper.js
lib/driver.js
lib/ios-deploy.js
lib/real-device-management.js
lib/utils.js
lib/wda/iproxy.js
lib/wda/utils.js
lib/wda/xcodebuild.js

Replace `indexOf` with `includes` and `startsWith` when possible.

Down with indexOf

---

ci/upload-appium.js
package.json

Instead of using BinTray, use a dedicated Github repo. Counterpart to https://github.com/appium/appium/pull/11893

Move to getting bundle from github for CI

---

lib/device-log/safari-network-log.js

Addresses https://github.com/appium/appium/issues/11907

Fix padEnd function usage

---

.travis.yml
ci/periodic-output.sh
lib/commands/execute.js
test/env/env.js
test/functional/basic/alert-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/desired.js
test/functional/driver/driver-e2e-specs.js
test/functional/helpers/session.js
test/functional/long/typing-stress-e2e-specs.js
test/functional/web/helpers.js
test/functional/web/safari-basic-e2e-specs.js
test/functional/web/safari-nativewebtap-e2e-specs.js
test/functional/web/safari-ssl-e2e-specs.js
test/unit/commands/element-specs.js
test/unit/commands/find-specs.js

Get all the tests to be running in the Travis cron job. Tests still are flakey, but at least they are running. Once this is in, and a few runs have happened, I can revisit the evidence and work on the test consistency.

Work on web and long cron tests

---

lib/commands/general.js
lib/driver.js

Addresses https://github.com/appium/appium/issues/12042

Avoid memoizing window size getter

---

lib/wda/xcodebuild.js

Add an Xcode option to NOT treat warnings as errors while building WDA

---

lib/commands/recordscreen.js

The changes for https://github.com/appium/appium/issues/12067

Added ability to specify '-r' option for video recording

---

README.md

https://github.com/appium/appium-xcuitest-driver/blob/dbe1a5009464a4cf983b0175c9f9f6e63f6a4685/lib/wda/xcodebuild.js#L166

add missing useSimpleBuildTest [skip ci]

---

lib/driver.js

Nothing much to describe here. Just better texting to help users solve startup problems on their own

Improve retry logging

---

lib/desired-caps.js
lib/utils.js
lib/wda/utils.js
lib/wda/webdriveragent.js
lib/wda/xcodebuild.js
test/unit/wda/utils-specs.js

- Update WDA
- Add `tvOS` platform
- An ability to build with `tvOS` scheme
- `xctestrunFile` cap for `tvOS`
On https://github.com/appium/appium/pull/12401 , I've attached an animation-gif of action for tvOS via Ruby client.

tvos support

---

lib/driver.js

Sometimes this information might be useful to debug startup issues

Log the stracktrace of the driver startup internal error

---

lib/commands/recordscreen.js

Addresses https://github.com/appium/appium/issues/12463

Fix initial settings of video recording process

---

lib/driver.js

Addresses https://github.com/appium/appium/issues/12584

Do not execute WDA cleanup if webDriverAgentUrl is set

---

lib/driver.js

Fail fast if an incorrect version number is provided

Add platformVersion validation to validateDesiredCaps

---

lib/commands/certificate.js

Addresses https://github.com/appium/appium/issues/12505

Update certificate installation on iOS 12.2+

---

ci-jobs/nightly-build.yml
ci-jobs/pr-validation-build.yml
ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/desired.js
test/functional/tv/tvos-e2e-specs.js

add tests for tvOS #913
---
This is only for making sure the tvOS build works and succeeds to launch.

add simple tvOS e2e test on Azure

---

lib/utils.js
lib/wda/webdriveragent.js

Hopefully addresses https://github.com/appium/appium/issues/12649

Cleanup obsolete iproxy processes if devices were interchanged

---

lib/commands/screenshots.js
lib/device-log/ios-log.js
lib/wda/utils.js
lib/wda/xcodebuild.js

We do not support Xcodes below 9 so these do not need to be here anymore.

Get rid of accommodations for older xcodes

---

README.md
lib/desired-caps.js

Moved `safariGarbageCollect` cap from `appium-ios-driver` where it causes problems.
See https://github.com/appium/appium-ios-driver/pull/383

Add safariGarbageCollect cap

---

lib/driver.js
lib/real-device-management.js
lib/utils.js
package.json

* Start using `appium-ios-device` in the project
* Remove the dependencies to `ideviceinfo` and `idevice_id`

Start using getOSVersion and getConnectedDevices from appium-ios-device

---

README.md
lib/commands/performance.js
lib/driver.js
package.json

https://github.com/appium/appium-base-driver/pull/328 should be published before this one.

use isFeatureEnabled for security features check

---

lib/commands/recordscreen.js

This might be useful for advanced source stream transformations, like rotation. See https://discuss.appium.io/t/video-is-not-capturing-in-landscape-mode-while-running-appium-script-in-ipad/26738/8

 Introduce videoFilters screen recording parameter

---

package.json
test/functional/basic/file-movement-e2e-specs.js

Same as for https://github.com/appium/appium-android-driver/pull/560

Stop using the vulnerable unzip dev dependency

---

lib/ios-deploy.js

Reverts appium/appium-xcuitest-driver#1034. It turns out that the problems was related to nodejs

Revert "fix: push files one by one instead of parralel"

---

lib/commands/context.js

Fixes https://github.com/appium/appium/issues/13063

fix: remove broken call to _getLatestWebviewContextForTitle

---

lib/commands/performance.js

Lets do it like Apple recommends in https://help.apple.com/instruments/mac/current/#/devb14ffaa5
Hopefully addresses https://github.com/appium/appium/issues/13048

Set the current working dir for instruments

---

ci-jobs/nightly-build.yml
ci-jobs/pr-validation-build.yml
ci-jobs/templates/ios-e2e-template.yml
ci-jobs/templates/sauce-e2e-template.yml
ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/long/typing-stress-e2e-specs.js
test/functional/web/safari-ssl-e2e-specs.js

no need to review. just running the tests on Azure.

fix: get Azure tests running iOS 13.0

---

lib/commands/execute.js
lib/commands/gesture.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/213

feat: Add mobile: wrapper for rotateElement API

---

.travis.yml
test/functional/basic/basic-e2e-specs.js
test/functional/basic/element-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/gesture-e2e-specs.js
test/functional/long/typing-stress-e2e-specs.js

When scrolling to visible didn't work we switched to direction. Go back.

chore: go back to scroll toVisible checks

---

.travis.yml
ci-jobs/nightly-build.yml
lib/wda/utils.js
lib/wda/xcodebuild.js

Inspired by https://github.com/appium/WebDriverAgent/pulls

chore: remove xcode 9 adjustments

---

README.md
lib/desired-caps.js
lib/driver.js
lib/ios-deploy.js
lib/real-device-management.js
lib/simulator-management.js
test/unit/driver-specs.js

Addresses https://github.com/appium/appium/issues/13577

feat: Add a capability to customize application push timeout for real devices

---

lib/commands/source.js
package.json

Added support of `excludedAttributes` based on https://github.com/appium/WebDriverAgent/pull/247

feat: Update the implementation of 'mobile: source' endpoint

---

lib/commands/file-movement.js

The file/folder method returns a timeout error message.
So, let me return the original message to get more info about the error.
related to: https://github.com/appium/appium/issues/13597

feat: add original error in the error message

---

ci-jobs/templates/ios-e2e-template.yml
ci-jobs/templates/sauce-e2e-template.yml
ci-jobs/templates/xcuitest-e2e-template.yml
package.json

As my comment on https://github.com/appium/appium/issues/13626
Here it is, @dpgraham :)
See the result at https://dev.azure.com/hlvtrinh/Community%20Contribution/_build/results?buildId=817

Fix build to be able to publish test results to Azure DevOps pipeline

---

lib/driver.js
package.json

Based on https://github.com/appium/appium-base-driver/pull/374

fix: Avoid applications cache corruption

---

lib/ios-deploy.js
package.json

Related to https://github.com/appium/appium/issues/13757#issuecomment-570640266

fix: Unpipe the file reader stream in case of failure

---

lib/commands/app-management.js
lib/device-log/ios-simulator-log.js

Use the `appPushTimeout` in `installApp`.

fix: make sure appPushTimeout is used for installApp

---

docs/real-device-config.md

Related to https://github.com/appium/appium/issues/13836

docs: Update the tutorial on WDA module root folder lookup

---

lib/commands/element.js
test/unit/commands/element-specs.js

Fixes https://travis-ci.org/appium/appium-xcuitest-driver/jobs/637502360

chore: Update unit tests for setValue API

---

lib/commands/context.js
lib/device-log/safari-console-log.js
lib/driver.js
package.json
test/functional/basic/gesture-e2e-specs.js

chore: update to appium-remote-debugger 8.0.0

---

lib/device-connections-factory.js

Another fix of https://github.com/appium/appium-xcuitest-driver/pull/1164

fix connectPort in createServer

---

lib/commands/general.js

https://discuss.appium.io/t/appium-1-17-getdevicetime-returns-strange-value/30162/18

fix: Tune the usage of timeZone value retrieved from lockdown

---

package.json
test/functional/tv/tvos-e2e-specs.js

Let me add a basic test for tvOS

test: add autoLaunch false for tvOS

---

lib/commands/performance.js
lib/commands/recordscreen.js
lib/utils.js
package.json

Same as https://github.com/appium/appium-android-driver/pull/637

chore: Update file upload procedure

---

ci-jobs/ci-build.yml
ci-jobs/templates/node-build-template.yml
ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/basic/gesture-e2e-specs.js

The double tap test is super flakey for iOS < 13 so I just skipped it 🤷‍♂️

chore: fix nightly tests on Azure

---

lib/driver.js
package.json

https://gist.github.com/kolyakrasnik/b7428724f230aac3d4648a91f9262558#file-appium_logs-L219

chore: Precache derived data path from xCode

---

lib/driver.js

Related to https://github.com/appium/appium/issues/14427

chore: Do not pass the remote port number to the factory if it is not used

---

ci-jobs/templates/ios-e2e-template.yml
lib/device-log/ios-crash-log.js

https://github.com/appium/appium/issues/14553

chore: Use non-strict lookup while scanning for logs

---

lib/commands/index.js
test/functional/desired.js

https://discuss.appium.io/t/enabling-darkmode-on-ios-android/31480/5

fix: Add appearance extensions to the index

---

docs/real-device-config.md

Updating Basic (manual) configuration working weblink

docs: updating working weblink

---

package.json

My previous commit included wrong change...

fix: wrong merge

---

ci-jobs/pr-validation-build.yml
ci-jobs/templates/xcuitest-e2e-template.yml
lib/commands/execute.js
lib/commands/permissions.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/385

feat: Add mobile: function to reset permissions

---

lib/commands/performance.js
package.json

Addresses https://github.com/appium/appium/issues/14804

fix: Archive the whole folder where the .trace file is located

---

lib/commands/general.js
package.json
test/functional/basic/element-e2e-specs.js

Based on https://github.com/appium/WebDriverAgent/pull/453

refactor: Move keyboard dismissal logic to WDA

---

lib/commands/web.js

I'll test this more later, but this should help https://github.com/appium/appium/issues/14988

fix: add setImplicitWait zero to calculate the coordinate

---

package.json

chore: Bump WDA

---

README.md

docs: remove non-xcuitest settings item

---

README.md
lib/commands/execute.js
lib/commands/index.js
lib/commands/iohid.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/494

feat: Add a possibility to trigger IO HID events

---

ci-jobs/templates/ios-e2e-template.yml
ci-jobs/templates/xcuitest-e2e-template.yml
lib/app-utils.js
lib/commands/certificate.js
lib/commands/element.js
lib/commands/execute.js
lib/commands/file-movement.js
lib/commands/general.js
lib/commands/gesture.js
lib/commands/log.js
lib/commands/timeouts.js
lib/desired-caps.js
lib/device-log/ios-crash-log.js
lib/driver.js
lib/simulator-management.js
lib/utils.js
test/unit/driver-specs.js
test/unit/utils-specs.js

For now I am moving everything to xcuitest driver except of context/web related stuff. 
Related to https://github.com/appium/appium/issues/14513

refactor: Start working on decoupling from appium-ios-driver

---

README.md
lib/commands/execute.js
lib/commands/index.js
lib/commands/localization.js
package.json

Based on https://github.com/appium/appium-ios-simulator/pull/307

feat: Add 'configureLocalization' Simulator extension

---

README.md
lib/desired-caps.js
lib/driver.js
package.json
test/unit/language-specs.js
test/unit/processargs-specs.js

feat: Add forceAppLaunch capability

---

README.md
lib/desired-caps.js
lib/driver.js
package.json
test/unit/language-specs.js
test/unit/processargs-specs.js

Based on https://github.com/appium/WebDriverAgent/pull/516

feat: Add useNativeCachingStrategy capability

---

lib/driver.js
test/unit/driver-specs.js

Addresses https://github.com/appium/appium/issues/15596

fix: Make it possible to provide URLs with otherApps capability

---

lib/commands/gesture.js
test/unit/commands/gesture-specs.js

addresses https://github.com/appium/appium/issues/15572

feat: add release actions as a no-op command

---

README.md
lib/arg-constraints.js
lib/driver.js

Co-authored-by: Ayan Khan <ayan@headspin.io>

feat: enable cli args for appium 2.x

---

README.md
lib/cert-utils.js
lib/commands/certificate.js
lib/driver.js

Related to https://github.com/appium/appium/issues/15848

fix: Align customSSLCert capability logic

---

lib/commands/source.js
package.json

The previous NPM repository has recently been [abandoned](https://github.com/xmldom/xmldom/issues/271), so we need to change the package name in order to get the recent updates.

chore: Bump xmldom

---

lib/commands/execute.js
lib/commands/web.js

Addresses https://github.com/appium/appium/issues/16039

fix: Cache elements returned from execute_script call

---

lib/commands/source.js
package.json
test/unit/commands/source-specs.js

Based on https://github.com/appium/WebDriverAgent/pull/544

chore: Add AppiumAUT tag using native WDA helpers

---

lib/commands/recordscreen.js

https://github.com/appium/appium/issues/16294

fix: Add ffmpeg options to reconnect automatically if the MJPEG server stops responding

---

lib/ios-fs-helpers.js

Related to https://github.com/appium/appium/issues/16333

chore: Be more forgivable while pulling multiple items from the device

---

lib/ios-fs-helpers.js

Addresses https://github.com/appium/appium/issues/16333#issuecomment-1013144231

fix: Fix top folder path calculation in pullFolder

---

lib/commands/certificate.js
lib/driver.js
lib/py-ios-device-client.js

[py-ios-device](https://github.com/YueChen-C/py-ios-device) has several tasty features which we could integrate into Appium. For now I've just added the support for profiles installation on real devices. @KazuCocoa Could you please help with testing?

feat: Add support of py-ios-device for certificate install on real devices

---

.github/workflows/publish.js.yml

I remember https://github.com/appium/appium-xcuitest-driver/pull/1235 for appium v2.
---
i need to push once after this pr tho...

ci: run shrinkwrap in pushing action

---

.github/workflows/publish.js.yml

since we'll have cases just bump package.json in v2

chore: remove paths-ignore package.json

---

README.md

to address https://github.com/appium/appium-ios-device/pull/88

docs: address openssl version in real device section

---

lib/commands/appearance.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/575

chore: Use the updated endpoint to set device appearance

---

lib/commands/app-management.js
lib/commands/certificate.js
lib/commands/context.js
lib/commands/cookies.js
lib/commands/element.js
lib/commands/execute.js
lib/commands/file-movement.js
lib/commands/find.js
lib/commands/general.js
lib/commands/gesture.js
lib/commands/location.js
lib/commands/navigation.js
lib/commands/pcap.js
lib/commands/performance.js
lib/commands/proxy-helper.js
lib/commands/record-audio.js
lib/commands/recordscreen.js
lib/commands/screenshots.js
lib/commands/timeouts.js
lib/commands/web.js
lib/commands/xctest.js
lib/driver.js

WebDriverAgent class still uses a separate logger. Will need to work on that separately in order to align this behavior

refactor: Switch to the built-in driver logger

---

README.md
lib/commands/execute.js
lib/commands/gesture.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/595

feat: Add scrollToElement extension

---

.github/workflows/publish.js.yml

https://github.com/appium/appium/discussions/17112#discussioncomment-3057952
Let's see how this will help.
On my local, actually removing `node_modules/appium` helped to remove it from `npm-shrinkwrap.json`

chore: remove appium module from npm-shrinkwrap.json

---

lib/desired-caps.js
lib/simulator-management.js
lib/utils.js

This cap should not be required as it is not used for real device selection at all and for simulators it's anyway optional.

refactor: Make deviceName optional

---

README.md
lib/commands/execute.js
lib/commands/gesture.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/611/files

feat: Add mobile shortcut for dragFromToWithVelocity gesture

---

docs/real-device-config.md

Appended a few description about codesign

docs: tune the provisioning profile stuff

---

ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/basic/basic-e2e-specs.js

- only in `test/functional/basic/basic-e2e-specs.js`
- if no problem, I'd like to continue working on the others under  `test/functional` as well.
- some of the methods are jswp (e.g. `getLogTypes`). is it ok?

test: convert wd method calls to webdriverio method calls

---

ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js

- only in `test/functional/basic/basic-e2e-specs.js`
- also addresses https://github.com/appium/appium-xcuitest-driver/pull/1447#discussion_r1009185499

test: convert wd method calls to webdriverio method calls for alerts

---

ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/basic/element-e2e-specs.js

- only in `test/functional/basic/element-e2e-specs.js`

test: convert wd method calls to webdriverio method calls for elements

---

ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/basic/find-e2e-specs.js
test/functional/desired.js
test/functional/device/calendar-e2e-specs.js
test/functional/device/file-movement-e2e-specs.js
test/functional/device/motion-e2e-specs.js
test/functional/device/otherApps-e2e-specs.js
test/functional/device/xctest-e2e-specs.js
test/functional/helpers/element.js

This PR fixes functional/device e2e tests and enables them on CI.
I'm going to add [reduceTranparency capability](https://github.com/appium/appium/issues/17905) and E2E test for it but I noticed device tests are not available now.

test: Fix functional/device e2e specs

---

lib/driver.js
lib/simulator-management.js
package.json
test/unit/driver-specs.js
test/unit/simulator-management-specs.js

Based on https://github.com/appium/appium-ios-simulator/pull/348

feat: Bump the major version of appium-ios-simulator

---

package.json

by bumping up the ios simulator version

fix: set permissions for simulator

---

ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/long/typing-stress-e2e-specs.js

This PR fixes `e2e-test:long` using webdriverio.

ci: fix typing stress specs

---

test/functional/basic/gesture-e2e-specs.js

This PR fixes gesture-e2e-specs.js so it checks this fix https://github.com/appium/appium-xcuitest-driver/pull/1477
I have some points that are not clear to me, so I'm asking in the comments. I'm hoping you can help me with them 🥺

ci: fix gesture specs

---

test/functional/basic/face-id-e2e-specs.js
test/functional/desired.js

as mentioned in https://github.com/appium/appium-xcuitest-driver/pull/1482#discussion_r1060230398, it is better to have face id tests since more iOS devices have face id authentication.

test: add face id tests

---

ci-jobs/pr-validation-build.yml
ci-jobs/templates/ios-e2e-template.yml
ci-jobs/templates/xcuitest-e2e-template.yml
test/functional/basic/basic-e2e-specs.js
test/functional/desired.js
test/functional/helpers/session.js

SSIA, see https://github.com/appium/appium-xcuitest-driver/pull/1478 for the background.
ref macos-12 https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

ci: bump Mac OS 12 and XCode 14 in CI

---

.github/workflows/publish-doc.yml

let me try if we can run on CI. Then, the command can after every release

ci: add publish doc

---

docs/execute-methods.md
lib/commands/execute.js
lib/commands/navigation.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/661

feat: Add deepLink extension

---

docs/execute-methods.md
lib/commands/execute.js
lib/commands/geolocation.js
lib/commands/index.js
package.json

Based on https://github.com/appium/WebDriverAgent/pull/662/

feat: Add simulated geolocation extensions

---

package.json
test/functional/web/safari-ssl-e2e-specs.js

Ref: https://github.com/appium/appium/issues/16403

test: Update safari-ssl-e2e tests for WebDriverIO compatibility

---

test/functional/basic/alert-e2e-specs.js
test/functional/basic/basic-e2e-specs.js
test/functional/basic/face-id-e2e-specs.js
test/functional/basic/find-e2e-specs.js
test/functional/basic/touch-id-e2e-specs.js
test/functional/device/file-movement-e2e-specs.js
test/functional/device/performance-e2e-specs.js
test/functional/helpers/simulator.js
test/functional/web/helpers.js
test/functional/web/safari-basic-e2e-specs.js
test/functional/web/safari-nativewebtap-e2e-specs.js

addresses: https://github.com/appium/appium-xcuitest-driver/issues/1448

refactor: cleanup process.env.CLOUD and process.env.REAL_DEVICE

---

docs/real-device-config.md

Adds https://github.com/appium/appium/issues/18378#issuecomment-1482678074

docs: update real-device-config.md

---

docs/execute-methods.md
lib/commands/certificate.js
lib/commands/execute.js

Adds command for py-ios-device client for removing profile from real device

feat: Add command for mobileRemoveCertificate for real devices

---

.github/workflows/docs.yml
package.json

This reuses most of Appium's docs preview workflow.  Let's see if it works!

chore(ci): attempt to get docs preview working

---

.github/workflows/docs.yml

run as pull_request_target for permissions purposes
this is the same thing that appium/appium does

chore(ci): fix docs workflow

---

.github/dependabot.yml

I forgot this file needed to disappear.

chore(ci): remove dependabot config

---

lib/commands/certificate.js
lib/py-ios-device-client.js

Addresses https://github.com/appium/appium/issues/18507

fix: Fix the return type of mobile: removeCertificate extension

---

.github/workflows/publish-doc.yml
package.json

Just to tweak the task. This won't run automatically yet.

ci: update publish-doc.yml (just update a few)

---

.releaserc

Closes https://github.com/appium/appium/issues/18553

chore(ci): commit package-lock.json upon release

---

docs/execute-methods.md
lib/commands/gesture.js

Based on https://github.com/appium/WebDriverAgent/pull/699

chore: Update the arguments list of `mobile: selectPickerWheelValue` extension

---

lib/commands/execute.js
lib/commands/web.js

Addresses https://github.com/appium/appium/issues/18722
Also fixed the previously broken indentation for some methods there.

fix: Align initial atom wait timeout with alerts check interval

---

docs/device-preparation.md

Address https://github.com/appium/appium/issues/14178#issuecomment-1569955191 in the documentation

docs: address isInspectable option for WebView

---

docs/execute-methods.md
lib/commands/audit.js
lib/commands/geolocation.js
lib/commands/index.js
lib/driver.js
lib/execute-method-map.ts
package-lock.json
package.json

Based on https://github.com/appium/WebDriverAgent/pull/727

feat: Add 'mobile: performAccessibilityAudit' extension

---

lib/ios-deploy.js

Addresses https://github.com/appium/appium/issues/18753
Kudos to @tomriddly for finding a proper workaround.

fix: Only request chosen application attributes

---

.github/workflows/publish-doc.yml
package-lock.json
package.json

this should work now (or at least it will once @boneskull's updates are merged/published from https://github.com/appium/appium/pull/18751

docs: update publishing logic to actually build docs

---

.github/workflows/functional-test.yml

Reverts appium/appium-xcuitest-driver#1773

Revert "chore(workflows): pin dependencies"

---

package-lock.json
package.json

Helps https://github.com/appium/appium/issues/18749#issuecomment-1644903756

fix: isAppInstalled in Xcode 15 env for simulator

---

lib/execute-method-map.ts

Addresses https://github.com/appium/appium/issues/18944

fix: Args order for mobileTapWithNumberOfTaps call

---

test/unit/commands/gesture-specs.js

https://github.com/appium/appium-xcuitest-driver/actions/runs/5935827737/job/16095002455?pr=1898

tests: Update unit tests

---

package.json

Background https://github.com/appium/appium-xcuitest-driver/pull/1973#discussion_r1320751851

chore: Remove prettier from pre-commit hook

---

docs/device-preparation.md

I have confirmed this setting allows me to automate web content in chrome with:
```
server_url = 'http://localhost:4723'
caps = {
"platformName": "ios",
"automationName": "xcuitest",
"udid": "00008020-000E5CDA0A23002E",
"bundleId": "com.google.chrome.ios",
"webDriverAgentUrl": "http://192.168.4.255:8100"
}
core = Appium::Core.for url: server_url, caps: caps
driver = core.start_driver
driver.execute_script 'mobile:getContexts'
```

docs: device-preparation

---

docs/capabilities.md
lib/commands/element.js
lib/desired-caps.js

feat: add capability to run special input event triggering after send keys

---

.github/workflows/publish.js.yml
.releaserc
package.json

not clear the reason since my local dry run had `npm-shrinkwrap.json` expectedly in the `npm publish`... and so far I cannot find the place that could remove `npm-shrinkwrap.json` unexpectedly....
Thus let me explicitly set `npm-shrinkwrap.json` in package.json how it will be...

fix: try fix release to include npm-shrinkwrap.json

---

docs/execute-methods.md
lib/commands/app-management.js
lib/driver.js
lib/execute-method-map.ts

Based on https://egeek.me/2021/06/12/how-to-save-and-restore-application-data-on-ios-simulator-quickly/

feat: Add clearApp extension

---

.github/workflows/publish.js.yml

let me run without publishment for testing

ci: tune publish

---

package.json

let me release a new patch version for ios 17. I'll merge after CI passes

fix: include a fix of setAppearance in iOS 17+

---

.github/workflows/functional-test.yml

ref: https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new

ci: make upload file name unique for upload-artifact@v4

---

docs/reference/execute-methods.md
lib/commands/index.js
lib/commands/memory.js
lib/devicectl.js
lib/driver.js
lib/execute-method-map.ts

feat: Add 'mobile: sendMemoryWarning' extension

---

lib/commands/log.js
lib/device-log/ios-crash-log.js

This will same some milliseconds on session startup.
@KazuCocoa Could you please verify if it works ok on real devices?

chore: Paralelize log collection startup

---

package.json

Based on https://github.com/appium/appium-remote-debugger/pull/356

chore: Bump remote debugger version

---

package.json

fix: respect defaultActiveApplication settings in activeApplication selection

---

lib/real-device.js

chore: left a comment for future work

---

.github/workflows/publish-doc.yml
.github/workflows/unit-test.yml

This PR includes 3 changes:
* https://github.com/appium/appium/pull/20059
* Adjust unit tests to be skipped for Markdown file changes
* Use latest Node LTS for publishing docs

ci: adjust unit test & docs publishing workflows

---

lib/app-infos-cache.js

Let me leave this dev note for future reference

chore: add note about .app naming finding for future reference

---

lib/commands/web.js

Related to https://github.com/appium/appium/issues/20300

fix: Respect the remote port capability for real devices

---

docs/reference/execute-methods.md
lib/execute-method-map.ts

Similar to https://github.com/appium/appium-uiautomator2-driver/pull/800

feat: Add mobile: wrappers for the clipboard API

---

lib/simulator-management.js

Addresses https://discuss.appium.io/t/appium-shutdownothersimulators-is-not-working/43005

fix: Filter out other simulators properly for shutdown

---

lib/commands/context.js
lib/commands/log.js
lib/commands/types.ts
lib/driver.js
lib/utils.js

This PR is done for demonstration purposes in order to show the idea of BiDi utilisation in mobile drivers
See https://w3c.github.io/webdriver-bidi/#event-log-entryAdded for more details

feat: Publish different log types over BiDi

---

lib/commands/log.js

Similar to https://github.com/appium/appium-android-driver/pull/958/

fix: Strip colors from server logs

---

lib/doctor/optional-checks.js

I have found the dead link after called the doctor command.

docs: Update README_LINK in optional-checks.js

---

package.json

closes https://github.com/appium/appium/issues/20835

feat: extend to handle critical notification elements in respectSystemAlerts settings

---

lib/commands/bidi/models.ts
lib/commands/bidi/types.ts

Based on https://w3c.github.io/webdriver-bidi/#types-log-logentry

fix: Adjust log level for BiDi events

---

lib/commands/recordscreen.js
lib/driver.js
test/unit/driver-specs.js

Address #(https://github.com/appium/appium/issues/20906)
@mykola-mokhnach Keeping port forward in sync with android - https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/driver.ts#L512-L521

feat: create port forward when mjpegServerPort is provided in caps

---

docs/reference/execute-methods.md
lib/commands/content-size.js
lib/commands/increase-contrast.js
lib/commands/index.js
lib/commands/types.ts
lib/driver.js
lib/execute-method-map.ts
lib/utils.js
package.json

closes https://github.com/appium/appium-xcuitest-driver/issues/2519
Not applied https://github.com/appium/appium-ios-simulator/pull/444  yet

feat: add increase contrast and content size commands

---

lib/driver.js
package.json

Related to https://github.com/appium/appium/pull/21021

fix: Pass reqBasePath proxy option

---

lib/commands/file-movement.js

https://github.com/appium/appium-xcuitest-driver/commit/6f3e7b5b30f7f5c438cd0cc0fce1f2aa7a3f4f3b#commitcomment-154640302

fix: bind this

---

docs/reference/execute-methods.md

Same as https://github.com/appium/appium-uiautomator2-driver/pull/890

docs: Add a comment about preferable log broadcast endpoint

---

lib/commands/certificate.js
lib/commands/find.js
lib/commands/recordscreen.js
lib/device-log/ios-simulator-log.ts
lib/driver.js

use optional chain for better readability

refactor: use optional chain for better readability

---

docs/guides/troubleshooting.md

To add https://github.com/appium/appium-xcuitest-driver/issues/2572 info in the troubleshooting

docs: add remaining permission on iOS 18+ env

---

lib/ios-fs-helpers.js
test/functional/basic/face-id-e2e-specs.js
test/functional/basic/touch-id-e2e-specs.js

This test doesn't run on CI. I'll merge after CI passes.
iOS 26 supports face id. I have confirmed this file worked on my local.

test: tune face id

---

package.json
scripts/download-wda-sim.mjs
scripts/tunnel-creation.mjs

As https://github.com/appium/appium-xcuitest-driver/pull/2587#issuecomment-3009109934
I'll take a look at the import error further later, so this is a temporary workaround

fix: add @ temporary fix

---

lib/device-log/safari-console-log.ts
lib/device-log/safari-network-log.ts
package.json

https://github.com/appium/appium/issues/21406
Includes fixes from https://github.com/appium/appium-remote-debugger/pull/427

fix: Safari network logging

---

lib/commands/context.js
lib/driver.js
package.json
test/functional/web/safari-basic-e2e-specs.js

Theoretically the debugger change is breaking, but since we anyway don't officially support anything below iOS 17 by this driver it should not break anything. Thus only changes the minor release number.

feat: Bump remote debugger
