- index.js
- lib/commands/alert.js
- lib/commands/index.js
- lib/driver.js
- package.json
- test/functional/alert-e2e-specs.js
- test/functional/desired.js
- test/functional/driver-e2e-specs.js
- test/unit/commands/alert-specs.js
Appium uses old-style alert endpoints while WDA uses W3C spec versions. This means we cannot just proxy, but need to catch, manipulate the endpoint, and send along.
> Add translation commands for alerts

- lib/driver.js
All timeout commands should be handled by Appium, not WDA.
> Handle all timeouts locally

- lib/commands/find.js
- lib/driver.js
We should never be calling on the wda proxy directly, but instead use the `proxyCommand` helper.
> Always use proxyCommand helper

- .travis.yml
- lib/commands/proxy-helper.js
- test/unit/commands/proxy-helper-specs.js
WDA does not necessarily return an http error code, so our proxy logic does not necessarily catch errors.  Handle this case while the WDA folks fix things.
> Handle errors from manual proxy

- .travis.yml
- index.js
- lib/driver.js
- lib/webdriveragent.js
- package.json
- test/functional/basic-e2e-specs.js
- test/functional/desired.js
- test/functional/find-e2e-specs.js
- test/functional/helpers/session.js
- test/functional/webdriveragent-e2e-specs.js
- test/functional/webview-e2e-specs.js
Handle recoverable errors in WDA launch. Close logs on session end. Handle xcodebuild closing (which seems to fail a lot with iOS 10/Xcode 8) better. Skip a couple of tests that don't work with Xcode 8.
> Make sure that iOS 10 passes the tests

- README.md
- lib/realDeviceManagement.js
- package.json
Use `libimobiledevice`'s `idevice_id` instead. Otherwise we run into issues with not being able to load on non-OSX machines.
> Remove dependency on node-ios-device

- README.md
- lib/webdriveragent.js
Add documentation about Carthage, and only build the actual dependencies, not Inspector, which we don't need.
> Only install WDA dependencies we use

- lib/webdriveragent.js
One more dependency from WDA needs to be accounted for. With this in the package appears to be runnable from Appium without needing Inspector and its node modules.
Added a little logging, too, to make things a little less opaque.
> Make sure we have the WDA resource structure

- lib/commands/gesture.js
This is for backward compatibility as we supported scroll without element.
> if there is no element passed then do action on application.

- lib/commands/context.js
- lib/driver.js
Make sure that we have a `platformVersion` set, even if one is not passed in.
For now, we have no way of getting the version of a real device. But once we have better support in (which is in the works) we should be able to.
Resolves https://github.com/appium/appium/issues/6765 and https://github.com/appium/appium-xcuitest-driver/issues/101
> Make sure we have a platformVersion

- test/functional/basic/alert-e2e-specs.js
WDA returns the wrong error when an alert is not found. For now, catch it and translate.
Upstream fix: https://github.com/facebook/WebDriverAgent/pull/271
Resolves, temporarily, #119
> Add test to confirm absence of alerts throws correct error

- lib/driver.js
- lib/ios-deploy.js
- lib/webdriveragent.js
Make sure we throw a useful error when no real device logging system is found.
Addresses #115
> Add error handling when real device logger does not exist

- .travis.yml
Travis' Xcode 8 installation now supports 9.3 and 10 sims. And already has Carthage installed!
> Use Xcode 8 on travis

- lib/webdriveragent.js
Otherwise we get difficult-to-discern errors in running the WebDriverScript. See, for instance, https://github.com/appium/appium/issues/6853
> Throw error if carthage does not exist

- README.md
- lib/desired-caps.js
- lib/driver.js
- lib/webdriveragent.js
Many people are having problems involving Xcode not being able to run the test. This adds a desired capability, `showXcodeLog` which puts all of xcodebuild's logs into the appium server log. Hopefully this will make things a little less blind.
> Add showXcodeLog cap and functionality

- lib/webdriveragent.js
#157 Introduced a check for the presence of Carthage. It seems that some systems don't pass the check even if Carthage is available, so there were false negatives. 
Change this to a log line, which in conjunction with the scripts not working will point to the correct solution to users' problems.
> Change carthage error to info log

- lib/driver.js
Make sure we have a message before trying to check it. Addresses #191.
Also add a line mentioning the driver version, so that we know.
> Make wda error check more defensive

- lib/commands/general.js
- lib/commands/gesture.js
- test/functional/basic/element-e2e-specs.js
For now, just press the `Done` button on the keyboard. We will likely need to update as time goes on. Alas.
> Add hide keyboard method

- test/functional/desired.js
Make it so running the test suite on real devices without needing to change anything.
> Add ability to auto-detect xcconfig for running test suite

- lib/driver.js
When driver.closeApp() and driver.launchApp() was called, options were reset in the driver which led then to other subsequent errors. This is fixed by just initializing the options map once.
The xml hierarchy did not contain values for element coordinates and element sizes. This is fixed by reading the coordinates and sizes correctly.
> Fixes issues when initializing options and generating the xml hierarchy

- lib/driver.js
Auto-initialize webview when `autoWebview` cap set.
Fixes https://github.com/appium/appium/issues/6926
> Add handling of autoWebview cap

- lib/webdriveragent.js
Since we proxy the commands over usb, there is no need for the restriction on devices being on the same network.
> Remove check for null url, since we use iproxy

- lib/commands/find.js
Allow the use of the short forms of class names. 
Fixes https://github.com/appium/appium/issues/6871
> Add modification of short class name forms

- lib/commands/gesture.js
Rather than throw an error, try to do the click (which may, itself throw an error if it can't find the element, but at least we try).
See https://github.com/appium/appium/issues/6941
> Make sure scroll failure does not ruin click

- README.md
- bin/run-xcodebuild.sh
- lib/desired-caps.js
- lib/driver.js
- lib/webdriveragent.js
People have problems with running real device tests. There is a chance that this is caused by being unable to access the private key for the certificate. See https://github.com/appium/appium/issues/6955
> Use script to set security and run xcodebuild

- lib/desired-caps.js
These are used in cases where we need to test out something in WebDriverAgent. If we don't validate them people complain that there is an "error" in the logs. 
But not adding these to the list of caps, since it is an internal thing.
> Add agentPath and bootstrapPath caps to validator

- lib/webdriveragent.js
`idevicesyslog` on some systems does not connect to the device. If that is the case, we will never be able to tell if the system is running, even if it is. Log the error.
> Add log line if logging fails

- README.md
- lib/driver.js
- lib/ios-deploy.js
- lib/webdriveragent.js
* Make sure that the path to `deviceconsole` is the executable, not the directory, or we get cryptic spawn errors (Fixes https://github.com/appium/appium/issues/6895 and #227)
* Throw an error if `iproxy` spawn does not happen (or else we just hang).
> Add better error handling

- lib/commands/find.js
We were logging every xpath search, no matter if we changed anything.
> Only log changed find selector if it is necessary

- lib/commands/find.js
- test/unit/commands/find-specs.js
UIAutomation selectors sometimes have the word 'View' appended to it and the XCUI equivalents don't. Added a function that strips out the word 'View' unless it is one of the exceptions (ScrollView, CollectionView, TextView, WebView)
(@jlipps @imurchie)
> Strip 'View' from XCUI selectors

- lib/commands/find.js
- test/unit/commands/find-specs.js
(see issue https://github.com/appium/appium-xcuitest-driver/issues/270)
To test if 'UIA' is in the axis of an xpath check if it has a forward slash preceding it or if it is at the beginning of the selector string
> Only rename 'UIA' if it's in an XPath's axis

- lib/driver.js
We already log that we've made the `platformVersion` to the maximum sdk version. Add a line saying this might be a problem, since the problem that does come up is opaque.
See https://github.com/appium/appium/issues/7126
> Add log line when platformVersion has been inferred

- lib/driver.js
`this.opts` has the massaged capabilities, so use it. Otherwise all the prior config work is ignored.
Fixes #77
> Send correct opts to create sim

- bin/run-xcodebuild.sh
- lib/webdriveragent.js
Using `test-without-building` alone does not work with real devices, but together with `build-for-testing` is faster than the `build test` solution we were using.
> Handle real device startup better

- lib/commands/gesture.js
- test/functional/basic/gesture-e2e-specs.js
We had a wonky double tap implementation that needed a new action to be added to the TouchAction API. Add to that the ability to set a "count" to the options on tap.
> Fix double tap implementation

- bin/run-xcodebuild.sh
- lib/webdriveragent.js
Ugh.
So it turns out that on real devices the changes to build targets swallows any error handling. So reverse it. The marginal increase in performance is not worth the opacity.
> Remove build-without-testing/test-without-building for real devices

- README.md
- lib/commands/gesture.js
- test/functional/basic/gesture-e2e-specs.js
This is the first multi-action to be supported.
Zoom works. Pinch does not, for Apple reasons (a bug has been issued).
[Apple's API](https://developer.apple.com/reference/xctest/xcuielement/1618669-pinchwithscale?language=objc): 
```objective-c
- (void)pinchWithScale:(CGFloat)scale 
velocity:(CGFloat)velocity;
```
The only things we can adjust are scale (0.02 to 1 for pinch, 1 to ? for zoom) and velocity. It is unclear what either mean in real terms.
We map two finger action with `touch`-`moveTo`-`release` signature. Expects `touch` and `moveTo` to be on the same element, and then takes the `x` and `y` offsets and uses them to decided upon a "scale", which for now is (for zoom) 1 scale factor for every 10 x or y offset difference. From experimentation this comes out to a reasonable amount …
> Add pinch/zoom multi-action

- README.md
- lib/desired-caps.js
- lib/driver.js
- lib/utils.js
These are the same changes as in https://github.com/appium/appium-xcuitest-driver/pull/308, which has been corrupted by my screwed hands.
> Add driver capability to prevent XCTest attachments creation

- lib/webdriveragent.js
- test/functional/basic/find-e2e-specs.js
The way in which we see that WDA is running has changed. Previously it would
print in the device logs two lines, one after another
```
Jul 20 13:03:57 iamPhone XCTRunner[296] <Warning>: Built at Jul 20 2016 13:03:50
Jul 20 13:03:57 iamPhone XCTRunner[296] <Warning>: ServerURLHere->http://10.35.4.122:8100<-ServerURLHere
```
We would look at the first line to get the date, so that for real devices we did
not get some old lines from the logs (on sims we tail the logs, so it is not an
issue).
This has changed. Now I'm seeing
```
Dec  7 10:55:32 iamPhone XCTRunner(WebDriverAgentLib)[386] <Notice>: Built at Dec  7 2016 09:52:17
Dec  7 10:55:32 iamPhone testmanagerd[382] <Notice>: <private>
Dec  7 10:55:32 iamPhone duetexpertd(QueryPrediction)[167] <Error>: Missing results from Connections.
Dec …
```
> Fix handling of real device timestamp

- test/functional/basic/alert-e2e-specs.js
- test/functional/basic/find-e2e-specs.js
On Travis we sometimes get failures because the first test times out. Extend this a little bit, to make the tests more reliable when the load is high.
> Extend alert timeout for travis

- README.md
- lib/desired-caps.js
- lib/webdriveragent.js
- test/unit/webdriveragent-specs.js
I have added some functionality to my own WebDriverAgent fork. Right now I start my WebDriverAgent, then start Appium, which starts its own WebDriverAgent (killing mine in the process), and after the test is done I start mine again for some cleanup.
This pull request allows me to provide a DesiredCapability of `webDriverAgentUrl` which, if present, Appium will use instead of creating its own.
> Allow users to provide their own WebDriverAgent URL

- README.md
- lib/driver.js
- test/unit/driver-specs.js
Warn users who use `autoAcceptAlerts` or `autoDismissAlerts` that the capabilities do not work.
Partial "solution" to https://github.com/appium/appium/issues/6864
Also updates test to use sinon.sandbox instead of manually handling stubs.
> Add warning about autoAcceptAlerts and autoDismissAlerts

- README.md
- lib/desired-caps.js
- lib/driver.js
- lib/ios-deploy.js
- lib/webdriveragent.js
- package.json
- test/functional/basic/basic-e2e-specs.js
- test/functional/desired.js
- test/functional/driver/webdriveragent-e2e-specs.js
- test/functional/web/safari-basic-e2e-specs.js
- test/functional/web/safari-ssl-e2e-specs.js
We currently use the technique of looking at the ios logs (sim or device) and waiting for [the marker that WDA writes on startup](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Routing/FBWebServer.m#L109). This means we need to open and manage the logs, make sure we are looking at the right entries, etc. It is all fraught, as the issue tracker can attest.
This PR strips out all log handling, and instead pings the WDA server until it gets a valid status back, or times out. This is possible since (A) on simulators the WDA server is always on localhost, and (B) on real devices we use `iproxy`, which maps the request over USB, so we also end up talking to localhost. In neither case do we need to _actual_ server url, which is the only information that is available in …
> Move to pinging WDA status for readiness

- lib/ios-deploy.js
- lib/utils.js
- lib/webdriveragent.js
- package.json
- test/functional/basic/basic-e2e-specs.js
Previously there were some issues with using `test-without-building` on real devices. This has been fixed with recent changes to how we check for the server running.
> Update xcodebuild targets for real devices

- lib/commands/web.js
There is bug with new architecture where we wait for alert for at least 500 ms even if there is no alert. So if you check code here  (https://github.com/appium/appium-ios-driver/blob/master/lib/commands/web.js#L334-L346) , `this.remote.executeAtom` get called and then we immediately call `for loop`, at this point `done` is still `false`  as executing atom takes at least 10 ms. So we end up waiting for alert for at least `500 ms`, this increases over all test time significantly. For `xcuitest` , we anyways don't do anything for alert. So i though its better to `override` and remove `checkForAlert`.
Later on we should solve this problem by actually putting `for loop` in different `promise` or some other trick of `promise`
> overriding waitForAtom for xcuitest driver so that we don't wait for alert

- lib/driver.js
- lib/webdriveragent.js
The polling code, on real devices, often times out with socket hangups, even if the device is ready and the status can be retrieved using `curl`. Adding the `forever` flag fixes this, making startup much faster.
> Use forever request for polling server at startup

- lib/driver.js
There is too much in the `stop` function, which is used by the `closeApp` function, too. So move some out, so it is much like the `stop` function in `appium-ios-driver`.
> Move reset logic out of stop into deleteSession

- README.md
WDA/Xcode does not seem to print out the same information when run manually. So update the docs so as not to confuse people.
> Update manual verification documentation

- lib/driver.js
- lib/webdriveragent.js
In the case that WDA has died or stopped responding in some way, sending a `DELETE` session request will fail, and the rest of the shutdown behaviour for the driver will be skipped. So catch and log, allowing the rest of the work to be done.
Hopefully this helps with cleaning up processes.
> Make sure we get past proxying DELETE to WDA

- lib/commands/execute.js
- lib/commands/gesture.js
- test/functional/basic/gesture-e2e-specs.js
- test/unit/commands/gesture-specs.js
Called via execution of 'mobile: swipe'. Must provide direction (up, down, left, or right). Similar to 'scroll'.
> Added swipe capability to gestures

- lib/driver.js
- package.json
- test/functional/basic/basic-e2e-specs.js
- test/unit/driver-specs.js
This should only speed up the things for Xcode 8+. And will work the same way as before for older versions.
This PR depends on https://github.com/appium/appium-ios-simulator/pull/95
> Speed up application install on simulator by doing it in parallel with UI process startup

- README.md
- lib/desired-caps.js
- lib/driver.js
- lib/simulator-management.js
- package.json
- test/functional/driver/driver-e2e-specs.js
Simulator restart procedure is very expensive operation. This PR tries to avoid restarting the Simulator where it is possible and keep it running  between sessions, which will allow to save A LOT of time. And time is money 💯 
The PR depends on https://github.com/appium/node-simctl/pull/30
> Avoid resetting the simulator after the test and speed up test execution by avoiding unnecessary restarts

- lib/webdriveragent.js
If the `showXcodeLog` capability is set, and there is an error, print out the contents of the xcodebuild log.
Addresses https://github.com/appium/appium/issues/7844
> Print contents of xcodebuild log file on xcodebuild error

- README.md
- lib/commands/proxy-helper.js
- lib/desired-caps.js
- lib/driver.js
- lib/webdriveragent.js
This PR adds the ability to set custom timeouts for Appium commands. It might be extremely useful in case with WDA backend, since it sometimes experiences unexpected freezes and stops responding to Appium. This causes Appium to wait for 4-5 minutes until socket timeout happens, which is not very good for automated tests.
This implementation allows to set either common timeout for each command or to set it on per-command basis, which offers our customers better control over the framework.
Depends on https://github.com/appium/appium-base-driver/pull/104
> POC for command execution timers

- README.md
- lib/commands/log.js
- lib/desired-caps.js
- lib/driver.js
- lib/real-device-management.js
- lib/simulator-management.js
- lib/utils.js
- package.json
- test/functional/helpers/session.js
- test/unit/driver-specs.js
Moves some functions out from the driver object to make things clearer. Also uses simulator functions instead of going directly to simctl.
To help with startup, add configuration through `wdaStartupRetries` and `wdaStartupRetryInterval` caps, and move from a recursive strategy to using `retryInterval` for startup retries (see https://github.com/appium/appium/issues/7828).
Fix problem with logging getting started over and over again in certain situations (see https://github.com/appium/appium/issues/7838).
Add xcodebuild log file into the stream when `showXcodeLog` is on and a failure happens (see https://github.com/appium/appium/issues/7844).
> Clean up structure and functioning

- lib/commands/proxy-helper.js
- lib/driver.js
This PR addresses https://github.com/appium/appium/issues/6548
All calls to WDA server are synchronous. So, if we are running some long request, like **createSession**, all the following requests will be automatically put in the internal queue and executed after **createSession**. This behaviour causes timeout errors for some API consumers, like Selenium Grid.
We put the result of **getStatus** call into the cache and return the cached value in case there is some asynchronous WDA request running in the background, so the external consumer may get response in time.
Related to https://github.com/appium/appium/issues/6548
> Cache /status API call result to make it pseudo-asynchronous

- docs/endpoints-wda.md
- lib/commands/general.js
- test/unit/commands/general-specs.js
According to WDA it seems like there are two end points for touch id:
https://github.com/facebook/WebDriverAgent/blob/eeaa1a3bbc9559d41ff3779c73c6678c7715a3d0/WebDriverAgentLib/Commands/FBTouchIDCommands.m
/wda/touch_id
/simulator/touch_id
The second will be deprecated so /wda/touch_id is the correct one to use.
> Fixed touch_id end point when proxying to wda.

- lib/webdriveragent.js
- test/functional/basic/find-e2e-specs.js
Slight tweak so that if the `showXcodeLog` capability is set, and we have an xcodebuild file, we print it out even on success.
> Log xcodebuild file even on success if showXcodeLog is on

- lib/webdriveragent-utils.js
- lib/webdriveragent.js
On xcode 8.0 there is a problem with the latest private headers, in that a method gets duplicated with different parameters. This causes building WDA to break.
> Make header files work for xcode 8.0

- lib/webdriveragent-utils.js
Carthage errors are obscure and make it hard for people. But we have the information about what failed! So use it.
> Make carthage error more informative

- lib/desired-caps.js
- lib/driver.js
- lib/webdriveragent.js
- test/functional/driver/driver-e2e-specs.js
On some systems there seems to be an error when the two phases are done together. Try out having them separated, behind a flag.
> Allow build and test phase of xcodebuild to be separated

- lib/commands/proxy-helper.js
- lib/driver.js
- lib/utils.js
- lib/webdriveragent.js
- package.json
- test/functional/basic/basic-e2e-specs.js
- test/unit/driver-specs.js
This PR allows to get rid of unnecessary flag in XCUITestDriver class and make /status response caching more reliable. The PR depends on https://github.com/appium/appium-base-driver/pull/105
> Simplify status caching

- lib/utils.js
- lib/webdriveragent.js
The driver call to launch currently expects the WDA status to be returned (https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L342) but it is not.
> Make sure status gets through on startup

- lib/commands/gesture.js
Some people have complained that they are adding a `release` to their `tap` actions and then it doesn't work. It is trivial to allow it, and map the whole thing to `tap` anyway.
> Make it so tap-release works as a gesture

- lib/commands/general.js
Native call is much faster and is based on the native XCTest's _dismissKeyboard_ API of XCUIApplication class. There is a known issue about this method is unable to hide keyboard for iPhone if there is no special key assigned for it. This case is handled separately to show correct error description. See https://github.com/facebook/WebDriverAgent/pull/473 for more details.
> Use native WDA call to hide the keyboard

- lib/commands/general.js
As per https://github.com/appium/appium/issues/7741
Please double check whether the flow is correct and matches to what was discussed in that thread.
> Implement new logic for /wda/deactivateApp endpoint

- lib/simulator-management.js
This should fix Safari data cleanup on "soft-reset". Also, some more folders should be added to appium-ios-simulator module. It will be done in another PR.
> Use separate cleaner for Safari

- lib/commands/general.js
- lib/desired-caps.js
- lib/driver.js
- test/functional/basic/iwdp-e2e-specs.js
- test/unit/driver-specs.js
* If startIWDP === true, start ios_webkit_debug_proxy
* Add test to confirm that Safari page can be opened and interacted with when startIWDP == true
* Add test to confirm that interactions with Safari page are rejected when startIWDP == false
* Add unit test to check that it's starting and stopping the server
* Fixed object-shorthand lint error in general.js
(please review @jlipps @imurchie)
> Starts IWDP if real device and cap is set

- .travis.yml
- lib/desired-caps.js
- lib/driver.js
- lib/webdriveragent.js
- test/functional/driver/driver-e2e-specs.js
Make whether you want to use `build-for-testing` and `test-without-building` configurable.
> Add ability to use build and test as build targets

- lib/commands/find.js
- lib/driver.js
- test/functional/basic/find-e2e-specs.js
Add a new locator type for XCUITest-based driver. See https://github.com/facebook/WebDriverAgent/pull/442 for more details.
> Add class chain locator to XCUITest driver

- lib/commands/general.js
- lib/commands/proxy-helper.js
- lib/no-session-proxy.js
- lib/webdriveragent.js
Some WDA commands don't require session ID to be set. Such commands can be executed even if the application under test is not active. This PR adds support for such endpoints to WDA driver
> Add a separate proxy for WDA commands without session ID

- lib/commands/execute.js
- lib/commands/gesture.js
- test/unit/commands/gesture-specs.js
This PR makes all XCTest gestures available for calling via mobile: interface, so one can use them even without specialised wrappers in top-level drivers. This is just a POC, so I didn't create any tests yet. Please kindly check the basic implementation first.
> Make all XCTest gestures available for "mobile:" interface

- lib/driver.js
- test/functional/basic/basic-e2e-specs.js
We have all sorts of logic around `getStatus` so it can function synchronously, but none of it works since the command still gets put into the queue and gets executed after the current command is done. While this is tested, the test just quietly throws an error and moves on:
```
✓ should get the server status
info HTTP --> POST /wd/hub/session/34ec4e62-b7a0-4e8d-a911-d7d471e97a45/timeouts/implicit_wait {"ms":10000}
dbug MJSONWP Calling XCUITestDriver.implicitWait() with args: [10000,"34ec4e62-b7a0-4e8d-a911-d7d471e97a45"]
dbug XCUITest Executing command 'implicitWait'
dbug BaseDriver Set implicit wait to 10000ms
dbug MJSONWP Responding to client with driver.implicitWait() result: null
info HTTP <-- POST /wd/hub/session/34ec4e62-b7a0-4e8d-a911-d7d471e97a45/timeouts/implicit_wait 200 95 ms …
```
> Allow getStatus to bypass command queue

- lib/commands/gesture.js
- test/unit/commands/gesture-specs.js
Trying to decrease the count of GitHub issues about iOS gestures and make the stuff more user-frindly in general.
> Make mobile gestures more user friendly

- lib/commands/alert.js
If a system alert opens there is no way to just click it. If there isn't, it will immediately fail and drop us back to using our logic to find the alert.
> Use native methods first for alerts, even in webview context

- test/functional/helpers/session.js
Don't need it anymore. It's available in the new wd client.
> Remove toggleTouchIdEnrollment monkey patch

- lib/webdriveragent.js
This fixes webdriver build with Xcode 8.3+ and does not require any WDA sources modification. See https://github.com/facebook/WebDriverAgent/pull/525 for more details.
> Add IPHONEOS_DEPLOYMENT_TARGET argument to avoid “unguarded availability” warning with Xcode 8.3+

- lib/commands/screenshots.js
Some of recent commits does not respect the fact, that "simctl io" command works only for simulator. Real devices should still use WDA API. This is fixed now.
Check https://github.com/appium/appium/issues/8146 for the reference
> Fix screenshoting for real device

- package.json
Only need `request-promise` it in the dependencies.
> Remove duplicate dep so warning is gone

- README.md
- lib/driver.js
- lib/webdriveragent-utils.js
- lib/webdriveragent.js
- test/unit/processargs-specs.js
After much testing, it turns out the new isVisible check from WDA works on everything except iOS 9.3. So make that the default. And make sure that rewriting the WDA bundle id is global not just the first instance.
> Minor tweaks after much test running on different platforms

- lib/commands/gesture.js
- test/functional/basic/gesture-e2e-specs.js
* java-client and python client documents it in ms
* 'appium-android-driver' uses duration in ms for longPress (https://github.com/appium/appium-android-driver/blob/ab024485ee1e31b8287a7549f343b294a8ebd29b/lib/commands/touch.js see lines 23-24)
* Found in https://github.com/appium/appium/issues/7597
Reviewers @jlipps @imurchie
> Accept longPress duration in ms (not seconds)

- lib/commands/screenshots.js
- test/unit/commands/screenshots-specs.js
Change screenshoting logic to get the screenshot from WDA first before falling back to simctl. This is done because Simulator window does not respect orientation change since iOS 10.3 and the screenshot returned by simctl gives us incorrectly rotated images, like this one:
Also, added unit tests as a bonus ;)
> Try to get the screenshot from WDA first

- lib/webdriveragent.js
Fixes the issue when the driver throws an error on exit if xcodebuild properly was not initialised properly and files cleanup is enabled:
```
2017-05-02 09:47:39:042 - error: [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'logLocation' of undefined
at WebDriverAgent.get (../../lib/webdriveragent.js:475:52)
at clearSystemFiles$ (../../lib/utils.js:112:19)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.j …
```
> Do not fail on cleanup if xcodebuild property is not set

- lib/driver.js
If platformVersion is passed as a String, it is parsed just fine. If it is passed as a Float, the check against it in startWdaSession will fail, as indexOf() is not a method for Floats. Flip the handling around to parse it as a float regardless of it being a String, Float, or Null so the logic is trivial and easy to follow.
For the record I tested all the possible values I could think of to make sure the original logic would still give the same results, just without errors now. 😄 
```javascript
> parseFloat(9.3) === 9.3
true
> parseFloat("9.3") === 9.3
true
> parseFloat(10.3) === 9.3
false
> parseFloat("10.3.1") === 9.3
false
> parseFloat(null) === 9.3
false
```
> Allow numerical platformVersion capabilities

- lib/driver.js
- package.json
- test/functional/web/safari-execute-e2e-specs.js
Make use of the `appium-ios-driver` capability to execute async javascript from https (using `enableAsyncExecuteFromHttps`).
See https://github.com/appium/appium/issues/3471
> Allow async exec through https

- lib/driver.js
- test/functional/driver/driver-e2e-specs.js
The placement of the test for bundle id meant that if the simulator was not running the check would fail and nothing could progress.
Move the check, and add some tests.
Resolves https://github.com/appium/appium/issues/8605
> Fix error when checking is bundle id exists on simualtor

- .travis.yml
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
- test/functional/driver/driver-e2e-specs.js
Real device remains the same (WDA runs on port 8100 on the device, `wdaLocalPort` specifies the local end of the iproxy bridge). On simulators there is no difference between local and remote, but users sometimes have something running on port 8100, so being able to specify it makes things able to work.
> Use wdaLocalPort for sim port

- lib/commands/navigation.js
- lib/wda/utils.js
- lib/wda/xcodebuild.js
- test/functional/basic/alert-e2e-specs.js
- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/find-e2e-specs.js
- test/functional/basic/gesture-e2e-specs.js
Make launching the driver with Xcode 9 and iOS 11 _possible_. There are still many issues with running tests, not least of which are (a) unable to get the text (either value or label) from text elements, and (b) 3-5 second pause before clicking on any element, after the device gets the request.
This PR is largely to get this in, so things don't get ahead of the work.
> First pass at Xcode 9/ios 11 support

- docs/endpoints-wda.md
According to [source.js](https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/source.js) program, HTTP method type for /source command seems not POST but GET.
> Fix wrong method in /source endpoint document

- README.md
startIWDP is there already so don't need to add that to documentation
> Document calendarAccessAuthorized desired cap

- docs/touch-id.md
- lib/driver.js
- test/functional/basic/touch-id-e2e-specs.js
* Previously, when allowTouchIdEnroll is set to true, you had to call the client method to toggle touch ID enrollment
* With this PR, we now enable touchId enrollment by default if allowTouchIdEnroll is set to true when the simulator starts
* Also added documentation for Touch ID as there wasn't any before
(connected to https://github.com/appium/appium/issues/8676 and https://github.com/appium/appium/issues/8578#issuecomment-308696488)
> Enable toggle touchId enrollment by default

- lib/driver.js
- package-lock.json
- package.json
- test/unit/commands/general-specs.js
users often find themselves in a situation where they want to use
nativeWebTap in some cases and the regular javascript actions
in other cases. This is a perfect example of what the settings
API was invented to handle. So handle it using the settings API!
> make nativeWebTap a setting in addition to a cap

- lib/commands/gesture.js
- test/functional/web/safari-execute-e2e-specs.js
- test/functional/web/safari-ssl-e2e-specs.js
- test/unit/commands/general-specs.js
Remove restriction for `nativeWebTap` on real devices, since it will work for XCUITest. Also switch to using the settings value rather than the cap.
> Allow nativeWebTap on real devices

- lib/commands/log.js
Once `appium-ios-driver` is updated, this will allow the user to specify what real device logger they have, and where. Before it is updated, it will do nothing (including doing no harm).
> Pass realDeviceLogger on to ios-log

- lib/ios-deploy.js
Exclude application uninstall from the default ios-deploy command line since the fact of application install is already verified in _installToRealDevice_ method of **real-device-management** module. Also, this argument forces ios-deploy utility itself to detect application bundle id (see https://github.com/phonegap/ios-deploy/blob/master/src/ios-deploy/ios-deploy.m -> `void uninstall_app(AMDeviceRef device)`), which affects performance and causes issues.
> Remove unnecessary uninstall argument from ios-deploy command line

- lib/driver.js
Currently we log `[object Object]` instead of the href.
```
dbug XCUITest Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at [object Object]...
```
We want:
```
dbug XCUITest Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at http://localhost:8100/...
```
> Fix logging of url

- lib/wda/webdriveragent.js
- test/unit/webdriveragent-specs.js
Make sure that `webDriverAgentUrl` is parsed as a [url](https://nodejs.org/api/url.html#url_class_url) object, as we expect elsewhere. Also remove return value, so that we actually get the status later on.
> Parse webDriverAgentUrl

- lib/commands/element.js
We've been seeing a number of errors (including in the build) where clear times out waiting for an action. Since it is just clearing, it is fine to retry the call to WDA. Seems to much stabler.
> Retry clear

- lib/driver.js
With this change i can open both url in safari and deep links in registered apps through driver.get(). I was not able to make it work without it.
I'll continue using my appium fork so I don't need this request merged. I just want to share result of several day-long investigation.
> Opening apps through deep links

- lib/driver.js
- lib/utils.js
- lib/wda/utils.js
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
- test/unit/utils-specs.js
The previous implementation was trying to change permissions for all WDA derived data folders matched by glob pattern, which is a bad approach for parallel tests. Now we only try to change permissions to the folder, that our xcodebuild process owns.
> Adjust permissions only on the current derived data folder

- lib/wda/iproxy.js
- lib/wda/xcodebuild.js
This promises more stability for real device tests, since in XCTest world they don't not like multiple WDA reinstallations. We are already trying to pick up the session after restart and with this PR merged session pick up should be also possible after Node server restart (see https://stackoverflow.com/questions/37427360/parent-process-kills-child-process-even-though-detached-is-set-to-true for the reference).
> Detach xcodebuild and iproxy processes to keep them running even after Node server is terminated

- package.json
- test/functional/basic/alert-e2e-specs.js
- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/element-e2e-specs.js
- test/functional/basic/find-e2e-specs.js
- test/functional/basic/gesture-e2e-specs.js
- test/functional/driver/driver-e2e-specs.js
- test/functional/long/typing-stress-e2e-specs.js
Update WDA, which allows us to un-quarantine most of the tests for iOS 11. The exceptions are:
* Gestures on arbitrary coordinates seem to click the wrong thing
* A couple of tests that rely on parsing the device logs, which still don't exist for iOS 11
> Update WDA and fix most of iOS 11 problems

- lib/wda/xcodebuild.js
In Xcode 9 the derived data folder does not comes up on the list of opened files `lsof` returns. So, find the xcodebuild log file and try to find the derived data folder from there.
> Update derived data parsing to handle xcode 9

- lib/driver.js
> 2017-07-27 04:19:52:769 - info: [debug] [XCUITest] The app has been installed successfully.
> 2017-07-27 04:19:52:770 - info: [debug] [BaseDriver] Event 'appInstalled' logged at 1501129192770 (09:49:52 GMT+0530 (IST))
> 2017-07-27 04:19:52:773 - info: [debug] [BaseDriver] Event 'appInstalled' logged at 1501129192773 (09:49:52 GMT+0530 (IST))
> Remove unnecessary event report

- lib/driver.js
- test/functional/basic/basic-e2e-specs.js
This is to avoid
>  2017-07-27 04:19:19:938 - warn: [BaseDriver] The following capabilities were provided, but are not recognized by appium: isFirstSession.
message in logs
> Exclude isFirstSession from capabilities

- lib/wda/utils.js
- lib/wda/webdriveragent.js
It looks like xcodebuild sometimes cannot connect to the simulator server hub while doing parallel tests on Xcode9. That is why we retry process startup. The example log file where this error is present: 
[EFE6BCCE-B610-4FB2-A11A-861674BF6775__HomePageTest2.txt](https://github.com/appium/appium-xcuitest-driver/files/1182559/EFE6BCCE-B610-4FB2-A11A-861674BF6775__HomePageTest2.txt)
> Retry xcodebuild execution for simulator only

- lib/wda/webdriveragent.js
The retry is not necessary for the very first session if we only want to workaround parallel access issues.
> Only retry xcodebuild execution for non-first session

- lib/utils.js
- lib/wda/webdriveragent.js
This situation might happen because we don't kill iproxy on session termination by default. Next time we try to run the same test on Simulator iproxy will be running and intercepting all requests to the WDA, so the requestor won't be able to contact Simulator host (which is the localhost). That is why we try to kill iproxy by local port number pattern rather than by udid in such case to make sure the port is free.
> Handle the situation when Simulator test is executed on the same port after a real device test

- lib/driver.js
- lib/utils.js
- test/unit/utils-specs.js
I decided to rely on internal synchronization primitives rather than AppiumDriver session management. This will make local functional tests more stable and predictable.
> Properly handle shared derived data folder in parallel sessions

- lib/commands/element.js
- test/unit/commands/element-specs.js
WDA may return 0 or 1 for boolean attribute (see https://github.com/appium/appium/issues/9037 for more details). This PR adds a verification for such case and some more love to unit tests.
> Improve getAttribute output interpretation

- lib/commands/screenshots.js
- test/unit/commands/screenshots-specs.js
In some issue reports I still can see that screenshots made by XCTest are not stable. Probably, falling back to idevicescreenshot will help to improve the state of the issue.
> Add fallback to idevicescreenshot for real devices

- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/pasteboard.js
- package.json
- test/unit/commands/pasteboard-specs.js
simctl supports pasteboard operations starting since Xcode SDK 8.1. This PR supports setting and getting the content of simulator pasteboard, setting the encoding of pasteboard text and device type verification (simulator or real device). Client interaction is done via "mobile:" endpoint (the documentation will be added laster after this PR is merged)
> Add the necessary stuff to support pasteboard on iOS simulator

- lib/driver.js
If the capability `webDriverAgentUrl` is set to a non-null value, checking the value of the Xcode version against the iOS platform version does not make sense. This change checks if the check needs to be executed. If this is not the case, a log message with `debug` severity will be emitted.
> Xcode version check against iOS platform version only when webDriverAgentUrl is not set

- README.md
- lib/desired-caps.js
This is useful for parallel testing using real devices.
> Add webkitDebugProxyPort to desired capabilities

- test/functional/parallel/parallel-simulators-e2e-specs.js
This test frequently fails because of a timeout caused by CI system slowness, so it would be better to skip it there.
> Skip parallel sessions tests on Travis CI

- lib/commands/pasteboard.js
- test/unit/commands/pasteboard-specs.js
When I tried to call `getPasteboard` and `setPasteboard`, I got the following error.
According to [node-simctl](https://github.com/appium/node-simctl/blob/master/lib/simctl.js#L311), the commands require `udid` as the 1st argument.
```
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: getPasteboard",[{}],"2f74b0a0-5a51-44b1-b25a-f67c887d91c7"]
[debug] [XCUITest] Executing command 'execute'
[simctl] Error: Error running 'xcrun simctl pbpaste ': Invalid device: undefined
at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
at getPasteboard$ (../../lib/simctl.js:318:11)
at tryCatch (/Users/kazu/GitHub/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] …
```
> fix Invalid device: undefined

- lib/commands/general.js
The openurl approach used by WDA has been reported as unstable, so we only keep it for real devices, as there is no other alternative, and use the old one (`simctl openurl`)  for Simulators.
> Use WDA /url call to WDA for real devices only

- lib/driver.js
- lib/simulator-management.js
If a platformVersion is not specified, but noReset is specified, the driver creates a simulator for the specific session but does not clean it up. This adds a check for noReset and gets a simulator based on a the detected platform version in that case.
This fixes https://github.com/appium/appium/issues/9134
> Fix an issue with simulators being re-created when noReset is specified

- .travis.yml
- test/functional/parallel/parallel-simulators-e2e-specs.js
For now we still need to support Xcode 7.3.
Also add subset of tests to run on 7.3 and 9 in Travis (currently 9 is failing... will look into under another PR).
> Fix compilation on Xcode 7.3

- lib/commands/log.js
- test/unit/log-specs.js
* Replaced `this.logs = this.log || {}` with `this.logs = this.logs || {}`
* This was causing it to be overwritten every time
* Was able to reproduce with a unit test that showed startCapture being called more than once
(connected to: https://github.com/appium/appium/issues/7838)
> Fix: Typo was causing startCapture to be called more than once

- lib/commands/execute.js
- lib/commands/source.js
WDA provides a possibility to represent page source in different formats (for now _xml_ and _json_ formats are available). I would like to [extend](https://github.com/facebook/WebDriverAgent/pull/731) it in WDA, so the _description_ format is available, which works much faster, since it's a single native call and might be extremely useful for debugging purposes.
> Add a possibility to get page source in different formats

- lib/wda/utils.js
I see many people complain about they don't get this error message, because it is shown even if carthage is installed, but not present in PATH. So I decided to improve it.
> Improve the error message, which is shown when carthage binary cannot be located

- lib/driver.js
- lib/utils.js
- lib/wda/utils.js
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
This PR is related to https://github.com/appium/appium-xcuitest-driver/pull/537
The idea is to apply the lock on top level, so we don't have to think about synchronisation on the lower levels, which makes the code safer and simpler. Yes, we'll probably loose several seconds in parallel drivers initialisation because of this change, but the overall safety about parallel sessions won't corrupt shared resources of each other is more important.
> Move resources lock to the top hierarchy layer

- lib/wda/utils.js
- lib/wda/xcodebuild.js
While investigating my xcodebuild code 65 error and updatedWDABundleId capability behavior, I found the following problems when I used updatedWDABundleId:
- When I tried simple dummy updatedWDABundleId value like "A" or "B", WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj become broken. This is because resetProjectFile method replaced many occurrences of "A" or "B" in project.pbxproj despite these strings are not part of PRODUCT_BUNDLE_IDENTIFIER value.
- When Appium server is killed forcibly and resetProjectFile is not called unfortunately, project.pbxproj file keeps having the user specific bundle ID. When this happened, udpateProjectFile method cannot replace bundle ID again, since now project.pbxproj does not have the "com.facebook.WebDriverAgentRunner" string occurrence.. …
> Fix updateProjectFile/resetProjectFile potential problems.

- lib/utils.js
- test/unit/utils-specs.js
Allow users to use the logical `"iPhone 8"`, `"iPhone 8 Plus"` and `"iPhone X"` for `deviceName`, instead of the actual `"iPhone2017-A"`, `"iPhone2017-B"` and `"iPhone2017-C"`.
> Add device name translation for new iPhones

- lib/commands/screenshots.js
- test/functional/basic/basic-e2e-specs.js
- test/unit/commands/screenshots-specs.js
On iPhone 7/8 Plus devices WDA screenshot crashes. Since we don't really have any reliable way to tell if something is one of those devices, prefer `idevicescreenshot` to do real device screenshoting.
> Prefer libimobiledevice over WDA for real device screenshot

- lib/commands/screenshots.js
There is no point in retrying taking a real device screenshot with _idevicescreenshot_ tool. We should fall back to the WDA method instead.
> Do not retry idevicescreenshot for real devices

- lib/driver.js
For now it is not very clear for users why the session is not started if they replace the device.
> Change wording for logging message to make it more helpful for clients

- lib/commands/screenshots.js
- test/unit/commands/screenshots-specs.js
We can do this ourselves if idevicelib is too lazy for it. The penalty - one extra call to WDA in order to detect the current  display orientation value.
> Fix screenshot rotation for landscape mode

- lib/commands/log.js
- lib/device-log/ios-log.js
- lib/driver.js
- package.json
- test/unit/log-specs.js
Xcode9 Simulator does not really like if we append anything to the system logs ourselves (it just stops logging at all). Also, the logic, which is coming from ios-driver contains some obsolete stuff for Xcode 6 and older, which we don't support anymore.
> Update simulator logs capture logic

- lib/commands/screenshots.js
- test/unit/commands/screenshots-specs.js
`this.getOrientation` command is not available inside commands context, so I need to use `proxyCommand` instead.
> Fix getting device orientation

- lib/commands/screenshots.js
- lib/wda/utils.js
- test/functional/web/helpers.js
- test/functional/web/safari-basic-e2e-specs.js
- test/unit/commands/screenshots-specs.js
Update WDA and add https://github.com/facebook/WebDriverAgent/pull/787
This means that we can go to WDA for screenshots first, then fall back to `idevicescreenshot` if necessary. Blurgh.
> Update WDA and real device screenshot logic

- lib/driver.js
- lib/utils.js
- lib/wda/webdriveragent.js
This PR should resolve an issue when people try to use different simulator types on the same machine and the driver automatically picks up the previously cached session from the previous run, which results in non-expected behaviour.
> Perform obsolete cached processes cleanup if multiple simulators are used on a single machine

- lib/driver.js
- test/unit/language-specs.js
Set the language and locale on the launched app by passing the right process arguments to WDA
> Pass language and locale along with arguments to WDA

- lib/commands/log.js
- lib/device-log/ios-log.js
- lib/driver.js
- test/functional/driver/driver-e2e-specs.js
I have observed that in the recent Xcode versions the log, which is written by Simulator to the standard log file, contains pretty limited data. However, more detailed log is available via `log stream` tool, which is a part of simctl tool set. Check http://shashikantjagtap.net/simctl-control-ios-simulators-command-line/ for more details.
> Use simctl tool for Simulator logs capture

- test/functional/desired.js
- test/functional/driver/driver-e2e-specs.js
Recent work from @mykola-mokhnach (see 063b320efbcb85517f4ff395bf2295bfac4044e0) makes logging work on iOS 11.
Finally remove the last vestiges of the switches for iOS 11 in the tests.
> Remove restriction on logging tests

- lib/driver.js
Addresses https://github.com/appium/appium/issues/9799
I'm not sure whether we should add this exception to NO_PROXY_WEB list
> Add setAlertText command to NO_PROXY list

- lib/commands/general.js
- lib/commands/index.js
- lib/commands/location.js
- test/unit/commands/location-specs.js
* Move location setting logic to location.js
* Add location setting for real devices
* Add unit tests for simulators and real devices
The idevicelocation tool can be found in this PR [idevicelocation PR](https://github.com/libimobiledevice/libimobiledevice/pull/480). It maybe makes sense for appium to fork libimobiledevice or port libimobiledevice code base to nodejs for faster development
> add location setting functionality for real devices

- lib/driver.js
- test/functional/desired.js
- test/functional/driver/driver-e2e-specs.js
* Edit createSession so that it passes all args to the base 'createSession' instead of just the first argument
* Added tests that call W3C endpoints to verify that it:
* Accepts w3c formatted caps
* Rejects it if 'platformName' is missing
* Parses the 'appium:' prefix correctly
* Tests that 'Element Not Found' call returns 404 status code (JSONWP always returns 500)
> W3C compliance

- lib/driver.js
Addresses https://github.com/appium/appium/issues/9917
> Properly handle the situation when not all of processArguments properties are defined

- lib/commands/general.js
- test/functional/basic/basic-e2e-specs.js
- test/unit/commands/general-specs.js
Currently, `getWindowRect` is defined in [routes.js](https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L540), but it isn't implemented in each drivers.
In this PR, XCUITest starts supporting the window rect. I've set `x` and `y` to `0` since they are not defined in mobile device itself. I mean `width` is the width of mobile devices and `height` is the height of mobile devices. (We must implement `x` and `y` against element level, though.)
for : https://github.com/jlipps/simple-wd-spec#get-window-rect
(Not for : https://github.com/jlipps/simple-wd-spec#get-element-rect )
What do you think?
```
[debug] [JSONWP Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/135A0AC6-E920-42E0-896B-7F9CDC6EB5CC/window/size] with no body
[debug] [JSONWP …
```
> add rect for window

- README.md
- lib/commands/index.js
- lib/commands/lock.js
- lib/driver.js
- test/functional/basic/basic-e2e-specs.js
Recreated https://github.com/appium/appium-xcuitest-driver/pull/595
> Implement handlers for lock/unlock API

- lib/device-log/ios-crash-log.js
My computer recently crashed and generated a file like
```
-rw-------   1 isaac staff  69647 Jan 29 07:24  contactsdonationagent_2018-01-02-175430_Isaac-Murchie-SL0219.crash
-??????????  ? ?     ?          ?            ?  contactsdonationagent_2018-01-05-165658_Isaac-Murchie-SL0219.crash
-rw-------   1 isaac staff  69213 Jan 29 07:24  contactsdonationagent_2018-01-06-015159_Isaac-Murchie-SL0219.crash
```
This, in turn, caused the start up to fail with the following:
```js
ERR! XCUITest Error: ENOENT: no such file or directory, lstat '/Users/isaac/Library/Logs/DiagnosticReports/contactsdonationagent_2018-01-05-165658_Isaac-Murchie-SL0219.crash'
ERR! XCUITest     at Error (native)
ERR! XCUITest  { Error: ENOENT: no such file or directory, lstat …
```
> Better handle broken crash reports

- lib/commands/recordscreen.js
It might be that if one is running parallel sessions then these two will try to create a video recording with the same name, which is the undesired behaviour. This patch fixes it.
> Add random suffix to the temporary video name to avoid concurrent sessions conflicts

- lib/driver.js
- package.json
- test/functional/web/safari-ssl-e2e-specs.js
* Since iOS 10.3 SQLite certificate installation stopped working in XCUITestDriver
* To make it work, the order of events has to be as follows:
* Start a simulator
* Install the SSL certificate
* Restart the simulator
* Moved the installSSLCert function to _after_ the simulator is started and then restart the the Simulator so that the certificate will take effect
(related to https://github.com/appium/appium/issues#boards?milestones=Robot%2021%232018-02-02&repos=7530570)
> Reboot Simulator when install cert

- lib/driver.js
- lib/utils.js
It is necessary to init `xcodeversion` property before `determineDevice` is called. Also, it would be safer to assign it to an empty object from the beginning.
> Fix getting xcode version flow

- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/performance.js
- lib/commands/recordscreen.js
- lib/utils.js
- test/functional/basic/performance-e2e-specs.js
Based on https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/Recording,Pausing,andStoppingTraces.html
I've added `relaxedSecurityEnabled` verification, since by default the `instruments` utility adds metrics for all the processes running on the host machine, and not only these, which are running inside the simulator.
> Implement performance measurement with `instruments` utility

- lib/commands/performance.js
Reports generated for the particular process id are much more compact in size in comparison to reports recorded for all running processes.
> Add a possibility to set process id for perf measurement

- lib/commands/proxy-helper.js
- lib/desired-caps.js
- lib/driver.js
* allow `commandTimeouts` cap to be an object, which is then parsed in the validate function.
* we currently map routes to commands at the base driver level, but there are commands that WDA handles that have different routes. This just handle the single case I've come up against. More will need to be added as they present themselves (or someone has time to do an exhaustive search).
* log when the route does not map to a command name, so developers can figure out what is wrong.
> Update command timeout logic

- lib/driver.js
- package.json
- test/unit/commands/alert-specs.js
- test/unit/commands/element-specs.js
- test/unit/commands/find-specs.js
- test/unit/commands/general-specs.js
- test/unit/commands/gesture-specs.js
- test/unit/commands/location-specs.js
- test/unit/commands/pasteboard-specs.js
- test/unit/commands/proxy-helper-specs.js
- test/unit/commands/recordscreen-specs.js
- test/unit/driver-specs.js
- test/unit/language-specs.js
- test/unit/log-specs.js
- test/unit/utils-specs.js
- test/unit/webdriveragent-utils-specs.js
Mostly doing things like renaming mocks/stubs/spies so that the variables correspond to the test apparatus (e.g., don't name a variable with a stub in it `proxySpy`).
> Clean up some tests

- lib/wda/xcodebuild.js
This can cause a problem if, for example, you use a wrapped version of clang that assumes common unix commands are available.
> Make xcodebuild inherit PATH from parent process

- lib/utils.js
- test/unit/commands/recordscreen-specs.js
It looks like `process.memoryUsage()` is [not good](https://stackoverflow.com/questions/48190962/how-to-get-the-value-of-max-old-space-size-from-the-code) to check how much heap memory is left, so we use `v8.getHeapStatistics()` instead.
> Fix free memory size calculation

- README.md
- lib/commands/screenshots.js
- lib/desired-caps.js
- test/unit/commands/screenshots-specs.js
The flow for screenshotting on real devices as it currently stands:
1. Try WDA method (i.e., `GET` request to `/screenshot` on WDA)
2. Try `idevicescreenshot` if available
3. Try WDA method an additional two times
However, there are reported cases where WDA still crashes when getting screenshots
This PR
* Adds `realDeviceScreenshotter` cap to specify the program to use preferentially (for now, either nothing, to use WDA first, or `idevicescreenshot` to use the `libimobiledevice` program). In the former case, the flow remains as above. In the case of using `idevicescreenshot` the flow becomes
1. Try `idevicescreenshot` if available
* Fixes handling of existence of `idevicescreenshot` (`fs.which` throws an error when program not found)
Resolves https://github.com/appium/appium/issues/10590
> Add cap to use idevicescreenshot for real device screenshots

- lib/driver.js
- lib/utils.js
There are still enough people that don't know the difference between emulator and simulator and think that the same application binary could be shared between real devices and simulators. This gonna make them not so self confident.
> Add application platform verification

- lib/commands/element.js
This endpoint exists in Android. It would be also useful to have it in iOS.
> Add keyboard presence verification endpoint

- lib/driver.js
- lib/simulator-management.js
- test/unit/simulator-management-specs.js
When a new simulator is created, the device name becomes `appiumTest-${sessionId}`. It means the name changes every new session. With `noReset` capability case, new simulators are created every new session. As the result, iOS simulators can be created so much.
example (they are same device name and os versions):
The issue was fixed https://github.com/appium/appium/issues/9134.
But if we have no the simulator name on the simulator list, the same error happens. Since xcuitest driver never reachs https://github.com/appium/appium-xcuitest-driver/compare/master...KazuCocoa:create-device-without-dynamic-name?expand=1#diff-bdfd0d2726c6301f92259c6fe3d4928eL18 .
A new created device has `sessionId` in the name and the part changes in the next new session.
_no the simulator name on the simulator …
> create simulators with device name by capability

- lib/commands/context.js
- package.json
On real devices we lose the web socket connection, so this fails.
> Do not turn on safari console logging when moving to native context

- lib/driver.js
Throw an error if one tries to set application attributes while browserName capability is already defined. Unfortunately users tend to do this and then complain something does not work...
> Add caps compatibility verification

- lib/driver.js
- lib/wda/utils.js
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
- test/unit/webdriveragent-specs.js
_try to uninstall WDA if updatedWDABundleId exists #712_ had an unexpected diff in `WebDriverAgent`. This PR has everything except for `WebDriverAgent` in https://github.com/appium/appium-xcuitest-driver/pull/712/files
--
We have no way to get running WDA's `PRODUCT_BUNDLE_IDENTIFIER` [note1](https://github.com/appium/appium-xcuitest-driver/pull/709/files#r198679101), [note2](https://github.com/appium/appium-xcuitest-driver/pull/709/files#diff-dd1c1e9a4d2cba48fc21e5d2c50abcafR134) by running WDA application.
As addressed in https://github.com/appium/appium-xcuitest-driver/pull/712#issuecomment-401088068, we handle running the bundle id in https://github.com/appium/appium-xcuitest-driver/blob/master/lib/wda/utils.js#L8 . When users set `updatedWDABundleId` in their capability, Appum …
> setupCaching to uninstall WDA if it isn't expected WDA

- lib/commands/cookies.js
- lib/commands/index.js
- package.json
- test/functional/web/safari-cookie-e2e-specs.js
- test/functional/web/safari-ssl-e2e-specs.js
`appium-remote-debugger` now supports getting cookies and deleting cookies, so use those instead of JS.
This ought to fix https://github.com/appium/appium/issues/6797
> Move to cookie methods through webkit

- lib/commands/context.js
- lib/commands/log.js
- lib/desired-caps.js
- lib/device-log/rotating-log.js
- lib/device-log/safari-console-log.js
- lib/device-log/safari-network-log.js
- lib/utils.js
- package.json
- test/functional/basic/basic-e2e-specs.js
Add the ability to listen to, and print out, the Safari network logs. This can be adjusted later, but the information displayed is in line with Chrome DevTools.
> Add collection of safari network logs

- lib/commands/file-movement.js
writeFile API does not require encoding to be set if the second parameter is already of type Buffer
> Fix writeFile calls

- lib/device-log/rotating-log.js
- lib/device-log/safari-console-log.js
- lib/device-log/safari-network-log.js
- test/functional/web/safari-basic-e2e-specs.js
The Java client requires a particular format for the logs returned. See https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteLogs.java#L80-L95 and https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
This PR allows this to work:
```java
LogEntries logEntries = driver.manage().logs().get("safariConsole");
for (LogEntry entry : logEntries) {
System.out.println(new Date(entry.getTimestamp()) + " " + entry.getLevel() + " " + entry.getMessage());
}
logEntries = driver.manage().logs().get("safariNetwork");
for (LogEntry entry : logEntries) {
System.out.println(new Date(entry.getTimestamp()) + " " + entry.getLevel() + " " + entry.getMessage());
}
```
> Fix Safari console and network log returns

- lib/driver.js
- lib/simulator-management.js
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
- package.json
- test/functional/basic/touch-id-e2e-specs.js
The most significant change is that Xcode 10b5 often tries to install apps (including WDA) but accessed a plist from its staging directory before actually moving that file there, so everything fails. I'll keep an eye on this as new betas are released, so maybe the complexity of retries can be removed as time goes by.
> Update to run on Xcode 10b5

- .travis.yml
- package.json
This seems like a minimal Travis config to allow tests to run on Linux but not need the full dev deps.
> Move optional dependencies back to dev

- lib/commands/gesture.js
This should workaround the problem from https://github.com/appium/appium/issues/11273
> Filter out zero waits from W3C actions

- lib/wda/utils.js
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
Sometimes Xcode caches outdated WDA libs and builds/installs outdated binary after component upgrade. We must perform the cleanup after each upgrade to make sure there are no such leftovers.
> Perform WebDriverAgent project cleanup after each upgrade

- .travis.yml
- package.json
- test/env/env.js
- test/env/ios-sim-platforms.js
- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/calendar-e2e-specs.js
- test/functional/desired.js
- test/functional/web/safari-ssl-e2e-specs.js
* Fix problem with env.js not getting the latest bintray URL
* Add appium-url bintray to CLOUD tests
* Only test 11.3 for now because it's the only one that works... once it's fixed we can add the others
* We should also make use of 'mocha-parallel-tests' once we get the tests passing.... using parallel means we can run on _several_ Simulators instead of just one
(cc: @vrunoa)
> Use bintray staging for Sauce EmuSim

- test/functional/basic/gesture-e2e-specs.js
* iPhone X control center doesn't swipe down from the top center
* Instead, select the "Cellular" icon and swipe down from that
(related to: https://github.com/appium/appium/issues/11363)
> Make control center view test work for iPhone X

- lib/commands/file-movement.js
This PR depends on https://github.com/appium/node-simctl/pull/57
>  Add a possibility to set container type for Simulator

- lib/commands/element.js
- lib/commands/gesture.js
- test/unit/commands/element-specs.js
Fix https://github.com/appium/appium/issues/11427#issuecomment-427777847
This module has no `getElementRect` command, but it has `getRect`. The former command is called when `/element_id/rect` is called.
We must transfer the getElementRec to getRect since the `getRect` has fix in https://github.com/appium/appium-xcuitest-driver/pull/782/files . => https://github.com/appium/appium-xcuitest-driver/pull/799/commits/296df5f7f3f5c83cbfa748cad425b648ebebbbd3
BTW, can we replace `getRect` with `getElementRect`? (I'll add this change later)  => https://github.com/appium/appium-xcuitest-driver/pull/799/commits/338373b9148d868a770374b357fb5749f1f27934
```
$ git grep "getRect"
lib/commands/element.js:  return await this.getRect(el);
lib/commands/element.js:commands.getRect = async function (el) { …
```
> add .getElementRec transfer to getRect

- lib/driver.js
- test/functional/driver/motion-e2e-specs.js
And see if the test needs the retries anymore.
Without this the sim _always_ crashes while waiting to boot. And we add yet another sim boot to the startup flow.
> Add await to reduce motion call

- lib/commands/biometric.js
- lib/commands/execute.js
- lib/commands/general.js
- lib/commands/index.js
- lib/commands/keychains.js
- package.json
- test/unit/commands/general-specs.js
The PR adds `mobile` endpoints for new Simulator features that were added into https://github.com/appium/appium-ios-simulator/pull/186
> Add mobile endpoints for new Simulator features

- lib/driver.js
- Reduce warning messages like `[BaseDriver] Didn't know about setting 'mjpegServerScreenshotQuality'. Are you sure you spelled it correctly? ` for `mjpegServerScreenshotQuality` and `mjpegServerFramerate`
- Add `opts` of `mjpegServerScreenshotQuality` and `mjpegServerFramerate` like other settings
```
[HTTP] {"settings":{"mjpegServerScreenshotQuality":10,"mjpegServerFramerate":1}}
[debug] [W3C (4e529818)] Calling AppiumDriver.updateSettings() with args: [{"mjpegServerScreenshotQuality":10,"mjpegServerFramerate":1},"4e529818-8d0b-4ee8-beb5-8a817217ce85"]
[debug] [XCUITest] Executing command 'updateSettings'
[BaseDriver] Didn't know about setting 'mjpegServerScreenshotQuality'. Are you sure you spelled it correctly? Proceeding anyway. Valid settings: …
```
> add mjpegServerScreenshotQuality and mjpegServerFramerate

- lib/commands/alert.js
These just end up as `[object Object]` (see, for instance, https://travis-ci.org/appium/appium-xcuitest-driver/jobs/452639858#L558). All the information is in the exception class anyway.
> Remove description from no alert error

- README.md
- lib/commands/execute.js
- lib/commands/permissions.js
- lib/desired-caps.js
- lib/driver.js
- package.json
Changing app permissions in runtime terminates WDA session, so it is necessary to do that before WDA is initialized.
See https://github.com/appium/appium-ios-simulator/issues/189 for more details
> Set permissions before starting WDA

- lib/driver.js
Move the udid check for sims to after the check for real devices. This allows a real device test to work without having any simctl calls.
> Move check for existent sim

- lib/commands/recordscreen.js
Addresses https://github.com/appium/appium/issues/11677
> Make video codec and scale configurable

- lib/commands/execute.js
- lib/commands/general.js
Based on https://github.com/appium/WebDriverAgent/pull/129
> Add mobile: command for siri client

- lib/driver.js
- package.json
This should address the situation when `clearSystemFiles` cap is set to true and the given application path is a relative path rather than absolute. As the result the driver was going to delete the app on session removal, since `isAppTemporary` was set to true, because `originalAppPath` (relative path) was different from `this.opts.app` (absolute path, rewritten by `configureApp`). Now this should not happen, because `isSameDestination` can detect that two paths are pointing to the same file even if they are not equal as strings.
> Fix temporary app detection

- .travis.yml
- ci/mpt-fix.js
- gulpfile.js
Move the functionality to `gulp` so it can be easily ported over to `appium-gulp-plugins` and be available to other packages once our CI is implemented there.
> Move mocha-parallel-tests fix to gulp

- lib/desired-caps.js
- lib/driver.js
- lib/simulator-management.js
- test/functional/driver/driver-e2e-specs.js
- test/unit/simulator-management-specs.js
If the system on which Appium is being run has no simulator with the required platform version and name, Appium will create one, and then delete it at the end of the session. If there is a simulator, though, it will just use it, which can cause problems (see https://github.com/appium/appium/issues/12025). 
This PR introduces a capability, `useNewSimulator`, which will force the use of a new sim if no UDID is specified in the caps.
> Add `enforceFreshSimulatorCreation` capability

- lib/driver.js
- package.json
Greenkeeper seems to not catch major releases.
> Update appium-ios-driver to 4.0.0

- README.md
- lib/desired-caps.js
- lib/driver.js
- test/unit/driver-specs.js
https://github.com/appium/appium/issues/12203#issuecomment-466308545
cc @jumois
I ensured below:
```
@@driver.logs.get :syslog # worked if `skipLogCapture` is false or undefined
@@driver.logs.get :syslog # raised an error if `skipLogCapture` is true <= expected error
```
`showIOSLog` appears on appium console at the same time
> add skipLogCapture

- lib/desired-caps.js
Cap constraint moved to `appium-ios-driver` (https://github.com/appium/appium-ios-driver/pull/358)
> Remove webkitDebugProxyPort constraint, in favor of appium-ios-driver

- lib/wda/xcodebuild.js
Currently, we cannot see any error message when xcode build failed when `--log-level=warn` for example.
In this case, users can know the xcodebuild failed with ` xcodebuild failure: "xcodebuild failed with code 65"`, but not sure the cause. They must chnage log level.
Currently, we already show some lines the cause of xcodebuild as `info`. But users need them to understand the failing cause. For example, `65` error by signing issue. As below, we can see the cause message if we change the log level. (I can see this 65 issue frequesntly in our issue as well. I hope users can see them even if they set loglevel as warn or error and resolve them by themselves, hopefully.)
What do you think?
---
- current (`--log-level=warn`)
```
[BaseDriver] The following capabilities were provided, but are …
```
> tweak xcode log level when build failed

- .travis.yml
`mocha-parallel-tests` doesn't currently support `mocha@6`. This PR makes it install `mocha@5` on cron builds until it does.
> fix: use mocha 5 for mocha-parallel

- lib/wda/xcodebuild.js
Returns xcodebuild error in error message to client. The message is in `message` and `stacktrace` in W3C error format.
Users can see WDA build error as client side message. I hope this helps users to take a look signing issue (for example).
- in Ruby client (Below is a combination of an error message and stacktrace)
```
Selenium::WebDriver::Error::UnknownError:         Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65
xcodebuild error message:
2019-03-08 22:54:50.731 xcodebuild[54467:791590] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such …
```
> return xcodebuild error message to client

- lib/driver.js
tiny changes.
Currently, xcode version only appears as debug level.
We can set an arbitrary xcode version like `DEVELOPER_DIR=/Applications/Xcode_941.app/Contents/Developer appium` to use it in Appium process.
In the case, we can determin the xcode version via `ps` & `grep` for example, but it is helpful to show current xcode version as a part of Appium log as info level.
(I would like to know it in non-debug level)
> make loglevel about xcode env to info

- .travis.yml
We cannot have comments in bash blocks, in the Travis config, as this is invalid YAML. This is why builds are not running on master right now.
> Remove comment from bash block in travis config

- docs/cloud-testing.md
* Duplicate `mocha`
* Use npx so it's the installed version and not global mocha
> docs: fix typo

- .gitignore
- azure-pipelines.yml
- ci/ios-e2e-template.yml
- ci/xcuitest-e2e-template.yml
- package.json
I got Azure Pipelines working for XCUITestDriver too!
It runs on Xcode 10.1, iOS 12.1.... the tests all take under 25 minutes: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=1001
The hosted Mac agents also have Xcode betas installed, so in the future when betas are released, we can test them on CI. Not sure how quickly the betas are added to the agents though.
> Azure Pipelines for XCUITestDriver

- lib/commands/recordscreen.js
This change adds a new option `pixelFormat`, which when set to `yuv420p` along with `videoType: 'libx264'` allows the resulting video files to be played back in Apple Quicktime and therefore in Finder Quick Look.
> Record screen command: Quicktime compatibility via pixelFormat: 'yuv420p'

- lib/driver.js
The default value for `screenshotQuality` is 1, but 0 is also a valid value. Previously, it was just ignored.
> Properly forward `screenshotQuality` to WebDriverAgent.

- lib/wda/webdriveragent.js
- test/unit/webdriveragent-specs.js
Fix https://github.com/appium/appium/issues/12259
Based on current behaviour in re-use WDA is below. Try to call `[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'` even if Appium already ensured the response like `Got response with status 200`.
```
debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.1.4\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n …
```
> return current status to ensure appium uses cached WDA

- lib/wda/xcodebuild.js
`COMPILER_INDEX_STORE_ENABLE=NO` slightly reduces build time, maybe.
With the option, clang does not generate `/Index/DataStore` like `-index-store-path /Users/kazuaki/GitHub/WebDriverAgent/tmp/Index/DataStore`.
According to https://twitter.com/steipete/status/1100404024224804871 , it could reduce build time in Travis for example.
https://reviews.llvm.org/D39050
I tested with below command on my locale, I could not observe any differences between with the potion and no the option, tho. But mine was SSD + MacBook Pro. Machine spec is much better than Travis.
> $ time xcodebuild  build-for-testing test-without-building -derivedDataPath ./tmp -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -sdk iphonesimulator -destination id=ECEDA200-9325-4E7A-9AF8-E63A2903E5A9 …
> Add COMPILER_INDEX_STORE_ENABLE=NO when xcodebuild runs

- lib/commands/file-movement.js
- lib/commands/navigation.js
- lib/driver.js
- lib/utils.js
Previously the platformVersion cap could be ignored for real devices, even though such behaviour is not quite correct. For now I will just keep TODOs there to not break the backward compatibility completely.
> Select safe options by default if platformVersion is not set in caps to keep the backward compatibility

- lib/commands/element.js
- lib/driver.js
- test/functional/web/safari-nativewebtap-e2e-specs.js
Rather than use our web technology to open the URL, use simctl so it can happen before we listen to the Web Inspector.
> Use simctl openUrl for 12.2 sims safari tests

- lib/driver.js
- lib/wda/webdriveragent.js
- lib/wda/xcodebuild.js
If one explicitly sets the showXcodeLog to false then it makes sense not to show any logs even if they contain error messages. Related to https://github.com/appium/appium/issues/12466
> Avoid showing Xcode logs if showXcodeLog is explicitly set to false

- lib/ios-deploy.js
Would like to show cmd here as debug messages since it helps users when they would like to ensure if the bundle id is in their test devices as debugging. (Since the check logic deffers in both simulator and real device)
```
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1554533069969 (15:44:29 GMT+0900 (Japan Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 242bfcc998fd156df0bd0ad1dde8ab8e0a032114 --bundle_id com.kazucocoa.apple-samplecode.UICatalog'.
[debug] [XCUITest] Stdout: '[....] Waiting for iOS device to be connected
[debug] [XCUITest] [....] Using 242bfcc998fd156df0bd0ad1dde8ab8e0a032114 (N69uAP, iPhone SE, …
```
> show ios deploy command and the stdout

- lib/commands/recordscreen.js
- lib/wda/iproxy.js
- package.json
This PR adds more advanced checks for ffmpeg and iproxy startup verification
> Speed up iproxy and ffmpeg startup

- lib/driver.js
I find this verification not very precise. Also, a test will fail anyway if matching SDK cannot be found.
Addresses https://github.com/appium/appium/issues/12504
> Remove SDK version verification

- lib/driver.js
- lib/wda/utils.js
- lib/wda/webdriveragent.js
Currently we always block WDA session startup for parallel sessions, although it would be faster to let the stuff be running in parallel if a unique derivedDataPath cap is set for each instance.
>  Do not block WDA initialization if a unique derived data path is set for each instance

- README.md
- lib/commands/recordscreen.js
- lib/desired-caps.js
- lib/driver.js
- lib/utils.js
- lib/wda/webdriveragent.js
- test/unit/utils-specs.js
- test/unit/webdriveragent-specs.js
We have `webDriverAgentUrl` to customise WDA URL. But it skips installing and listening WDA starting status. I would like to listen to the customised URL instead of `WDA_BASE_URL` to be able to deploy and start WDA via WiFi.
Below is with `wdaCustomBaseURL = "http://192.168.1.100"` case. It affects only `WDA_BASE_URL`. This is necessary to listen WDA on Apple TV 4K (wireless) for example.
I could send basic commands to the WDA after below session creation command.
```
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.100","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://192.168.1.100:8100/status] with no body
[WD Proxy] Got an …
```
> customisable WDA URL

- lib/commands/execute.js
- lib/commands/general.js
I would like to include this in the next initial tvOS support. cc @dpgraham 
On tvOS, _get active element_ does not work. Users cannot get a current focused element after `@driver.execute_script 'mobile: pressButton', { name: 'Up' }` for now if we do not provide _get focused element_ logic
https://github.com/appium/WebDriverAgent/pull/151/files#diff-1ce9f4bcc55f2133845eab148e127364R51
example:
```ruby
> @driver.execute_script 'mobile: pressButton', { name: 'Home' }
> e = @driver.execute_script 'mobile: getFocusedElement'
> e.label #=> "Settings"
```
> add get a focused element as get active element method

- lib/driver.js
- lib/utils.js
It turns out we only needed to get CLT version for logging purposes and the variable was not used anywhere else, so I removed it for good
> Do not retrieve xcode command line tools version

- lib/driver.js
- lib/simulator-management.js
It makes sense to shutdown simulator completely (along with xcodebuild) instead of just terminating the app under test if one wants reset on session deletion.
> Enforce Simulator shutdown if resetOnSessionStartOnly is set to false

- lib/commands/context.js
- lib/driver.js
Override `appium-ios-driver`'s `getLatestWebviewContextForTitle` function, to remove the various conditions. This makes it possible to find Safari contexts when `webDriverAgentUrl` is set, in which case there is no iOS SDK version set.
Diff, when compared to `appium-ios-driver` version:
```diff
extensions.getLatestWebviewContextForTitle = async function getLatestWebviewContextForTitle (regExp) {
-  let contexts = await this.getContextsAndViews();
+  const contexts = await this.getContextsAndViews();
let matchingCtx;
-  for (let ctx of contexts) {
+  for (const ctx of contexts) {
if (ctx.view && ((ctx.view.title && ctx.view.title.match(regExp)) || (ctx.view.url && ctx.view.url.match(regExp)))) {
-      if (ctx.view.url !== 'about:blank') {
-        matchingCtx = ctx;
-      } else {
- …
```
> Override getLatestWebviewContextForTitle

- lib/commands/navigation.js
- lib/driver.js
- lib/utils.js
- package.json
If the `platformVersion` is not provided in caps then we will try to determine its value by querying ideviceinfo output for real devices and using the latest available SDK for simulators. In case these fail or an incorrect (e .g. semver-unparseable) version string has been provided then an exception is thrown. Also, the calculated or provided value is normalised to only include the major and minor number and ignore the patch number.
@umutuzgur FYI
> Make platformVersion a required capability

- lib/commands/web.js
When trying to native web tap on an an element with the same text as another it will always try to select the first element regardless of visibility.
Here's a quick example webpage:
```
<html>
<body>
<div>
<button style="position: absolute;">larger</button>
<a>link</a>
</div>
<a href="about:blank">link</a>
</body>
</html>
```
This page has 2 identical links (the href can be omitted) but `tapWebElementNatively()` will first try to match the text and search for an accessibility id with that text. The problem is that the first link, which is hidden by the button, isn't the one we want to tap on yet it is the one returned by the driver.
Here is the response of:
```
const el = await driver.findNativeElementOrElements('accessibility id', text, false);
```
```
[WD Proxy] Proxying [POST /element] …
```
> Only native tap if there is one matching element

- lib/wda/webdriveragent.js
Setting WebDriverAgent connections to remain alive as long as they are being used
> Setting WebDriverAgent connections to remain alive

- lib/commands/web.js
Added extra calculation so that iPhone XR's and XS Max's are considered iPhone X's. The `IPHONE_X_NOTCH_OFFSET` should still be the same on larger devices.
> Added calculation for large iPhone X's.

- lib/commands/certificate.js
Removed Sheet.Install in favour of using a visible check for the button. This is because on iPad the button is within an Alert not within a sheet. Thus making the certificate unable to be installed on iPad.
> Changed default Install button to only select the visible one

- lib/driver.js
- package.json
Now ios-simulator support idb, so lets make usage of it. In the future we could also assign idb to a driver property and use it there if necessary.
> Initialize idb and pass it to iOS Simulator

- lib/simulator-management.js
It looks like simctl might also throw error with codes different from 35. See https://github.com/appium/appium/issues/10464?issuecomment-496517286
> Always restore installd cache if simctl error output includes MIInstallerErrorDomain

- lib/commands/file-movement.js
- test/unit/commands/file-movement-specs.js
for https://github.com/appium/appium/issues/12283#issuecomment-497384996
I would like to put a couple of examples as documentation in https://github.com/appium/appium/tree/master/docs/en
summary:
- `--container` can work if the target app has UIFileSharingEnabled flag
- `--documents` can work without the flag
- Thus, I tried to mount by `--documents` if the provided `remotePath` starts with `Documents` after the bundle id
- The mounted target on iPhone is in _On My Phone/app name_ in Files app
I tested they worked with https://github.com/appium/ruby_lib_core/pull/216/files for real device
> Fix pull/push for real device via ifuse using `documents` flag

- lib/driver.js
We shouldn't kill iproxy instances if webDriverAgentUrl is passed as there would be an iproxy instance already running to connect to the WDA
> Don't cleanupObsoleteProcesses if webDriverAgentUrl is passed

- lib/driver.js
- lib/utils.js
- lib/wda/xcodebuild.js
Add parameter to `verifyApplicationPlatform` so that tvos builds can be recognized when appropriate.
Also add another expected log line to the list.
> Add tv check to verifyApplicationPlatform

- .travis.yml
As we no longer have a submodule, Travis no longer needs to accommodate one.
> Remove submodule stuff from Travis config

- lib/driver.js
If the file specified by `app` caps exists but its format is wrong (due to zip operation mistake etc), currently the error message is like `An unknown server-side error occurred while processing the command. Original error: Bad app: ***. App paths need to be absolute or an URL to a compressed app file` And if you check Appium log, you can see `App zip unzipped OK, but we could not find .app bundle(s) in it. Make sure your archive contains .app package(s) and nothing else`.
But I think if the error message itself also contains the detailed cause like `...we could not find .app bundle(s) in it..`, the user debug will be much easier (at least for me).
> Improve bad app error messgae

- lib/wda/webdriveragent.js
- test/unit/wda/webdriveragent-specs.js
https://github.com/appium/appium/issues/12836
@dpgraham 
What about skipping the checking process if `usePrebuiltWDA` is enabled?
In the case, we do not need to check WDA dependencies. So, simply skip it.
Will add test later if this works well
> Skip checking wda dependencies when usePrebuiltWDA is enabled

- lib/wda/webdriveragent.js
After https://github.com/appium/appium-xcuitest-driver/pull/980/files , `checkForDependencies` has been moved to WDA script,  https://github.com/appium/WebDriverAgent/blob/master/index.js#L114-L116.
Then, the argument has been an object, and it uses `opt.useSsl`.
(if we need `bootstrapPath`, we should close this PR and update `checkForDependencies` in WDA side.)
> update checkForDependencies arguments to follow the new WDA

- lib/commands/recordscreen.js
- lib/wda/iproxy.js
- lib/wda/webdriveragent.js
- package.json
Remove iproxy and use a native implementation for port forwarding
> feat: remove using iproxy

- lib/commands/performance.js
After https://github.com/appium/appium-xcuitest-driver/pull/989, performance record feature does not work for simulators. It should raise an error when the test device real devices.
(Founded in ruby lib core's [CI](https://dev.azure.com/kazucocoa/ruby_lib_core/_build/results?buildId=879))
```
=================‌00D‌RROR[&quot;test_start_performance_record_and_stop&quot;, #&lt;Minitest::Reporters::Suite:0x00007f8a472253e8 @name=&quot;AppiumLibCoreTest::Ios::DeviceTest&quot;&gt;, 443.211323]‌
test_start_performance_record_and_stop#AppiumLibCoreTest::Ios::DeviceTest (443.21s)
Selenium::WebDriver::Error::UnknownError:         Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Performance measurement is for simulators …
```
> fix: the control flow of perf record

- lib/commands/deviceInfo.js
- lib/commands/execute.js
- lib/commands/index.js
- test/unit/commands/deviceinfo-specs.js
Added `deviceInfo` mobile command like `batteryInfo` command. http://appium.io/docs/en/commands/mobile-command/
It returns device condition like current locale, timezone.
```ruby
@driver.execute_script 'mobile: deviceInfo', {}
=> {"locale"=>"en_US", "timeZone"=>"Asia/Tokyo"}
```
The command returns timezone and locale after https://github.com/appium/WebDriverAgent/commit/3cf6e3309baa38f8018534986729444000b5e08f 
WDA can work independently, e.g. webDriverAgentUrl, so nothing returns if locale or timezone do not in the response.
---
I noticed android UIA2 and Espresso drivers have the same name command.
Will add locale and timezone in them for android.
> feat: add getting deviceInfo mobile command

- lib/driver.js
- lib/simulator-management.js
- test/unit/simulator-management-specs.js
**[update]**
We implemented this way, uninstall everytime without noReset, because of untrusted clearing local data in simulator.
We'd like to avoid reminding unexpected previous data even if Appium called scrub method.
So, I changed to just adding test cases here.
---
related to https://github.com/appium/appium/issues/12873 
According to the issue, we previously did not require `app` as fastReset (default).
(Simulator scope. Not for real devices)
Current logic to clear local data is:
1. check `opts.app` => if it exists, return (not clean the simulator data)
2. If the app does not exist => `path.basename(opts.app)` raises an error => not clean the simulator data
So, in this PR, I changed to call `scrubCustomApp` instead of uninstalling the app every time (except for noReset is true) for …
> test: add tests for runSimulatorReset in order to clarify the behaviour

- README.md
- lib/desired-caps.js
- lib/driver.js
- package.json
- test/functional/desired.js
- test/functional/driver/otherApps-e2e-specs.js
- test/unit/driver-specs.js
[work in progress]
Something that came up in appium conf is giving support for otherApps capability on iOS. Gonna add a functional test to make sure it works.
> Add support other apps ios

- lib/simulator-management.js
- test/functional/driver/driver-e2e-specs.js
Small change to the reset logic (given the check on line 119, there is no way that `opts.app` evaluates as truthy, so there is no need to recheck it).
With the change in https://github.com/appium/appium-xcuitest-driver/pull/1004 the driver tests when only bundleId is set continued to work, but with an added ~4 minutes to the run because of the error:
```
dbug WD Proxy Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.example.apple-samplecode.UICatalog","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":30,"shouldUseSingletonTestManager":true}}
ERR! Xcode 2019-07-12 14:33:38.575419+0000 …
```
> tests: Add noReset=true to driver bundleId tests

- lib/commands/file-movement.js
- lib/ios-deploy.js
fixes https://github.com/appium/appium/issues/12981
> feat: get only user apps in file-movement for performance aspect, add comments

- lib/driver.js
Fix https://github.com/appium/appium/issues/12968
WDA handles get active element as "GET" which is W3C spec. MJSONWP case the method is "POST".
xcuitest-driver has the proxy so MJSONWP case the request should be handled by xcuitest-driver.
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/general.js#L9-L14
e2e test exists, but it can work since it is W3C. (and it works fine)
fixed:
```
[HTTP] --> POST /wd/hub/session/18c36a40-d1ee-448f-a0d0-8c969b45698d/element/active
[HTTP] {}
[debug] [MJSONWP (18c36a40)] Calling AppiumDriver.active() with args: ["18c36a40-d1ee-448f-a0d0-8c969b45698d"]
[debug] [XCUITest] Executing command 'active'
[debug] [WD Proxy] Matched '/element/active' to command name 'active'
[debug] [WD Proxy] Proxying [GET /element/active] to [GET …
```
> fix: get active element should proxy

- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/find-e2e-specs.js
- test/functional/driver/driver-e2e-specs.js
- test/functional/driver/motion-e2e-specs.js
- test/functional/driver/otherApps-e2e-specs.js
- test/functional/driver/webdriveragent-derived-data-path-e2e-specs.js
- test/functional/helpers/session.js
- test/functional/helpers/simulator.js
- test/functional/tv/tvos-e2e-specs.js
- test/functional/web/safari-basic-e2e-specs.js
- test/functional/web/safari-nativewebtap-e2e-specs.js
Two things:
- remove most of our implicit wait usage
- consolidate the five separate-but-identical definitions of `deleteDeviceWithRetry`.
> refactor: clean up tests

- lib/commands/element.js
- lib/commands/general.js
Before:
```
info HTTP --> POST /wd/hub/session/2e5c2452-7e6b-46c0-96e7-3e31a58dce81/appium/device/hide_keyboard
info HTTP {}
dbug MJSONWP (2e5c2452) Calling XCUITestDriver.hideKeyboard() with args: [null,null,null,null,"2e5c2452-7e6b-46c0-96e7-3e31a58dce81"]
dbug XCUITest Executing command 'hideKeyboard'
dbug BaseDriver Waiting up to 0 ms for condition
dbug WD Proxy Matched '/element' to command name 'findElement'
dbug WD Proxy Proxying [POST /element] to [POST http://localhost:8100/session/FD20A0A8-EDAD-42DD-824B-A09301810C9B/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
dbug WD Proxy Got response with status 200: {"value":{"ELEMENT":"D0000000-0000-0000-FA5E-000000000000"},"sessionId":"FD20A0A8-EDAD-42DD-824B-A09301810C9B","status":0}
dbug XCUITest Finding …
```
> Fix handling of attribute when hiding keyboard

- lib/commands/activeAppInfo.js
- lib/commands/deviceInfo.js
- lib/commands/execute.js
- lib/commands/index.js
- test/unit/commands/activeAppInfo-specs.js
https://github.com/appium/WebDriverAgent/pull/194/files
```
> @@driver.execute_script('mobile: activeAppInfo', {})
=> {"processArguments"=>{"env"=>{"HAPPY"=>"testing"}, "args"=>["happy", "tseting"]}, "name"=>"", "pid"=>505, "bundleId"=>"com.apple.mobilesafari"}
```
`/wda/activeAppInfo` isn't new endpoint
> feat: add activeAppInfo

- README.md
- lib/driver.js
Please do not merge before https://github.com/appium/WebDriverAgent/pull/195 is published
> Fix the behaviour of autoLaunch capability

- lib/commands/context.js
Currently, https://github.com/appium/appium-remote-debugger/blob/b8f5be6bd0fe9577c0f3ca54eac595a049e7aaaa/lib/remote-debugger.js#L324 is rased when we run below scenario.
1. Open an ios-uicatalog app
2. Call `available contexts` command
- Get `NATIVE_APP` 🆗 
3. Open `Web View` cell
- open webview
4. call `available contexts` command
- Get `NATIVE_APP` and `WEBVIEW_xxxx` 🆗 
5. Back
- No webview page
6. call `available contexts` command
- https://github.com/appium/appium-remote-debugger/blob/b8f5be6bd0fe9577c0f3ca54eac595a049e7aaaa/lib/remote-debugger.js#L324 is raised
This is because we do not handle the error in xcuitest layer.
The error means we have no available webview. So, I think we can make the result `[]`
In this PR, I handle the error as try/catch in xcuitest layer, but I also …
> fix: catching error when no available web pages

- lib/commands/web.js
We only get the webview if it exists and it's visible but in some cases the webview will not be determined visible by the driver. As seen here I try to locate the webview with both strategies but only the one where I don't specify if it is visible actually returns an element.
```
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:4823/session/D16313A4-7D07-449D-904F-EF563AA85853/element] with body: {"using":"predicate string","value":"type = 'XCUIElementTypeWebView'"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"26000000-0000-0000-0C3B-000000000000"},"sessionId":"D16313A4-7D07-449D-904F-EF563AA85853","status":0}
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD …
```
> Remove visibility check from webview.

- lib/commands/screenshots.js
So, a typo here prevented screenshots from being returned from the mjpegstream.
Here's something interesting though, fixing this caused screenshots on my machine to go from taking ~172ms each to taking ~436ms. So by fixing this, screenshots are actually _less_ performant on iOS.
> fix mjpegstream logic for returning screenshots

- lib/wda/webdriveragent.js
Currently, we can port forward only to 8100 on a real device. Here can be `this.wdaLocalPort` as same as simulators. (I could not remember why `wdaRemotePort` was only `WDA_AGENT_PORT` for real device though...)
If a user set both `wdaLocalPort` and `wdaBaseUrl`, appium can send WDA via xcodebuild port forwarding to `wdaLocalPort` and it can communicate with WDA via `wdaBaseUrl:wdaLocalPort`. Then, Appium can re-use running WDA on the device regardless of xcodebuild's port condition since Appium communicate with WDA via `wdaBaseUrl:wdaLocalPort`.
The combination can avoid https://github.com/appium/appium/issues/13127 port issue.
I tested on a real device and a simulator with below configurations. Ran `driver.start_driver` twice and `driver.start_driver => driver.quite => …
> feat: make this.wdaRemotePort configuarable

- lib/driver.js
The returned result might be undefined, so we need to make sure first that it can be passed to `path.normalize`
> fix: Perform validation of retrieved derived data path

- README.md
- lib/commands/context.js
- lib/desired-caps.js
- package.json
Add a cap `includeSafariInWebviews` which signals to the remote debugger to add safari apps to the available list.
I would go for making this default to `true` but that would be a breaking change.
> feat: add includeSafariInWebviews cap

- lib/commands/general.js
- test/unit/commands/general-specs.js
I would like to keep the approach where `seconds` argument is passed to this endpoint like in Android to avoid unnecessary confusion for different clients.
The final rules will be:
- seconds value can be float
- if seconds value is greater or equal to zero then the app is minimized and restored after the timeout
- if seconds less than zero or null then home screen is shown
> chore: Refactor the background endpoint implementation

- lib/driver.js
- package.json
- test/unit/driver-specs.js
related to https://github.com/appium/WebDriverAgent/pull/202
Before:
- Can configure the setting only when before launching simulators (It requires to reset simulator)
After:
- Can change the setting without closing simulator
> feat: switch reduce motion via settings API

- lib/driver.js
Addresses https://github.com/appium/appium/issues/13233
> fix: Add GET /timeouts to the list of non-proxied urls

- lib/ios-generic-simulators.js
- lib/utils.js
- test/unit/utils-specs.js
What this pull request does
* Bumps up the default device for the generic `iphone simulator` for iOS 13+ from `iPhone 6` to `iPhone X`
_WHY?_: `iOS 13` does not support `iPhone 6` so this needs to be changed. Chose `iPhone X` over `iPhone 11` because it's not quite the latest and not bleeding edge.
* Refactored logic so that the default generic versions are specified in a plain Javascript object in `ios-generic-simulators.js`
_WHY?_: So we're not hardcoding this in code. We just need to keep this file (and the tests) up-to-date
> feat: bump generic iPhone for iOS 13.0

- lib/ios-deploy.js
Fix timeout error when installing new app (wrong order of arguments for `.timeout()`)
Probably related to appium/appium#13180 and appium/appium#13218
> Fix use of timeout in pushAppBundle

- lib/ios-generic-simulators.js
- test/unit/utils-specs.js
Set it to `iPad (5th generation)` (`iPad Air` is not supported)
> fix: Bump min iPad for 13.0

- ci-jobs/nightly-build.yml
- ci-jobs/sauce-build.yml
- ci-jobs/templates/ios-e2e-template.yml
- ci-jobs/templates/xcuitest-e2e-template.yml
- test/functional/basic/basic-e2e-specs.js
- test/functional/device/otherApps-e2e-specs.js
- test/functional/driver/driver-e2e-specs.js
- test/functional/driver/protocol-e2e-specs.js
- test/functional/driver/webdriveragent-derived-data-path-e2e-specs.js
- test/functional/driver/webdriveragent-e2e-specs.js
* Separate Sauce and Nightly into separate YML because Sauce is flakey and requires the uploaded  Appium bundle which limits its use-cases to only nightly
* Update the trigger (from the Azure interface, not reflected here) to run both `nightly` and on `refs/tags/*`... whenever a new Appium XCUITest Driver tag is published, these tests will run.
Next steps:
> Fix Azure nightly builds [1 of n]

- ci-jobs/templates/ios-e2e-template.yml
- ci-jobs/templates/xcuitest-e2e-template.yml
- lib/desired-caps.js
- lib/driver.js
- lib/utils.js
- lib/wda/webdriveragent.js
- test/functional/desired.js
Experimental idb support. idb currently doesn't work with xcode 11 and azure. It needs further investigation but it should be okay to merge it since it is just an alternative to xcodebuild and doesn't break the old logic
> feat: use idb instead of xcodebuild

- lib/simulator-management.js
It looks like after Xcode 9 Apple has fixed the cache overgrow issue after multiple apps install, so we can now remove the workaround.
> chore: Do not perform simulator cache cleanup for Xcode 10+

- lib/driver.js
- lib/ios-deploy.js
Easy enough to get the platform version from the device using `appium-ios-device`.
> fix: add getPlatformVersion to ios-deploy object

- test/functional/web/safari-execute-e2e-specs.js
- test/functional/web/safari-nativewebtap-e2e-specs.js
Since changing the asynchronous execute implementation to use promises on the device, the functionality has been available to real devices.
> tests: run async execute tests on real devices

- README.md
- lib/commands/log.js
- lib/desired-caps.js
- lib/device-log/ios-simulator-log.js
- test/functional/basic/gesture-e2e-specs.js
- test/unit/log-specs.js
* Add capability `iosSimulatorLogsPredicate` which is a string that gets added on as a flag to the `xcrun simctl spawn <udid> log...` sub-process as `--predicate <predicate>`
* Updated IosSimulatorLog class to include this as an option
* Added a unit test for IosSimulatorLog
Reasoning:
Logging when upgrading to Xcode 11 has become extemely verbose and we need a way to reduce the verbosity so that 1. logs are easier to make sense of 2. we don't deal with memory issues due to huge log files
Other:
* Removed xcodeVersion property because it wasn't being used
Note:
* The `XCUITestDriver - startLogCapture` tests weren't changed, they were just moved into another nested describe block and that's why the diff is so noisy
Related issues:
* https://github.com/appium/appium/issues/13366
* …
> feat: Add "iosSimulatorLogsPredicate" capability

- lib/commands/certificate.js
- lib/driver.js
This feature has been already added to WDA. Now it's driver's turn
> fix: Update capabilities verification logic to allow WDA execution without app under test

- package.json
@mykola-mokhnach this is the kind of thing all the drivers will need to do in order to advertise their details to the appium 2 server.
> chore: add Appium 2.0 compatible metadata

- lib/commands/execute.js
- lib/commands/file-movement.js
- test/functional/device/file-movement-e2e-specs.js
Adds functions (`mobile: deleteFile` and `mobile: deleteFolder`) to remove files/folders from the device or simulator.
Locally this has been tested with an iPhone 7 Plus running iOS 13.1 with
```js
describe('keynote', function () {
const caps = {
bundleId: 'com.apple.Keynote',
platformName: 'iOS',
platformVersion: '13.1',
automationName: 'XCUITest',
udid: 'auto',
app: null,
browserName: null,
}
let driver;
before(async function () {
driver = await initSession(caps);
});
after(async function () {
await deleteSession();
});
it('should push a file', async function () {
const stringData = `random string data ${Math.random()}`;
const base64Data = Buffer.from(stringData).toString('base64');
const remotePath = '@com.apple.Keynote:documents/higher.txt';
await driver.pushFile(remotePath, …
```
> feat: add execute commands for removing files

- lib/ios-deploy.js
It seems like there are still some cases where `ios-device` caanot handle app installation properly but `ios-deploy` can. So, we can make the flow more flexible
> feat: Fallback to ios-deploy usage if ios-device lib fails to install the app bundle

- lib/device-connections-factory.js
- lib/driver.js
- test/unit/device-connections-factory-specs.js
Hopefully addresses https://github.com/appium/appium/issues/13452
> fix: Make sure ports are closed properly after the cleanup

- lib/device-connections-factory.js
We currently only listening to errors right after server startup or after we close it, although it makes sense to do that during the whole server life cycle.
> fix: Listen to socket server errors after its startup

- lib/commands/context.js
I found an error in ruby lib core's nightly test.
The scenario was:
1. Set web-context
2. Set context as `null` (Then, Appium should set the context as native)
Then, the `name` was `null` and `replace` failed.
Previous implementation (before https://github.com/appium/appium-xcuitest-driver/pull/1105) avoided this error by `if (isNativeContext(name)) {` in the next line.
https://dev.azure.com/kazucocoa/ruby_lib_core/_build/results?buildId=1425&view=logs&j=b357693d-6cc3-5f61-d7af-e4ebe11dce24&t=25c282ea-11ac-5a8c-6a63-157c06b57748
```
[HTTP] --> POST /wd/hub/session/0f2307fb-bfb5-49c0-a168-5e72e545fbc5/context
[HTTP] {"name":null}
[debug] [W3C (0f2307fb)] Calling AppiumDriver.setContext() with args: [null,"0f2307fb-bfb5-49c0-a168-5e72e545fbc5"]
[debug] [XCUITest] Executing command …
```
> fix: 'null' replace error when the context changes from web to null (native)

- test/functional/web/helpers.js
- test/functional/web/safari-basic-e2e-specs.js
We started skipping these tests a while ago (starting with iOS 12.2). Change the URL to one that works better, and use the native context to check on progress.
> tests: fix safari phishing tests

- lib/commands/web.js
- package.json
- test/functional/web/helpers.js
Small change needed to handle the new `appium-remote-debugger` release, over and above what Greenkeeper is proposing.
> chore: update appium-remote-debugger

- README.md
- lib/commands/context.js
- lib/desired-caps.js
- lib/driver.js
- package.json
Pass additional webview bundle identifiers along to the remote debugger.
> feat: add additionalWebviewBundleIds capability

- lib/commands/context.js
Early initialization and connection was a holdover from an earlier version of `appium-remote-debugger` that had some problems. 
This will fix the native portion of https://github.com/appium/appium/issues/13692, though the problem with the `EPIPE` error will remain on that person's machine, in a hybrid/web test.
> fix: move remote debugger initialization to when it is used

- lib/commands/app-management.js
`confifureApp` manages the applications cache on its own. Deletion of the app on the client side might cause cache damage.
Addresses https://github.com/appium/appium/issues/13412#issuecomment-564042217
> fix: Avoid deleting an app after installation is completed

- lib/driver.js
I did the work to initialize later but missed the important step of removing the early initialization. This goes, again, toward https://github.com/appium/appium/issues/13692
> fix: whoops! did not remove the early remote debugger start

- lib/utils.js
- test/unit/utils-specs.js
I think this is more appropriate way of doing the cleanup. We cannot rely on the command line tools
> refactor: Perform temporary files cleanup using Node promises

- lib/ios-deploy.js
- package.json
While looking at the logs for a failure in this code (https://github.com/appium/appium/issues/13716) I found the output confusing. This PR rearranges some of the error output, as well as normalizes some of the style.
> refactor: clean up app install error handling

- lib/device-connections-factory.js
Not all errors thrown by remote socket are critical to us, it makes sense to print them at info level to not confuse users to much
> chore: Tune error messages and variable names for the connections factory

- lib/commands/context.js
- test/functional/basic/basic-e2e-specs.js
Add an option, `waitForWebviewMs`, to the mobile execute version of `getContexts`, which will make it blocking for that period of time. Workaround for https://github.com/appium/appium/issues/13770
> feat: add option for wait duration for mobile context list

- lib/driver.js
- lib/simulator-management.js
- test/unit/driver-specs.js
There are times when we _know_ that a simulator is new. And so we do not really need to check if our app is on it.
> refactor: do not check for app install status on new simulator

- lib/desired-caps.js
- lib/driver.js
- lib/simulator-management.js
- package.json
- test/functional/driver/driver-e2e-specs.js
- test/functional/tv/tvos-e2e-specs.js
Use the new functionality in `appium-ios-simulator` to skip the check for a sim's existence when we have just created it.
Also, when getting the simulator in `determineDevice`, there is no need to check if it exists beforehand, since that is done in the `getSimulator` function.
> refactor: do not check for existence of simulator when it is known

- lib/commands/file-movement.js
The idea is similar to https://github.com/appium/appium-xcuitest-driver/commit/366597e03cbe411730581fa49843228675764bba
> fix: Update error handling in push/pull file methods for real devices

- lib/commands/element.js
Currently WDA is much more advanced than when the previous code was written, so it handles the keyboard presence and retries on its own. Also, there was a bug in the code related to strings split. the issue was that the standard `String.split` method does not properly handle complex Unicode characters, like smiles.
> refactor: Remove the obsolete stuff from input handlers

- lib/utils.js
- test/unit/utils-specs.js
This should speed up the cleanup process
> fix: Look for temporary logs in the specific root folder instead of the whole tempdir

- lib/device-connections-factory.js
There is nothing particularly instructive in the full stack trace, and it makes the WDA startup process _very_ verbose:
```
dbug [11-47-26:657] WD Proxy Matched '/status' to command name 'getStatus'
dbug [11-47-26:658] WD Proxy Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
ERR! [11-47-26:661] iProxy@c54f3306 Error: Connection was refused to port 8100
ERR! [11-47-26:661] iProxy@c54f3306     at responseCallback (/Users/isaacmurchie/code/appium-xcuitest-driver/node_modules/appium-ios-device/lib/usbmux/index.js:212:15)
ERR! [11-47-26:661] iProxy@c54f3306     at cb (/Users/isaacmurchie/code/appium-xcuitest-driver/node_modules/appium-ios-device/lib/usbmux/index.js:133:19)
ERR! [11-47-26:661] iProxy@c54f3306     at Usbmux._handleData …
```
> fix: only print message from real device proxy connect error

- lib/commands/context.js
The latest `appium-remote-debugger` exposes the bundle id for webview apps. Add that to the data in the full context list, so clients have more information to choose the correct webview for their situation.
> fix: add bundleid to full context list

- package.json
https://github.com/appium/appium-ios-driver/pull/415
> chore: bump ios driver to 4.6.0

- lib/driver.js
- lib/utils.js
The `getPIDsUsingPattern` helper was only used by WDA, which is currently a separate module. Also resolved the TODO regarding the platform validation
> chore: Update helper functions

- lib/commands/alert.js
Small change to the structure of Safari alerts in iOS 13.4 beta. Allow for this change, and the entire Safari suite will run  successfully with 13.4.
> fix: handle safari alert for iOS 13.4

- lib/commands/web.js
Rather than going directly into checking for alerts, with a hardcoded wait, spend a second waiting for the promise to return. Then move on to checking for an alert.
> fix: wait for atom finish before checking for alerts

- lib/commands/execute.js
- lib/commands/gesture.js
- package.json
Based on https://github.com/appium/WebDriverAgent/pull/295
> feat: Add mobile command for tapWithNumberOfTaps

- lib/commands/alert.js
- test/functional/web/safari-window-e2e-specs.js
Add "Block"/"Allow" alerts to those recognized.
This should fix https://github.com/appium/appium/issues/8582 and https://github.com/appium/appium/issues/14091
> feat: allow safari alert with block/allow buttons to be handled

- lib/commands/gesture.js
- lib/commands/web.js
- lib/desired-caps.js
- lib/driver.js
- test/functional/web/safari-window-e2e-specs.js
Add a capability, `nativeWebTapStrict`, which skips the attempt to not convert the web coordinates. See https://github.com/appium/appium/issues/14084
First, this makes sure the web coordinate conversion works for newer devices.
> feat: add nativeWebTapStrict cap

- lib/commands/general.js
Moment.js assumes that unix timestamps are given in local time zone by default (o_O): https://momentjs.com/docs/#/parsing/unix-timestamp/
> fix: ensure unix timestamp is in utc

- ci-jobs/templates/ios-e2e-template.yml
- ci-jobs/templates/node-build-template.yml
- ci-jobs/templates/sauce-e2e-template.yml
- ci-jobs/templates/xcuitest-e2e-template.yml
- package.json
Remove step from _each_ functional test job, since the e2e coverage isn't collected. Add coverage generation to the unit test section. And remove superfluous build tasks, since `npm install` runs the transpilation.
Makes for a coverage pane in Azure: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9013&view=codecoverage-tab
> build: get coverage in azure

- lib/commands/web.js
Change to wait for the atom promise at the same time as checking for the alert. This also makes it so there are no dead waits... it is always short-circuited if the atom promise resolves.
> refactor: simplify wait for atoms

- README.md
- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/record-audio.js
- lib/driver.js
The idea of this PR is that we could record Simulator audio output using Soundflower like it is described in http://www.lorisware.com/blog/2012/04/28/recording-iphone-emulator-video-with-sound/
For real devices there is a possibility to connect a phone as an input device: https://www.makeuseof.com/tag/play-audio-iphone-mac/, although I've never tested that, since I don't have a real device :-P
In the worst case one could always use the classic audio jack connected to a microphone input of a mac machine.
The feature is insecure, because it allows to access system microphone, so it must be enabled explicitly on the server side.
I'll write a separate doc later on how to configure the Simulator for audio recording. It would be great if @KazuCocoa could help to check how audio capture works …
> feat: Add mobile commands for audio recording

- lib/commands/general.js
https://discuss.appium.io/t/ios-simulator-error-opening-urls-on-real-devices-is-not-supported/31025/2
> fix: Adjust setUrl call for different contexts

- lib/commands/performance.js
Since XCode the `instruments` tool is going to be deprecated and removed from developer tools. The `xctrace` is proposed as a drop-in replacement. This PR adds support of this tool and still keeps a fallback to instruments for older Xcode versions.
> feat: Use xctrace tool for performance stats recording if possible

- ci-jobs/templates/ios-e2e-template.yml
e2e_basic_idb_iPhoneX_13_4 is failing because of below error.
```
/Users/runner/work/_temp/a1cad390-6bec-40a8-b44f-d5846f9c40a6.sh: line 3: /usr/local/bin/pip3.7: No such file or directory
```
Let me try to follow https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python to specify the Python version
> ci: use UsePythonVersion

- .github/workflows/publish.js.yml
fixes https://github.com/appium/appium/issues/14732
shrinkwrap is necessary in our `appium` package regular release, but not in each separate modules, I think.
e.g. Appium 1.18.1 has shrinkwrap in the package, but not in the node_modules/appium-xcuitest-driver package
Is this removal enough?
> chore: remove shrinkwrap from package

- lib/utils.js
- test/functional/basic/gesture-e2e-specs.js
The test in gestures-e2e was using `getGenericSimulatorForIosVersion` method in `utils`; a method that is only used by `translateDeviceName` and does not have any unit tests. The test was failing because it expects lowercase deviceName which it wasn't getting so it wasn't returning the correct result.
The fix is to just use `translateDeviceName` method directly, and then make `getGenericSimulatorForIosVersion` unexported (ie: a private method).
> chore: fix broken control center test

- lib/driver.js
Changing permissions via simctl terminates/backgrounds the app under test, so we need to make sure this is done after the app is installed, but before it is started.
> chore: Make sure calendar access is assigned before app startup

- lib/commands/certificate.js
- test/unit/commands/ssl-certificate-specs.js
The separator (`/`) for the values of the output in LibreSSL (OpenSSL in MacOS/OpenBSD) is different from the separator ` , ` in OpenSSL in Linux.
**appium-xcuitest-driver** is expecting to run on macOS so the regex which parses the output from LibreSSL (OpenSSL in MacOS/OpenBSD) doesn't work when using OpenSSL.
This patch adds the fallback to parse the OpenSSL output in case it fails to parse the LibreSSL output.
> fix: parsing SSL output from OpenSSL output

- test/functional/device/performance-e2e-specs.js
Xcode 12.3 complains that Simulator does not support the default `Activity Monitor` profile. So, I've changed the profile name to make it working
> chore: Update the default profile name

- lib/driver.js
Setting it to false enforces the corresponding simulator setting to be changed every time it is started
> chore: Do not enforce trace pointer setting

- lib/commands/location.js
- package.json
- test/functional/basic/basic-e2e-specs.js
- test/unit/commands/location-specs.js
When it worked:
```ruby
driver.location
=> #<struct Selenium::WebDriver::Location latitude=55, longitude=0.72, altitude=0>
```
Against tvOS:
```ruby
> @driver.location
Selenium::WebDriver::Error::UnsupportedOperationError: unsupported
from UnsupportedOperationError: unsupported
```
> feat: support getGeoLocation (requires 'Always' in Location Services)

- docs/real-device-config.md
WebDriverAgent's bootstrap.sh script is redundant since version 2.32.0
of WebDriverAgent. It only prints to the command-line that everything is
ok. Therefore we can simplify the setup instructions by not calling this
script anymore. In addition this is a preparation for removing the
bootstrap.sh script from WebDriverAgent.
> docs: Run WDA bootstrap only for new releases 

- README.md
- lib/desired-caps.js
- lib/driver.js
- test/unit/commands/session-specs.js
For https://github.com/appium/appium/issues/15101
In some environments, it seems `/screen` endpoint takes long time to get the response in XCTest.
As a workaround for now, we can disable the call.
We can call them via an extension like `mobile:screenInfo` or existing `deviceInfo`?
> feat: add appium:includeDeviceCapsToSessionInfo to be able to ignore /screen call to WDA

- README.md
- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/notifications.js
https://betterprogramming.pub/how-to-send-push-notifications-to-the-ios-simulator-2988092ba931
> feat: Add a possibility to simulate push notifications via simctl

- README.md
- lib/commands/execute.js
- lib/commands/notifications.js
- package.json
Based on https://github.com/appium/WebDriverAgent/pull/480
> feat: Add mobile extension for the 'expectNotification' call

- README.md
- lib/desired-caps.js
- lib/driver.js
- package.json
- test/unit/language-specs.js
- test/unit/processargs-specs.js
The value of this will override WDA's default config for disabling XCTest automatic screenshot taking.
Depends on this change on WDA: https://github.com/appium/WebDriverAgent/pull/483
> feat: Add disableAutomaticScreenshots capability

- README.md
- lib/desired-caps.js
- lib/driver.js
- package.json
- test/unit/language-specs.js
- test/unit/processargs-specs.js
To specify if the app should be terminated on session end (when `bundleId` is present). The default is `true` to be consistent with the existing behaviour.
Depends on: https://github.com/appium/WebDriverAgent/pull/486
> feat: Add shouldTerminateApp capability

- README.md
It seems `alert` needs a key such as `title`
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc#2943365
> docs: tweak example in pushNotification

- ci-jobs/templates/xcuitest-e2e-template.yml
These tests are always failing because of timeouts. I don't see any value in them unless they could be fixed.
> chore: Disable IDB-related e2e tests

- README.md
- lib/commands/gesture.js
Related to https://github.com/appium/appium-uiautomator2-driver/pull/458 and https://github.com/appium/appium/issues/15392#issuecomment-844785946
> chore: Deprecate `element` in favour of `elementId`

- lib/commands/element.js
As a part of decoupling appium ios driver in https://github.com/appium/appium-xcuitest-driver/pull/1297
When the getName method was moved, toLowerCase() was missing which was originally present in [appium-ios-driver](https://github.com/appium/appium-ios-driver/blob/9755e309af6f5cbd4a895ca3f157650a943eff5b/lib/commands/element.js#L124) thus causing a parity in the behavior of some of the test scripts.
> fix: lowercase in name command

- lib/commands/web.js
The previous implementation was creating multiple getAlertRequests requests, which were unnecessarily stacked to the WDA queue and eventually killing the server. This fix prevents that from happening and makes sure we only have single alert detection request at a time.
> chore: Improve the logic for the alert checking in web context

- lib/commands/element.js
Fixes https://github.com/appium/appium/issues/15675
I found `driver.execute_script 'return [document.body.scrollLeft, document.body.scrollTop];' ` was always zero while `driver.execute_script 'return [Math.max(window.pageXOffset, document.documentElement.scrollLeft, document.body.scrollLeft), Math.max(window.pageYOffset, document.documentElement.scrollTop, document.body.scrollTop)];'` returns probably expected value.
On an iOS 15 real device,  pageXOffset and pageYOffset returned values but others were zero.
> fix: return offset properly in absoluteWebLocations

- lib/commands/element.js
- lib/commands/general.js
- lib/commands/gesture.js
- lib/commands/screenshots.js
- lib/commands/web.js
- lib/driver.js
- package.json
- test/unit/commands/element-specs.js
The current logic is not very flexible and does not allow elements whose ids contain non-digit chars. Also it might potentially create a memory leak, because `this.webElementIds` array never gets shifted.
> refactor: Change web elements caching logic

- lib/build-wda.js
- package.json
We can't rely on directory hierarchies to find the script within WDA.
Also, it turns out that what we wanted out of this script was different anyway.
> fix: update build-wda script to a regular file

- lib/commands/gesture.js
- test/unit/commands/gesture-specs.js
Addresses https://discuss.appium.io/t/cannot-use-velocity-in-ios-specific-gestures/34468
> fix: Pass velocity to `mobile: swipe` call

- README.md
- lib/commands/execute.js
- lib/commands/location.js
- lib/desired-caps.js
- lib/driver.js
`service.resetLocation();` to reset the location service on a real device is available in our ios-device repo, but we do not implement it in XCUITest layer.
This PR adds:
1. `mobile:resetLocationService` to allow users to be able to reset the location service in the session
2. `appium:resetLocationOnRealDevice` to allow reset the location service in the session deletion as teardown.
> feat: add reset location service call in mobile command, and capabilities

- lib/commands/cookies.js
👋  Hi folks, 
Currently using appium to run real device tests, however, running into issues with incorrectly encoded cookie values causing difficulty. On inspection of the code I found that there was no guard against a malformed cookie value. 
I've raised this PR to start a conversation if this is a change that you folks would consider? 
Many thanks!
> Decode cookies safely

- lib/commands/context.js
Related to https://github.com/appium/appium/issues/16036#issuecomment-960491115
I think we do not need to this restriction.
We currently drop `autoLaunch: false` usage. Alternatively, we provide non-app and non-bundleid pattern to achieve like 
1. launch a bundle id with autoLaunch: false
2. do some setup before launching the bundle id
3. launch the bundle id
4. access to the webview
This was added in https://github.com/appium/appium-xcuitest-driver/pull/1020 , but probably we did not discuss about this point then.
We had `autoLaunch: false` usage then, so the above pattern was not an issue then.
> feat: remove bundle id restriction in get contexts

- package.json
This PR adds a schema as per appium/appium#15938, adapted from the `argsConstraints` field.
We will want to remove `argsConstraints` from the main class (soon) assuming Appium 1.x does not support it.
> feat(config): add schema support for Appium 2.0

- package.json
`platformNames` is `tvOS` for tvOS.
> fix: update platformNames in package.json for appium 2.0

- lib/arg-constraints.js
- lib/driver.js
Constraints are now handled in the schema, and the latest version of Appium supports schemas, so we can remove this.
The logging which previously displayed arguments values passed in through the CLI now only displays values if they overwrite capabilities.
> chore(cli): remove ARGS_CONSTRAINTS

- lib/ios-deploy.js
Related to appium/appium#16201 
Tested after fix: Pass options to installApp call #1357
Added an extra logging to represent the passed parameters: 
**Before fix** strategy is ignoring: 
```
2021-12-06 09:21:30:834 - [HTTP] --> POST /wd/hub/session/7567419a-5fc0-4760-9c70-26802572d9fd/appium/device/install_app
2021-12-06 09:21:30:834 - [HTTP] {"appPath":"/Users/alexandrivanchenko/Projects/aqa-mobile-testapp/testapp.ipa","options":{"strategy":"ios-deploy"}}
2021-12-06 09:21:30:841 - [debug] [W3C (7567419a)] Calling AppiumDriver.installApp() with args: 
["/Users/alexandrivanchenko/Projects/aqa-mobile-testapp/testapp.ipa",{"strategy":"ios-deploy"},null,null,"7567419a-5fc0-4760-9c70-26802572d9fd"]
2021-12-06 09:21:30:842 - [debug] [XCUITest] Executing command 'installApp'
2021-12-06 …
```
> fix: added "Strategy" parameter to the ios-deploy.js appInstall()

- lib/driver.js
I think this fixes appium/appium#16340.  My bad
It would only set the value from `wdaLocalPort` if it was going to overwrite caps
> fix(driver): correct logic in assignment from cli args

- lib/device-log/ios-crash-log.js
- lib/py-ios-device-client.js
Before we were collecting crash reports from the local file system, but it looks like they rarely end up there, because one needs some time for sync, which is not the case right after an automated test finishes due to an app crash.
py-ios-device though allows to gather crash reports directly from the device under test, which would allow us to basically instantly fetch necessary reports.
> feat: Use py-ios-device to gather crash reports from the device

- README.md
- lib/commands/deviceInfo.js
- package.json
```
> @driver.execute_script 'mobile: deviceInfo', {}
=> {"timeZone"=>"GMT-0800",
"currentLocale"=>"ja_JP",
"model"=>"iPhone",
"uuid"=>"B3D4A74D-8B4B-4F4E-8859-CDE8F3D917BE",
"thermalState"=>0,
"userInterfaceIdiom"=>0,
"userInterfaceStyle"=>"light",
"name"=>"🦉kazu",
"isSimulator"=>false,
"lockdownInfo"=>
{"BasebandCertId"=>3840149528,
"BasebandKeyHashInformation"=> ...,
"BuildVersion"=>"19C56",
"CPUArchitecture"=>"arm64",
"ChipID"=>32768,
"DeviceClass"=>"iPhone",
"DeviceColor"=>"#c8caca",
"DeviceName"=>"🦉kazu",
....}}
```
> feat: add device info via lockdown

- README.md
- lib/commands/app-management.js
- lib/commands/execute.js
- lib/py-ios-device-client.js
Close https://github.com/appium/appium-xcuitest-driver/issues/1385
We now have `py-ios-device`, so this driver can kill an app via instruments service.
Ideally, it would be nice to add such instruments service in appium-ios-device, but currently not.
I wonder the method shold always return `true` though...
I tested this killApp against `com.apple.Maps`. Then, the existing `terminateApp` also killed the app process expectedly. So killApp could take additional preparation time thank the terminateApp so far, but potentially the killApp could kill well than terminateApp in some cases.
Btw, app history by double home button clicks still show the killed app even via `killApp` command sometimes. This is iOS's behavior.
> feat: add appKill mobile command via instruments service

- package.json
To include https://github.com/appium/appium-ios-device/pull/88 as a npm released version.
Since appium v2, each driver starts including shrinkwrap in their packages. We currently need to create a version and release it to update it.
> fix: secured connection error between real devices with OpenSSL v3, the default security level of 1

- README.md
- lib/commands/app-management.js
- lib/py-ios-device-client.js
- package.json
replace appKill implementation with https://github.com/appium/appium-ios-device 's instrument.
After https://github.com/appium/appium-ios-device/pull/89 , I'd like to replace `import { SERVICE } from 'appium-ios-device/build/lib/instrument';` part with `INSTRUMENT_SERVICE`
---
I've tested mobile:killApp command manually on my local.
> feat: replace killApp instrumentation with appium-ios-device/instrument

- README.md
- lib/desired-caps.js
- package.json
Btw, current xcuitest driver no longer depends on webkit debug proxy, so I think we can remove it
> chore: drop unused webkitDebugProxyPort

- README.md
- lib/app-utils.js
- lib/commands/app-management.js
- lib/driver.js
- lib/ios-deploy.js
- lib/real-device-management.js
- test/functional/web/safari-basic-e2e-specs.js
This PR includes:
- Improved logic for `safariInitialUrl` capability. Now setting it to an empty strings makes the driver to skip setting of the initial URL, which saves some time on startup. Also, setting `noReset` to `true` has the same effect if `safariInitialUrl` is not provided
- Device reset now terminates Safari on real devices, previously it had no effect
- Removed some related conditions for legacy platforms (e.g. iOS 12)
> refactor: Tune Safari initialization

- .github/workflows/publish.js.yml
npm v8 in NodeJS 16 is enough as a release task. `npm install -g npm` is not necessary.
> ci: remove unnecessary npm install

- README.md
The pipe in `string|array` is used as a table column divider. Using the HTML character code `&#124;` fixes this.
> Fix broken formatting in docs

- lib/app-utils.js
- lib/driver.js
This PR updates the way application bundles are processed in the driver and moves the appropriate logic to the xcuitest driver instead of having it in the base driver.
Also added some tasty improvements like the one requested by @nextlevelbeard in https://github.com/appium/appium-xcuitest-driver/pull/1408
The PR needs some more attention and extensive testing for different app/platform scenarios.
Main scenarios are:
Real device
- .app bundle
- .ipa bundle
- .zip bundle with .app
- .zip bundle with .ipa
- .zip bundle with multiple .app/.ipa, where only one bundle matches the target platform
- url to .ipa bundle
- url to a .zip bundle
- invalid bundle
Simulator
- all the same above
All cases except the first one must also be verified regarding valid caching.
I would be very grateful …
> feat: Update application bundles processing

- lib/device-log/ios-crash-log.js
Fix https://github.com/appium/appium/issues/17346
This PR makes the ips file be read as crash log for the emulator. According to [this post](https://stackoverflow.com/questions/69858174/how-to-read-translate-macos-12-monterey-ips-crash-files)
> Starting in macOS 12 (Monterey), the system apparently writes crash file as .ips files, instead of the traditional .crash file format.
getLogs() [reads ips files on real  device](https://github.com/YueChen-C/py-ios-device#get-crash-syslog) but not on simulator.
> fix: make ips files readable as crash log

- README.md
- lib/commands/certificate.js
- lib/commands/execute.js
- package.json
Piggybacking off the work @mykola-mokhnach did for https://github.com/appium/appium-xcuitest-driver/pull/1369
This adds a mobile command to list certificates installed on the device. It only works on real devices where [py-ios-device](https://github.com/YueChen-C/py-ios-device) tool is available on the server machine. I did not see a mechanism in WDA, etc for getting this info from simulators.
> feat: listCertificates command for real devices

- docs/real-device-config.md
- docs/wda-custom-server.md
This is a bit advanced, but potentially this will help users who would like to manage signed `.app` package.
Btw, this method (generate .app -> start it without xcodebuild command) can use free account as well.
Codesign thing is more advanced, but we may be able to add more example here, real-device-config or wda-custom-server, in the future
> docs: add xcodebuild for general ios/tvos devices way

- docs/real-device-config.md
Generic builds are now available in WDA releases page. The link to the releases may help since the packages are generated with the same command of `xcodebuild`
> docs: add a link to WDA/releases in the real device config

- ci-jobs/templates/xcuitest-e2e-template.yml
- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/element-e2e-specs.js
- test/functional/basic/find-e2e-specs.js
- test/functional/desired.js
also drops `noReset` capability so that tests under `functional/basic` won't affect each other
> test: convert wd method calls to webdriverio method calls for find-e2e-specs

- README.md
- docs/ci-setup.md
Summary of some pitfalls and solutions to save some time when setting up Appium with CI.
https://github.com/appium/appium/issues/17818
> docs: Add documentation on XCUITest usage in a CI environment 

- ci-jobs/templates/xcuitest-e2e-template.yml
- test/functional/basic/alert-e2e-specs.js
- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/element-e2e-specs.js
- test/functional/basic/find-e2e-specs.js
- test/functional/basic/touch-id-e2e-specs.js
- test/functional/device/accessibility-e2e-specs.js
- test/functional/device/file-movement-e2e-specs.js
- test/functional/device/otherApps-e2e-specs.js
- test/functional/device/performance-e2e-specs.js
- test/functional/device/xctest-e2e-specs.js
- test/functional/helpers/session.js
- test/functional/web/safari-alerts-e2e-specs.js
- test/functional/web/safari-basic-e2e-specs.js
- test/functional/web/safari-execute-e2e-specs.js
- test/functional/web/safari-window-e2e-specs.js
see https://github.com/appium/appium-xcuitest-driver/pull/1464#issuecomment-1348286595
Now device CI fails because the test assumes WDA is prebuilt but there is no WDA.
This was fine before I changed the test name in the https://github.com/appium/appium-xcuitest-driver/pull/1464 . This PR changed the order of the test and now the accessibility test is the first one.
> test: reuse prebuilt WDA as much as possible among functional tests

- lib/commands/appearance.js
fixes https://github.com/appium/appium-xcuitest-driver/issues/1470
Actually, the receiver in WDA has only `withoutSession`.
```
[[FBRoute POST:@"/wda/device/appearance"].withoutSession respondWithTarget:self action:@selector(handleSetDeviceAppearance:)],
```
I haven't tested this yet, will test a bit later
> fix: /wda/device/appearance as withoutSession

- lib/driver.js
releaseActions() and actions() (which [calls releaseActions](https://github.com/webdriverio/webdriverio/blob/3f551214691d14eebabff84f2625b2624fae9ef4/packages/webdriverio/src/commands/browser/actions.ts#L34)) of webdriverio doesn't work because it's routed to WDA:
```
[debug] [XCUITestDriver@65de (dc729734)] Matched '/session/dc729734-1137-4405-8808-b2f2eadc0c60/actions' to command name 'releaseActions'
[debug] [XCUITestDriver@65de (dc729734)] Proxying [DELETE /session/dc729734-1137-4405-8808-b2f2eadc0c60/actions] to [DELETE http://127.0.0.1:8100/session/A9A3C9DC-6CC4-4DEC-B352-62518C890856/actions] with no body
[XCUITestDriver@65de (dc729734)] Got response with status 404: {"value":{"error":"unknown command","message":"Unhandled endpoint: …
```
> fix: releaseActions fails due to unhandled endpoint

- ci-jobs/templates/ios-e2e-template.yml
- ci-jobs/templates/xcuitest-e2e-template.yml
- package.json
- test/functional/device/xctest-e2e-specs.js
I thought I enabled the XCTest on CI in [the previous PR](https://github.com/appium/appium-xcuitest-driver/pull/1471) but I forgot to enable `LAUNCH_WITH_IDB` variable 🤦 
And I think it's unable to run it because the CI uses XCode 13.2 that has an issue with concurrency library (see [this issue](https://github.com/appium/appium-idb/pull/66)). I just added the code to skip it by checking xcode version.
Is it possible to update the XCode version in CI?
> test: Enable xctest ci (but it requires xcode 14)

- lib/desired-caps.js
ref. https://github.com/appium/appium-xcuitest-driver/pull/1479#discussion_r1058298053
It doesn't seem to be used anymore.
> chore: remove tapWithShortPressDuration cap

- package.json
Latest xcuitest driver still does not have recent wda updates, so we can run a release script once. (package.json update itself is not necessary, but we need to bump published npm-shrinkwrap.json in xcuitest)
> fix: update WDA to include snapshots/maxDepth fixes

- README.md
This is a dummy readme update to push a new version to apply `NOTCHED_DEVICE_SIZES` update in https://github.com/appium/appium-xcuitest-driver/pull/1490 to close https://github.com/appium/appium/issues/17014
> fix: Update NOTCHED_DEVICE_SIZES for nativeWebTapStrict (part of #1490)

- .github/workflows/unit-test.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: Update unit tests CI job

- lib/commands/web.js
In https://github.com/appium/appium-xcuitest-driver/pull/1484#discussion_r1085993711, I noticed https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/cookies.js had `getCookies`, `deleteCookie` and `_deleteCookie` via remote-debugger's WebInspector code instead of JS script right now.
So it probably would be nice to remove the unused methods in `web.js`.
I checked in a real device, so not in a simulator yet. I'll do a double-check with a simulator later if the current mater uses which code.
> chore: remove unused cookies code

- lib/commands/web.js
- package.json
This should avoid xcuitest from waiting for too long if the app under test or Safari crashes while waiting for atom response. See https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=24956&view=logs&j=66348596-d35e-5e67-f0f1-be5c1aa44784&t=71e9a390-e9eb-5265-011c-e30f520bcba6 for an example
> chore: Short circuit if the app under test crashes while checking for alerts

- docs/execute-methods.md
Noticed the url https://unix.superglobalmegacorp.com/xnu/newsrc/iokit/IOKit/hidsystem/IOHIDUsageTables.h.html returns 404... maybe removed...?
> docs: fix a url for HID Usage Tables

- lib/py-ios-device-client.js
@mykola-mokhnach I missed this in https://github.com/appium/appium-xcuitest-driver/pull/1529
The py-ios-device client expects the profile name to be passed in with the `--name` option
> fix: Add missing --name option to removeProfile

- test/functional/basic/alert-e2e-specs.js
- test/functional/basic/basic-e2e-specs.js
- test/functional/basic/element-e2e-specs.js
- test/functional/device/accessibility-e2e-specs.js
- test/functional/device/file-movement-e2e-specs.js
- test/functional/driver/driver-e2e-specs.js
- test/functional/web/safari-alerts-e2e-specs.js
- test/functional/web/safari-basic-e2e-specs.js
- test/functional/web/safari-execute-e2e-specs.js
- test/functional/web/safari-window-e2e-specs.js
- test/unit/commands/activeAppInfo-specs.js
- test/unit/commands/alert-specs.js
- test/unit/commands/deviceinfo-specs.js
- test/unit/commands/element-specs.js
- test/unit/commands/file-movement-specs.js
- test/unit/commands/find-specs.js
- test/unit/commands/general-specs.js
- test/unit/commands/gesture-specs.js
- test/unit/commands/location-specs.js
- test/unit/commands/pasteboard-specs.js
- test/unit/commands/proxy-helper-specs.js
`eventually.be.<x>` is used when `x` is not an assertion native to `chai-as-promised`, so it's redundant in the case of `eventually.be.rejected` or `eventually.be.fulfilled`
> chore(test): update some assertions

- lib/commands/general.js
Instead of https://github.com/appium/appium-xcuitest-driver/pull/1539
https://github.com/appium/appium-xcuitest-driver/commit/9b9e6fa860425f3ed2a9130d088889c05e3e10a9#diff-b394cf1ec7843c77eb14478b73321d02c718f7f8123b5416b6d88181627ac690L190-L199 changed the launchApp behavior. The master one did not create a new session between appium/xcuitest and WDA, so after the launchApp method, no commands worked.
This PR brings removed launchApp behavior.
---
The launchApp method removed in this PR was ordinary existed in lib/driver.js, but it seems like nothing used the method in my git history confirmation. `response.currentApp.bundleID` was broken, but has existed since XCUITest driver v2 at least. It means Appium 1.22.3 had the method as well, but no non-reference error occurred for bundleID. We …
> fix: launchApp regression

- lib/commands/web.js
Using `this.remote` for cookies handling (except for setCookies) is current intentional behavior instead of JavaScript call. (https://gist.github.com/KazuCocoa/b935fbca6efa1abf4688cc94bc14366a for reference)
https://github.com/appium/appium-xcuitest-driver/issues/1532
This change will send `_rpc_forwardSocketData` with `Page.` commands.
```
[HTTP] --> GET /session/8cec8681-efd8-4b28-a207-393fcb59d679/cookie
[HTTP] {}
[debug] [XCUITestDriver@17d4 (8cec8681)] Calling AppiumDriver.getCookies() with args: ["8cec8681-efd8-4b28-a207-393fcb59d679"]
[debug] [XCUITestDriver@17d4 (8cec8681)] Executing command 'getCookies'
[debug] [RemoteDebugger] Getting cookies
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:57553', page '1', target 'page-7' (id: 38): …
```
> fix: cookies regression: send Page commands for cookies handling

- package.json
This reverts commit ff96d7cfa209783f58fc053602b7e37889c6241f.
I'm not sure why dependabot merged this, because `get-port` v6 is ESM only and the build should be broken.
I've disabled dependabot entirely.
> fix: revert "chore: Bump get-port from 5.1.1 to 6.1.2 (#1535)"

- .releaserc
This changes three things in `.releaserc` (which controls how `semantic-release` works):
1. Switched the preset from `angular` to `conventionalcommits` to match our changelog and commitlint configurations.
2. Removed the rule which causes `chore`-type commits to be released as patch versions.  This was causing many unnecessary releases.
3. Hide `chore`- and `refactor`-type commits from the changelog.  These are typically not useful to end users.
@KazuCocoa I see that you explicitly added the configuration to make `chore`-type commits cause patch releases, but I could not find any reasoning/intent as the original PR text (#1458) was empty.
> chore: update .releaserc

- lib/commands/pcap.js
- lib/commands/record-audio.js
- lib/driver.js
- lib/execute-method-map.ts
These were missing from the execute method map, and also needed to be refactored.
> fix(commands): fix startAudioRecording and stopAudioRecording execute methods

- .github/workflows/docs.yml
The docs preview for PRs was useless--like in Appium--since we cannot allow any fork to commit to `gh-pages`. The result is that the preview would only ever be generated against `master`, and the changes from the PR would not be reflected in the output.
Will figure this out again later, since Appium has the same problem.
> chore(ci): remove docs preview

- lib/commands/permissions.js
- lib/execute-method-map.ts
These were backwards, per the documentation.
> fix(command): flip args for mobile: getPermission

- lib/commands/general.js
- lib/driver.js
This API is expected to return a boolean true value if an app was removed successfully
> fix: Add missing return to removeApp API

- lib/commands/execute.js
- package-lock.json
- test/unit/driver-specs.js
How this works may change in the future, but XCUITestDriver users expect to be able to use `mobile:foo` instead of or in addition to `mobile: foo`.
Any change on the Appium side affects more than just this driver, so the change should happen here for now to fix the extant regression.
In addition, updated `package-lock.json` since it was out-of-date w/r/t the package version.  See https://github.com/appium/appium/issues/18553
Closes https://github.com/appium/appium/issues/18551
> fix: make whitespace in execute methods insignificant

- .github/workflows/publish.js.yml
- .releaserc
- package-lock.json
It seems like npm shrinkwrap renamed package-lock.json so the semantics-release adds the lock file as "delete" in https://github.com/appium/appium-xcuitest-driver/commit/0021c5f49b27ef48b31aa3e69d5f97744ad880e3
Let me revert the change for now to keep the lock file. I'll look into it again.
Probably... we should keep the lock file with lower supported npm version's lock file only... instead...?
> chore: bring packag-lock.json back to the repository

- docs/index.md
- package.json
Eventually the mike command should be like:
```
/Users/kazuaki/.asdf/installs/python/3.10.2/bin/mike deploy --push --config-file /Users/kazuaki/GitHub/appium-xcuitest-driver/mkdocs.yml --remote origin --branch docs-site --message 'docs: auto-build docs for appium-xcuitest-driver@4.24.3' --rebase --update-aliases 4.24 latest
```
but current command generated:
```
ERROR                                                                                                                                                                                                                 docutils:cli 21:59:24
Command '/Users/kazuaki/.asdf/installs/python/3.10.2/bin/mike deploy --config-file /Users/kazuaki/GitHub/appium-xcuitest-driver/mkdocs.yml --remote origin --branch docs-site --message 'docs: …
```
> docs: tweak docs

- .github/workflows/update-package-lock.yml
Closes https://github.com/appium/appium/issues/18553
This Pr maybe will create a pr to update the version. Once I have confirmed this will work, I'll run this after the release task
> ci: add a task to update driver version in the package-lock

- lib/driver.js
`usePreinstalledWDA` does not use xcodebuild, so it does not need to get xcode version and xcodebuild something such as xcodebuild system file lock. This PR fixes `this.wda.setupCaching()`'s usage condition.
I think this will also resolve https://github.com/appium/appium/issues/18641
> fix: tune usePreinstalledWDA to behave as similar to webDriverAgentUrl

- lib/execute-method-map.ts
- lib/py-ios-device-client.js
- Adds --network flag to py-ios-device commands otherwise network devices (like an Apple TV 4K) are [ignored](https://github.com/YueChen-C/py-ios-device/blob/main/ios_device/util/usbmux.py#L158)
- Adds missing command `mobile: removeCertificate` to method map
> fix: Support network devices with py-ios-device + add missing method map

- package.json
This should hopefully fix some warnings about potential incompatibility with Appium 2.0.0-rc.3+.
> fix(deps): change Appium peer dep from pinned to compatible

- lib/driver.js
- lib/simulator-management.js
- lib/utils.js
So the logic there is the following:
- If udid is provided and no real device has been matched then we try to match a simulator with the given udid. If no match is found then an error is thrown
- If platformVersion is provided then we try to match the first available device with the given version or a particular device if deviceName has been provided
- If a new simulator device has been created by the driver then it must also be destroyed on session cleanup
Related to https://github.com/appium/appium/issues/18814
> chore: Tune Simulator device retrieval and cleanup

- docs/run-prebuilt-wda.md
- docs/run-preinstalled-wda.md
It would be safe to address this method does not work for ios 17 env so far
> docs: address ios 17 thing in run-preinstalled-wda

- lib/commands/general.js
- lib/commands/gesture.js
- lib/commands/web.js
- package-lock.json
- package.json
- test/functional/web/safari-alerts-e2e-specs.js
- test/functional/web/safari-nativewebtap-e2e-specs.js
this is technically a breaking change since we're removing a deprecated method (`moveTo`). not sure how much we care.
fixes appium/appium#17013
fixes appium/appium#18951
> feat: use new selenium atoms from remote debugger

- lib/driver.js
- test/functional/web/helpers.js
- test/functional/web/safari-basic-e2e-specs.js
- test/unit/driver-specs.js
We want to load the startup url as fast as possible to reduce the session startup duration. Thus loading the URL available on the device itself would be the fastest.
> chore: Align simulator and real device default startup urls

- .releaserc
seems weird... but `npx semantic-release --dry-run --debug` also ended below:
```
n' + '\n' + 'Bumps [@types/lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/lodash) from 4.14.197 to 4.14.198.\n' + '- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)\n' + '- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/lodash)\n' + '\n' + '---\n' + 'updated-dependencies:\n' + '- dependency-name: "@types/lodash"\n' + '  dependency-type: direct:development\n' + '  update-type: version-update:semver-patch\n' + '...\n' + '\n' + 'Signed-off-by: dependabot[bot] <support@github.com>', gitTags: '' }, { commit: { long: '91584c910f2f800bc741bb205a71e69dadfe9d42', short: '91584c91' }, tree: { long: …
```
> ci: use angular as the preset

- lib/commands/permissions.js
- lib/commands/source.js
- lib/driver.js
- package-lock.json
- package.json
- test/unit/commands/source-specs.js
I'm thinking to add a setting like `excludedAttributes` to exclude these attributes for `/source` endpoint. 
I also think of https://github.com/appium/appium-inspector/issues/1062 for lower appium versions, but this is via settings api.
Then, `/source` endpoint will apply the settings always. (This exclude won't apply for `useJSONSource` since it is json format for WDA)
Before that, I found we could remove existing old implementation that we may be able to remove for now. Maybe I think we can drop for now, what do you think?
> chore: remove old implementation in get page source

- lib/commands/app-management.js
- lib/commands/performance.js
- lib/ios-deploy.js
- lib/xcrun.js
- package-lock.json
Related to https://github.com/appium/appium/issues/18749
This PR kills the process directly against iOS 17 devices via `devicectl` command without appium-ios-device side modifications.
```
driver.execute_script 'mobile:killApp', {bundleId: "com.apple.mobilesafari"}
```
terminateApp via XCTest (WDA) works without any issues, but instrument service gets an issue in iOS 17 with current appium-ios-device implementation. This could have small overhead than existing implementation (because of `devicectl`), but should not be a big issue for this usage
---
**Note**
Maybe we need to build a wrapper module for `devicectl` to use it widely for our use. This PR should refer to it later.
> fix: terminateApp with devicectl for iOS 17

- docs/troubleshooting.md
Trying to address https://github.com/appium/WebDriverAgent/pull/774 behavior, and workaround to terminate the app process in https://appium.github.io/appium-xcuitest-driver/5.3/troubleshooting/
> docs: troubleshooting.md

- .github/workflows/publish.js.yml
- .releaserc
I wonder current unexpected `npm-shrinkwrap.json` removal from npm push was by this order diff. Let me check if this helps.
Expected behavior is `npm-shrinkwrap.json` present in the npm package:
current (npm-shrinkwrap.json does not exist)
```
2023-09-23T23:25:31.9799760Z npm notice 17.4kB  lib/utils.js                                     
2023-09-23T23:25:31.9800160Z npm notice 329B    lib/xcrun.js                                     
2023-09-23T23:25:31.9800570Z npm notice 6.0kB   package.json                                     
2023-09-23T23:25:31.9801090Z npm notice 1.9kB   scripts/build-docs.js                            
2023-09-23T23:25:31.9801630Z npm notice 1.2kB   scripts/build-wda.js                             
2023-09-23T23:25:31.9802170Z npm notice 411B …
```
> fix: (dummy) releaserc update

- lib/driver.js
- test/unit/driver-specs.js
Extract https://github.com/appium/appium-xcuitest-driver/commit/00ed99fdd75d54d74ab1971f5998ed2173b8b94d from https://github.com/appium/appium-xcuitest-driver/pull/2050 to here to make diff small.
This PR will remove `undefined` usage for `installToRealDevice` and `installToSimulator`
> fix: get bundleId for other apps before calling installation

- docs/execute-methods.md
- lib/commands/location.js
https://github.com/appium/appium/issues/18749 clarified iOS 17 requires `mobile:setSimulatedLocation` to simulate the location. We could explicitly address the fact in the documentation
> docs: address ios 17 for setSimulatedLocation

- README.md
In order to not annoy non-Mac users, mention the OS requirement before the `npm driver install` command.
> docs: note MacOS requirement in README.md

- docs/execute-methods.md
I can observe users are sometimes confused about how to call Execute methods from their code. This should help them.
> docs: Add source code examples for Execute Methods

- docs/execute-methods.md
- lib/commands/keyboard.js
- lib/commands/types.ts
- lib/driver.js
- lib/execute-method-map.ts
- package-lock.json
- package.json
Based on https://github.com/appium/WebDriverAgent/pull/797/
> feat: Add 'mobile: keys' extension

- docs/execute-methods.md
* Update Java `executeScript` code example to use `Map.ofEntries` instead of `Map.of`
* Unlike `Map.ofEntries`, `Map.of` is limited to 10 key-value pairs, however, unlike `uiautomator2`, `xcuitest` does not have any extension methods that support more than 10 parameters. Still, this may not be the case in the future, so it is safer to use common terminology across both drivers.
> docs: update Java executeScript example

- docs/run-preinstalled-wda.md
Maybe it is worth addressing the method to remove `XC*.framework` what we do in https://github.com/appium/WebDriverAgent/blob/master/.github/workflows/publish.js.yml to build a wda package for real devices across OS versions without xcodebuild. A hacky workaround like https://github.com/appium/WebDriverAgent/pull/800 is not necessary with this.
> docs: add a way to call rm xctest frameworks in run-preinstalled-wda

- .github/workflows/docs.yml
- .github/workflows/unit-test.yml
Currently there are a lot of dependency PRs from dependabot. Any new commits on master cause dependabot to force-push them onto its dependency update branches. This triggers both the `push` and `pull_request` workflows for docs and unit tests, creating unnecessary work.
With this change, such force-pushes should only trigger the `pull_request` workflows.
> ci: run CI only for master branch

- lib/driver.js
- test/unit/language-specs.js
I observed the following appium server log which appium-xcuitest-driver pushes language and locale arguments when retrying `/session` api call to WDA. 
```
07:24:34:138 d [38;5;64m[XCUITestDriver@68b6 (5cc2d54a)][0m Sending createSession command to WDA
07:24:34:139 d [38;5;64m[XCUITestDriver@68b6 (5cc2d54a)][0m Matched '/session' to command name 'createSession'
07:24:34:140 d [38;5;64m[XCUITestDriver@68b6 (5cc2d54a)][0m Proxying [POST /session] to [POST http://127.0.0.1:50201/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.trident-qa.ScrollSleuth","arguments":["-AppleLanguages","(en)","-NSLanguages","(en)","-AppleLocale","en_US"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingF …
```
> fix: assign deeply cloned processArguments for starting a WDA session

- docs/execute-methods.md
- package.json
Address https://github.com/appium/appium-ios-simulator/pull/406 in the setPermission docs
> feat: set location permission via xcrun simctl privacy

- .github/workflows/publish.js.yml
- .npmrc
Exclude dev and peer dependencies from npm-shrinkwrap.json upon release. This PR tries to avoid the following behavior.
1. `npm prune ...` creates `package-lock.json` and the lock file contains dev/peer dependencies
2. As `npm shrinkwrap` creates `npm-shrinkwrap.json` based on `package-lock.json`, dev/peer dependencies are included in the published `npm-shrinkwrap.json`
refs. https://github.com/appium/appium-xcuitest-driver/pull/2189
By following the updated workflow manually, confirmed no dev/peer dependencies are included in npm-shrinkwrap.json. (17581 lines at [v5.11.0](https://www.npmjs.com/package/appium-xcuitest-driver/v/5.11.0?activeTab=code) with many `"dev": true` -> 3924 lines without `"dev": true`)
> fix: tune shrinkwrap for a release

- .github/workflows/publish.js.yml
It seems like still newer npm generates package-lock. Let me run with no package lock flag. My local seems good
> fix: tune release module

- .github/workflows/publish.js.yml
Ok, I think this is better.
`npm install` to run tests
Then, clear them and run prune:
> fix: tune to minimize release module

- package.json
To release a version with https://github.com/appium/appium-ios-simulator/pull/407 explicitly
> fix: keep backward compatibility for the value of set location command via xcrun simctl privacy

- lib/commands/navigation.js
It looks like sending `Menu` button in tvOS behaves "back" behavior.
A button below is the menu in the recent remote control.
> feat: use Menu button for tvOS in driver.back

- lib/ios-fs-helpers.js
While pushing in parallel it makes sense to push larger files first
> chore: Sort files to push by size

- docs/guides/run-preinstalled-wda.md
It looks like https://github.com/doronz88/pymobiledevice3 supports XCTest process starts right now.
```
Usage example:
iOS<17:
python3 -m pymobiledevice3 developer dvt xcuitest com.facebook.WebDriverAgentRunner.xctrunner
iOS>=17:
python3 -m pymobiledevice3 developer dvt xcuitest com.facebook.WebDriverAgentRunner.xctrunner --tunnel $UDID
```
> docs: update run-preinstalled-wda

- CHANGELOG.md
semantics release appends new content on the top, so we can add more information for the past sections.
Maybe it is nice to address  https://github.com/appium/appium/issues/19716 in the changelog.
> docs: address dialog thing in CHANGELOG.md

- package.json
This revert will fix https://github.com/appium/appium/issues/19716 for xcuitest driver v5.
The change will be in xcuitest driver v6.
cc @eglitise
> fix: revert active application detection fix added in 5.14.1

- docs/reference/execute-methods.md
- lib/commands/gesture.js
- lib/driver.js
- lib/execute-method-map.ts
- package.json
- test/unit/commands/gesture-specs.js
BREAKING CHANGE: Removed the unused getCoordinates API
BREAKING CHANGE: Changed arguments order for various gesture extensions
BREAKING CHANGE: Bumped WDA to ^6.0.0, which includes fixes for the active application detection
Updated various gesture extensions to align them with recent WDA fixed made in https://github.com/appium/WebDriverAgent/pull/843
This restores https://github.com/appium/appium-xcuitest-driver/pull/2313 erroneously merged without bumping the major driver version
> feat: Unify gesture extensions

- CHANGELOG.md
So that we can point the change log out for users in case we get reports
> docs: address the system dialog handling in the changelog

- lib/app-utils.js
- lib/driver.js
@KazuCocoa Do you have an intel-based mac where we could verify it?
> chore: Add validation of Simulator binary architecture

- lib/commands/location.js
Related to https://github.com/appium/appium/issues/19761
It looks like simulators need to use simulated locations right now. I'm not sure this is for all simulators nowadays, so lets me update the error message right now instead of returning an error for all simulator cases
> chore: add a guide for the simulated location

- docs/guides/troubleshooting.md
Maybe it would be nice to address the dialog thing in troubleshooting
> docs: add hints to interact with system dialogs

- docs/reference/commands.md
- lib/commands/gesture.js
- lib/commands/proxy-helper.js
- lib/driver.js
- lib/method-map.js
- package.json
- test/unit/commands/gesture-specs.js
BREAKING CHANGE: Removed the following obsolete APIs:
- performTouch
- performMultiAction
Based on https://github.com/appium/WebDriverAgent/pull/847
> feat: Remove obsolete MJSONWP touch actions

- docs/reference/commands.md
- lib/commands/location.js
[update]
Let's return the result of getSimulatedLocation first if available for ios 17+.
---
For iOS 17+, our primary method for setting location is setSimulatedLocation. It would make sense to show log to use `mobile:getSimulatedLocation`. The existing method can get actual device location info, so we don't need to forcefully proxy the request to the mobile:getSimulatedLocation
> feat: return the result of getGeoLocation if available for ios 17+

- lib/commands/proxy-helper.js
- lib/driver.js
- It does not make sense to uninstall WDA when session startup fails, because that means WDA has actually started successfully
- We must short-circuit (e.g. no more reties) if the session startup times out
- Hardcoded repeats for WDA session startup are useless. They only prolong the time to fail.
> fix: Properly handle WDA session startup errors

- docs/guides/troubleshooting.md
I confirmed that when a session started without app/bundleId and started `com.apple.Maps` with activate app later, the session was able to select permission alert if the system have shown permission alert without calling `mobile: alert`, switching application to the spring board explicitly etc. So, I think users who start a session without app/bundleId may not have any issues with v6 changes.
Then, it also would be nice to add this in the troubleshooting.
> docs: more troubleshooting for Interact with dialogs managed by `com.apple.springboard`

- lib/commands/context.js
90 seconds is definitely too much for that by default.
> fix: Update the default timeout for the recent webview detection

- docs/reference/execute-methods.md
- lib/commands/app-management.js
- lib/commands/index.js
- lib/commands/log.js
- lib/commands/xctest-record-screen.js
- lib/devicectl.js
- lib/driver.js
- lib/execute-method-map.ts
- package.json
Based on https://github.com/appium/WebDriverAgent/pull/858
Also put it under a feature flag as it was discussed previously
> feat: Video recording using native XCTest backend

- docs/endpoints.md
These APIs are not supported anymore since v7
> docs: Remove deprecated touch command from the endpoints list

- lib/driver.js
I wondered if we simply can skip the connected devices check with `webDriverAgentUrl` since `webDriverAgentUrl` usually means the caller prepared the device properly for the session
> chore: skip connected device check if the caps had webDriverAgentUrl

- lib/real-device-management.js
- lib/real-device.js
- test/unit/real-device-management-specs.js
`ios-deploy` method usage keeps as-is. This changes `IOSDeploy` object names and the file name.
I have tested with a real device locally
> chore: rename IosDeploy obhect to RealDevice to make the object meaning actual usage

- lib/commands/memory.js
- lib/commands/xctest-record-screen.js
- lib/driver.js
- lib/ios-deploy.js
- lib/real-device-management.js
the command itself failed but below example was this pr's test. The `lib/commands/memory.js`'s instance called the devicectl command properly
```
[HTTP] --> POST /session/882dfb56-d64d-4124-a74e-f1056e9c7200/execute/sync
[HTTP] {"script":"mobile: sendMemoryWarning","args":[{"bundleId":"com.apple.Maps"}]}
[XCUITestDriver@36d5 (882dfb56)] Calling AppiumDriver.execute() with args: ["mobile: sendMemoryWarning",[{"bundleId":"com.apple.Maps"}],"882dfb56-d64d-4124-a74e-f1056e9c7200"]
[XCUITestDriver@36d5 (882dfb56)] Executing command 'execute'
[XCUITest] Executing xcrun devicectl device info apps --device 00008020-000E5CDA0A23002E --include-all-apps --bundle-id com.apple.Maps --quiet --json-output -
[XCUITest] Executing xcrun devicectl device info processes --device 00008020-000E5CDA0A23002E …
```
> chore: include devicectl in IOSDeploy object

- lib/simulator-management.js
```
Error: lib/simulator-management.js(41,10): error TS2339: Property 'map' does not exist on type 'Promise<any>'.
Error: lib/simulator-management.js(50,63): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
Type 'undefined' is not assignable to type 'string'.
npm ERR! code 1
npm ERR! path /home/runner/work/appium-xcuitest-driver/appium-xcuitest-driver
npm ERR! command failed
npm ERR! command sh -c npm run rebuild
npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2024-03-25T00_07_44_898Z-debug-0.log
Error: Process completed with exit code 1.
```
https://github.com/appium/appium-xcuitest-driver/actions/runs/8413083261/job/23034781606
> fix: build error

- lib/real-device.js
Fixes https://github.com/appium/appium/issues/19834 that is similar to https://github.com/appium/appium/issues/18753
```
[XCUITestDriver@c3fa (a8298d6e)] Event 'wdaStartAttempted' logged at 1711345142607 (13:39:02 GMT+0800 (Singapore Standard Time))
uncaughtException: maxObjectCount exceeded
Error: maxObjectCount exceeded
at Object.exports.parseBuffer (/Users/saikrishna/Downloads/git/appium-device-farm/node_modules/appium-xcuitest-driver/node_modules/bplist-parser/bplistParser.js:92:11)
at parseBinaryPlist (/Users/saikrishna/Downloads/git/appium-device-farm/node_modules/appium-xcuitest-driver/node_modules/@appium/support/lib/plist.js:111:22)
at Object.parsePlist (/Users/saikrishna/Downloads/git/appium-device-farm/node_modules/appium-xcuitest-driver/node_modules/@appium/support/lib/plist.js …
```
> fix: uncaughtException: maxObjectCount exceeded in listApplications

- lib/devicectl.js
Fixes https://github.com/appium/appium/issues/19926
It looks like:
> xcrun devicectl device process launch --device 00008020-000E5CDA0A23002E com.trident.WebDriverAgentRunner.xctrunner --terminate-existing --environment-variables '{"USE_PORT":"9900","WDA_PRODUCT_BUNDLE_IDENTIFIER":"com.trident.WebDriverAgentRunner.xctrunner"}'
does not apply arguments properly while it does not raise any errors. It should be:
> xcrun devicectl device process launch --device 00008020-000E5CDA0A23002E --terminate-existing --environment-variables '{"USE_PORT":"9900","WDA_PRODUCT_BUNDLE_IDENTIFIER":"com.trident.WebDriverAgentRunner.xctrunner"}' com.trident.WebDriverAgentRunner.xctrunner
I tested this case before but as part of refactoring in the pr, changed the order. I thought it worked but did not in the …
> fix: set bundle id at the end to make arguments work properly in Devicectl#launchApp

- docs/preparation/real-device-config.md
Add links to "improve session startup performance" from real device config page. They may help readers to see possible methods to configure WDA for real devices as advanced usage.
> docs: add links to improve startup performance

- lib/driver.js
- lib/real-device-management.js
- lib/utils.js
- test/unit/utils-specs.js
We may skip listing of real devices if webDriverAgentUrl is set, but we cannot skip listing of simulators, because we don't know if the given udid belongs to a real device or to a simulator. So we must verify the list of simulators does not contain the given udid to make sure a real device is requested.
> fix: Properly match simulator udid if webDriverAgentUrl is provided

- index.js
- lib/doctor/checks.js
I'd like to use doctor in xcuitest from Flutter driver to check xcuitest-related env check. In Android, appium-android-driver already has the same one like uia2 driver does.
Example usage:
```
import { doctor } from "appium-xcuitest-driver";
doctor.required.XcodeCheck...
doctor.optional.OptionalFfmpegCheck...
```
> feat: export doctor used in xcuitest driver

- lib/app-utils.js
- lib/driver.js
- package.json
- test/unit/app-utils-specs.js
bsdtar utility which is supplied together with macOS is capable to unzip archives in stream. We could use that to speed up driver session startup if the given app is an URL. After this PR is merged the overall app configuration will be MAX(download, unzip) instead of SUM(download, unzip), which is especially beneficial for bigger app archives.
I've tested it with iOS simulator and found no issues.
> feat: Perform bundles extraction in stream

- lib/app-infos-cache.js
Addresses https://github.com/appium/appium/issues/20075
> fix: Properly cache manifests for .ipa bundles containing multiple apps

- docs/guides/run-preinstalled-wda.md
It looks like this removal thing helps only for real devices https://github.com/appium/WebDriverAgent/pull/868#issuecomment-2147927237 . Explicit "for real devices" may reduce confusion.
> docs: address real devices in docs/guides/run-preinstalled-wda

- package.json
To include https://github.com/appium/appium-ios-simulator/pull/431
> fix: system prompt for Apple ID sign translation for simulators

- lib/commands/log.js
After the npmlog has been replaced with the custom fork we have proper timestamps available there
> fix: Add proper timestamps to server logs

- lib/ios-fs-helpers.js
I found a regression in https://github.com/appium/appium-xcuitest-driver/pull/2388/files#diff-22d12fc5b181e17350b50e15778689447222790c00e7e8303e8973bcdd91a8fbR204
When I test a file upload (e.g. `d.push_file '@com.apple.Keynote:documents/sample.png', (File.read '/Users/kazu/github/ruby_lib_core/sample.png')`), I observed no-response behavior as below:
```
[HTTP] --> POST /session/d57aaa4f-5f82-45e8-a55f-0f7f093c7aa5/appium/device/push_file
...
[XCUITestDriver@61a8 (d57aaa4f)] Executing command 'pushFile'
[XCUITest] Parsed container type: documents
```
Maybe... in buffer case, should the write stream call `end` after `write`....?
With this change:
```
[XCUITestDriver@601b (fe85e621)] Executing command 'pushFile'
[XCUITest] Parsed container type: documents
[XCUITest] Successfully pushed the …
```
> fix: stream end after write in a file push

- lib/commands/recordscreen.js
This is not "fix" but we intentionally put the max limit as 1800 right now.
According to https://github.com/appium/appium/issues/20265#issuecomment-2176518291 , it could be `4293` as ffmpeg.
So, we probably could put the max as `4200` instead. I also wondered if we could remove the max limitation, but this would give a better error response than printing error message in the appium server log only.
> fix: relax the max of recording limitation to 4200 sec as timeLimit

- lib/commands/screenshots.js
Starting a discussion @mykola-mokhnach 
- is that a good enough way to take viewport screenshots for web? Do we care that this would (positively) impact customers tests?
- does appium have a way to take full page screenshots?
- do we wanna touch the take element screenshot code?
- TODO: upgrade to latest appium-remote-debugger package once https://github.com/appium/appium-remote-debugger/pull/386 is merged
> feat: take viewport screenshot using safari remote debugger

- lib/devicectl.js
Related to https://github.com/appium/appium/issues/20290
> fix: Apply the default exec timeout if not provided explicitly

- lib/commands/log.js
- lib/commands/types.ts
- lib/device-log/helpers.ts
- lib/device-log/ios-crash-log.js
- lib/device-log/ios-device-log.js
- lib/device-log/ios-log.js
- lib/device-log/ios-performance-log.js
- lib/device-log/ios-simulator-log.js
- package.json
This is probably the first PR  out of many. I would like to streamline all logging-related classes to:
- Avoid code duplication
- Reduce CPU and memory usage as logs are written fairly often
- Make it typed, so it would be easier to work with this hierarchy
> chore: Streamline logging helpers

- lib/commands/log.js
This is needed in order to improve the log listening flow in the flutter driver
> feat: Emit an event on syslog startup

- .github/workflows/functional-test.yml
- .github/workflows/unit-test.yml
- package.json
- test/functional/basic/element-e2e-specs.js
Let's update existing e2e for send_keys with w3c action in selenium client way.
For now, this test should fail without https://github.com/appium/WebDriverAgent/pull/919.
> fix: no actions in w3c actions case

- lib/commands/gesture.js
Related to https://discuss.appium.io/t/i-cant-get-click-with-options-working/43095
> chore: Raise more helpful error if a W3C action contains a web element

- lib/commands/certificate.js
- lib/commands/pcap.js
- lib/driver.js
Fix for https://github.com/appium/appium/issues/20427
`Pyidevice` ctor was not invoked properly, hence the command `mobile: installCertificate` is broken.
> fix: Pyidevice ctor invocations with options object

- lib/commands/context.js
Fixed the async call to selectPage to avoid linter errors and to properly assign the value of `this.selectingNewPage`.
Also refactored the `isUrlIgnored` call to make the method more readable
> fix: Streamline page selection

- docs/reference/execute-methods.md
https://github.com/appium/appium/issues/20438
> docs: add language example in execute methods

- lib/real-device.js
I observed that `xcrun devicectl` could take a few mins some cases.
This PR's `reset` in real-devices.js is called before starting WDA etc.
Safari process will be killed by the WDA in the WDA's new session creation, so this `this.terminateApp(bundleId, String(platformVersion));` here for real device is completely redundant AND it calls `xcrun devicectl` which could make the session preparation long unexpectedly for iOS 17+ as the `xcrun devicectl` behavior.
So, it makes sense to not call it for real devices.
I have tested this does not change existing behavior with noReset, shouldTerminateApp and forceAppLaunch combinations. forceAppLaunch is default `true` so even with this PR, a new session's Safari process is a new one.
> fix: safari process management will be done by WDA

- docs/reference/bidi.md
- mkdocs.yml
Related to https://github.com/appium/appium-xcuitest-driver/pull/2458/
> docs: Document supported BiDi entities

- docs/guides/troubleshooting.md
Adding https://github.com/appium/appium/issues/20591 as troubleshooting.
Maybe users will check `com.apple.springboard` for this dialogs, thus adding this description near place would help so far.
I wondered if we could use `com.apple.ContactsUI.LimitedAccessPromptView` instead of `com.apple.springboard` for iOS 18+ in WDA (since so far, it looks like elements available via `com.apple.springboard` were also available via `com.apple.ContactsUI.LimitedAccessPromptView` as well).
I haven't investigated this `com.apple.ContactsUI.LimitedAccessPromptView` behavior well yet.
> docs: address com.apple.ContactsUI.LimitedAccessPromptView in troubleshooting

- docs/reference/scripts.md
- scripts/build-wda.js
Adding the ability to select devices and versions for cases like https://discuss.appium.io/t/web-driver-agent-issues-with-wda-startup-time/41544.
And probably mine https://github.com/appium/appium/issues/20601#issuecomment-2369354808
> feat: build-wda script parameters

- docs/guides/troubleshooting.md
Address https://github.com/appium/appium-xcuitest-driver/pull/2334 in the troubleshooting that iOS 17.6+ could have a fix.
I haven't observed the issue in iOS 18 so far, so addressing here and maybe can close the PR as Apple side issue.
> docs: add remote debugger disconnection in troubleshooting

- lib/app-utils.js
This PR updates the `verifyApplicationPlatform` function to use `lipo -info` instead of the `file` command for determining the architectures supported by the app’s executable. The change improves accuracy when verifying compatibility on both Intel and Apple Silicon devices by aligning with the consistent output format of lipo.
• **Inconsistent file Output:** The file command’s output can vary based on the system, leading to unreliable architecture detection.
• **Consistent lipo Output:** lipo -info provides consistent architecture details, which makes it a better choice for ensuring the correct Simulator architecture is detected.
• **Simplified Logic:** This change also simplifies string matching and error handling, reducing potential issues with cross-architecture setups.
``` …
```
> fix: use lipo -info instead of file for architecture detection

- package.json
related to https://github.com/appium/WebDriverAgent/pull/946
> fix: bump WDA to fix transient overlay windows handling when respectSystemAlerts is enabled

- lib/commands/source.js
- With useJSONSource as false, source contains accessible attribute 
- With useJSONSource as true, it bypasses the attribute.
> fix: Add accessible attribute to the xml tree in case of useJSONSource

- lib/app-utils.js
Related to https://github.com/appium/appium-xcuitest-driver/issues/2489
> fix: Tune simulator app architecture validation

- lib/commands/context.js
Related to https://github.com/appium/appium/issues/20710
> feat: Return default window handle in native context

- docs/reference/bidi.md
- lib/commands/bidi/constants.ts
- lib/commands/bidi/models.ts
- lib/commands/bidi/types.ts
- lib/commands/context.js
- lib/commands/log.js
- lib/driver.js
- lib/utils.js
https://github.com/appium/appium/issues/20741
> feat: Add a BiDi event upon context change

- docs/reference/execute-methods.md
In the documentation of the mobile: doubleTap command, the mobile: pinch command was being used in the code examples.
> docs: change method command on doubleTap code examples

- docs/reference/bidi.md
- lib/commands/bidi/constants.ts
- lib/commands/bidi/models.ts
- lib/commands/context.js
After talking to @christian-bromann we have decided to update the event name up to the standard, which required it to have a custom prefix. The old one is still there, has been marked as deprecated, and will be removed after the next driver major bump.
> chore: Tune contextUpdated event generation

- docs/reference/execute-methods.md
Currently the :mm: combo creates an emoji flag in the Example section for the `mobile: getDeviceTime' command
> docs: remove emoji flag from `mobile: getDeviceTime` Example

- package.json
Specifically to get this change https://github.com/appium/appium-ios-device/pull/190 which unblocks usage of `usbmuxd` running in non-root mode.
> feat: Bump appium-ios-device to support USBMUXD_SOCKET_ADDRESS

- docs/guides/file-transfer.md
- lib/commands/file-movement.js
- always use vendContainer to add files without extra app permissions
- adjust docs accordingly
as discussed in https://github.com/appium/appium-xcuitest-driver/issues/2521
I tested this on ios 18 and ios 16 so i its safe to assume it works on 17 as well (i unfortunately don't have an ios 17 device)
> feat: always use vendContainer to add files without extra app permissions

- lib/app-utils.js
Related to https://github.com/appium/appium/issues/14100
> fix: Make sure a proper file names encoding is used while unzipping files from app bundles

- lib/commands/general.js
- lib/commands/proxy-helper.js
- lib/commands/screenshots.js
- lib/commands/web.js
- lib/driver.js
- package.json
- test/functional/basic/basic-e2e-specs.js
- test/functional/web/safari-basic-e2e-specs.js
- test/unit/commands/general-specs.js
BREAKING CHANGE: The following deprecated driver methods were removed:
- getWindowSizeWeb
- getWindowSizeNative
> feat: Switch size retrieval to use the W3C window/rect endpoint

- docs/reference/commands.md
- lib/method-map.js
This PR adds deprecated marks in lib/method-map.js. Some are already mentioned as deprecated in our doc (and current appium master), some will be removed in appium 3 branch. They already have alternatives like extensions.
- https://appium.github.io/appium-xcuitest-driver/latest/reference/commands/ already addressed deprecated
- `/session/:sessionId/appium/element/:elementId/value`
- `/session/:sessionId/keys`
- `/session/:sessionId/appium/receive_async_response`
- `/session/:sessionId/appium/simulator/toggle_touch_id_enrollment`
- `/session/:sessionId/appium/simulator/touch_id`
- `/session/:sessionId/element/:elementId/location`
- `/session/:sessionId/element/:elementId/location_in_view`
- `/session/:sessionId/window/:windowhandle/size`
- `/session/:sessionId/timeouts/async_script`
- …
> chore: add deprecated marks in lib/method-map.js

- lib/method-map.js
These endpoints are part of the JWP protocol. The expected replacement for them is to use corresponding mobile: execute methods
> chore: Add geolocation endpoints to the method map

- docs/guides/run-prebuilt-wda.md
- docs/guides/run-preinstalled-wda.md
I think now `download-wda-sim` and using `usePreinstalledWDA` and `prebuiltWDAPath` can be a recommended way to improve the new session creation performance for simulators.
So... maybe it's nice to move the idea before the `useXctestrunFile` one
> docs: update prebuilt page

- lib/commands/battery.js
- package.json
Then, at least this module-related installation failure would not block the xcuitest driver installation itself.
https://github.com/appium/appium-ios-tuntap/issues/15
> chore: make  appium-ios-remotexpc optional deps

- .github/workflows/functional-test.yml
...
https://github.com/appium/appium-xcuitest-driver/actions/runs/17015041298/job/48236195981?pr=2607
Expected result is the func tests pass
> ci: use ios 18.5 simulator since 18.2 no longer exists

- package.json
Hi everybody!
when I used this library in a TypeScript project, I found that the type hints were missing because index.d.ts was not included in the npm package build, so I submitted this PR.
> fix: add TypeScript declarations to npm package files
